### ISSUE TITLE
[BUG]: ValueError: y_test indices do not match y_pred_indices or split/prediction length

### ISSUE THREAD

**Issue by techwithshadab** [pycaret/pycaret#2575] opened 2022-05-21 22:50 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

I tried using `pycaret-ts-alpha` for training time series forecasting model using daily stock price data, but since stocks doesn't trade all day there are missing data for non-trading dates.  Due to which I'm getting mismatch in the length of y_pred and y_test.

### Reproducible Example

You can see a reproducible example in this [Kaggle Notebook]( https://www.kaggle.com/code/shadabhussain/pycaret-ts-error/notebook)

### Expected Behavior

Model should be trained without any error

### Actual Results

```
python-traceback
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\U6086373\AppData\Roaming\Python\Python37\site-packages\joblib\externals\loky\process_executor.py", line 431, in _process_worker
    r = call_item()
  File "C:\Users\U6086373\AppData\Roaming\Python\Python37\site-packages\joblib\externals\loky\process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "C:\Users\U6086373\AppData\Roaming\Python\Python37\site-packages\joblib\_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\U6086373\AppData\Roaming\Python\Python37\site-packages\joblib\parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "C:\Users\U6086373\AppData\Roaming\Python\Python37\site-packages\joblib\parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "C:\Users\U6086373\AppData\Roaming\Python\Python37\site-packages\pycaret\utils\time_series\forecasting\model_selection.py", line 133, in _fit_and_score
    "y_test indices do not match y_pred_indices or split/prediction "
ValueError: y_test indices do not match y_pred_indices or split/prediction length does not match forecast horizon.
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_18284\1926270964.py in <module>
----> 1 model = exp.create_model("arima")

~\AppData\Roaming\Python\Python37\site-packages\pycaret\time_series\forecasting\oop.py in create_model(self, estimator, fold, round, cross_validation, fit_kwargs, experiment_custom_tags, verbose, **kwargs)
   1724             experiment_custom_tags=experiment_custom_tags,
   1725             verbose=verbose,
-> 1726             **kwargs,
   1727         )
   1728 

~\AppData\Roaming\Python\Python37\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py in create_model(self, estimator, fold, round, cross_validation, predict, fit_kwargs, groups, refit, probability_threshold, experiment_custom_tags, verbose, system, add_to_model_list, X_train_data, y_train_data, metrics, display, **kwargs)
   1481             refit,
   1482             system,
-> 1483             display,
   1484         )
   1485 

~\AppData\Roaming\Python\Python37\site-packages\pycaret\time_series\forecasting\oop.py in _create_model_with_cv(self, model, data_X, data_y, fit_kwargs, round, cv, groups, metrics, refit, system, display)
   1878             return_train_score=False,
   1879             error_score=0,
-> 1880             **additional_scorer_kwargs,
   1881         )
   1882 

~\AppData\Roaming\Python\Python37\site-packages\pycaret\utils\time_series\forecasting\model_selection.py in cross_validate(forecaster, y, X, cv, scoring, fit_params, n_jobs, return_train_score, error_score, verbose, **additional_scorer_kwargs)
    247                 **additional_scorer_kwargs,
    248             )
--> 249             for train, test in get_folds(cv, y)
    250         )
    251     # raise key exceptions

~\AppData\Roaming\Python\Python37\site-packages\joblib\parallel.py in __call__(self, iterable)
   1052 
   1053             with self._backend.retrieval_context():
-> 1054                 self.retrieve()
   1055             # Make sure that we get a last message telling us we are done
   1056             elapsed_time = time.time() - self._start_time

~\AppData\Roaming\Python\Python37\site-packages\joblib\parallel.py in retrieve(self)
    931             try:
    932                 if getattr(self._backend, 'supports_timeout', False):
--> 933                     self._output.extend(job.get(timeout=self.timeout))
    934                 else:
    935                     self._output.extend(job.get())

~\AppData\Roaming\Python\Python37\site-packages\joblib\_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

~\.conda\envs\p_37\lib\concurrent\futures\_base.py in result(self, timeout)
    433                 raise CancelledError()
    434             elif self._state == FINISHED:
--> 435                 return self.__get_result()
    436             else:
    437                 raise TimeoutError()

~\.conda\envs\p_37\lib\concurrent\futures\_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

ValueError: y_test indices do not match y_pred_indices or split/prediction length does not match forecast horizon.
```

### Installed Versions

```
System:
    python: 3.7.13 (default, Mar 28 2022, 08:03:21) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\U6086373\.conda\envs\p_37\python.exe
   machine: Windows-10-10.0.19041-SP0

Python dependencies:
          pip: 22.1.1
   setuptools: 62.3.2
      pycaret: 3.0.0
      sklearn: 1.0.2
       sktime: 0.10.1
  statsmodels: 0.13.2
        numpy: 1.21.6
        scipy: 1.7.3
       pandas: 1.3.5
   matplotlib: 3.5.2
       plotly: 5.8.0
       joblib: 1.0.1
        numba: 0.55.1
       mlflow: 1.26.0
     lightgbm: 3.3.2
      xgboost: 1.6.1
     pmdarima: 1.8.5
        tbats: Installed but version unavailable
      prophet: 1.0
      tsfresh: 0.19.0
```

**Comment by ngupta23** [comment] 2022-05-25 11:35
I think this is because your data has missing values or it could also be because of the business week data which was only implemented recently in PyCaret. https://github.com/pycaret/pycaret/issues/1854

Can you try the same code by installing pycaret like this. I think that should resolve the issue. 

```
pip install -U git+https://github.com/pycaret/pycaret.git@develop
```

FYI... This version should be available in pip shortly as a Release Candidate.

**Comment by ngupta23** [comment] 2022-05-25 11:37
Also, the version above on `develop` includes capability to impute the data so if you have missing values, it will help with that as well (check the `setup` docstring on how to add imputation to the pipeline)

**Comment by Shady-Hegazy** [comment] 2022-05-30 18:54
I have the same issue, while the data has no missing values.
I think it might be an issue with the indices conversion back and forth between pycaret and the models.
It occurred to me with Prophet.

**Comment by ngupta23** [comment] 2022-05-31 01:10
@techwithshadab This is working on the `develop` branch with a small change to your code.

https://gist.github.com/ngupta23/9ee31919f73cd8cc2a877ee863cf71c0

The way you have defined the freq is not correct. You have defined it as "D" which means you have values every day. This is really business daily, since you only have values from Monday - Friday. Hence the frequency should be business daily ('B').

That too is not completely accurate since there are some holidays between Monday - Friday for which the data is not returned (missing value), So to workaround, I simply imputed with forward fill. (Technically, you should define this as custom business daily, but that is more complex and given the small number of missing points, ffill seemed to be a good way to proceed).

I am not sure if this will work with the current released version, but the version on `develop` should be released shortly.

```python
# Your solution
# df.index = pd.PeriodIndex(df.index, freq='D')

# My fix
df = df.asfreq("B", method="ffill")
```

![image](https://user-images.githubusercontent.com/33585645/171073815-69056117-d26d-4753-9bfb-ad3221338270.png)


@Shady-Hegazy - Can you file a separate issue for your problem with a reproducible example?

Thanks!

**Comment by ngupta23** [comment] 2022-05-31 01:16
Closing for now. Feel free to reopen if the issue persists.

**Closed** 2022-05-31 01:16 UTC
Labels: bug, time_series, setup, impute
