### ISSUE TITLE
[BUG]: check_fairness doesn't work

### ISSUE THREAD

**Issue by StatsAI** [pycaret/pycaret#2469] opened 2022-04-28 17:41 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the main branch of pycaret.

### Issue Description

Hi, I am getting this bug when I try to run check_fairness

![Bug1](https://user-images.githubusercontent.com/67183539/165813497-449f6515-55cf-4a7b-951e-0efcf1879f8e.PNG)
![Bug2](https://user-images.githubusercontent.com/67183539/165813527-fd823d4e-247d-4dd5-be0f-d8daafafadd6.PNG)

### Reproducible Example

```python
Apologies, I am unable to provide the code due to privacy restrictions.
```

### Expected Behavior

[Cech_fair](https://www.youtube.com/watch?v=mjhDKuLRpM0)

### Actual Results

```python-traceback
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/pandas/core/indexing.py in _get_list_axis(self, key, axis)
   1468         try:
-> 1469             return self.obj._take_with_is_copy(key, axis=axis)
   1470         except IndexError as err:

~/.local/lib/python3.6/site-packages/pandas/core/generic.py in _take_with_is_copy(self, indices, axis)
   3362         """
-> 3363         result = self.take(indices=indices, axis=axis)
   3364         # Maybe set copy if we didn't actually change the index.

~/.local/lib/python3.6/site-packages/pandas/core/generic.py in take(self, indices, axis, is_copy, **kwargs)
   3350         new_data = self._mgr.take(
-> 3351             indices, axis=self._get_block_manager_axis(axis), verify=True
   3352         )

~/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py in take(self, indexer, axis, verify, convert)
   1448         if convert:
-> 1449             indexer = maybe_convert_indices(indexer, n)
   1450 

~/.local/lib/python3.6/site-packages/pandas/core/indexers.py in maybe_convert_indices(indices, n)
    249     if mask.any():
--> 250         raise IndexError("indices are out-of-bounds")
    251     return indices

IndexError: indices are out-of-bounds

The above exception was the direct cause of the following exception:

IndexError                                Traceback (most recent call last)
<ipython-input-85-3357003e8cb8> in <module>
----> 1 check_fairness(tuned_best_model, ['marital'])

~/.local/lib/python3.6/site-packages/pycaret/classification.py in check_fairness(estimator, sensitive_features, plot_kwargs)
   2958         estimator=estimator,
   2959         sensitive_features=sensitive_features,
-> 2960         plot_kwargs=plot_kwargs,
   2961     )
   2962 

~/.local/lib/python3.6/site-packages/pycaret/internal/tabular.py in check_fairness(estimator, sensitive_features, plot_kwargs)
  10421     y_true = np.array(get_config("y_test"))
  10422     X_test_before_transform = get_config("data_before_preprocess").iloc[
> 10423         get_config("X_test").index
  10424     ]
  10425 

~/.local/lib/python3.6/site-packages/pandas/core/indexing.py in __getitem__(self, key)
    877 
    878             maybe_callable = com.apply_if_callable(key, self.obj)
--> 879             return self._getitem_axis(maybe_callable, axis=axis)
    880 
    881     def _is_scalar_access(self, key: Tuple):

~/.local/lib/python3.6/site-packages/pandas/core/indexing.py in _getitem_axis(self, key, axis)
   1485         # a list of integers
   1486         elif is_list_like_indexer(key):
-> 1487             return self._get_list_axis(key, axis=axis)
   1488 
   1489         # a single integer

~/.local/lib/python3.6/site-packages/pandas/core/indexing.py in _get_list_axis(self, key, axis)
   1470         except IndexError as err:
   1471             # re-raise with different error message
-> 1472             raise IndexError("positional indexers are out-of-bounds") from err
   1473 
   1474     def _getitem_axis(self, key, axis: int):

IndexError: positional indexers are out-of-bounds
```

### Installed Versions

<details>
2.3.6
</details>

**Comment by ngupta23** [comment] 2022-04-28 19:02
It is hard to debug without a reproducible example. Can you try to replicate with dummy data and dummy code. We do not need your actual data or code, just something with which we can reproduce and debug.

**Comment by ngupta23** [comment] 2022-07-01 09:19
@StatsAI We will close this for now due to missing information. Feel free to provide a reproducible example and reopen this issue. Thanks!

**Closed by ngupta23** 2022-07-01 09:19 UTC
Labels: bug, missing_info, fairness
