### ISSUE TITLE
All result AUC = 0 with compare_model

### ISSUE THREAD

**Issue by houpdelta** [pycaret/pycaret#3922] opened 2024-02-27 17:24 UTC
Hello, 
I am new and I don't know if it is an error from me.
AUC doesn't work.
![Capture d’écran 2024-02-25 173622](https://github.com/pycaret/pycaret/assets/10964021/693a8fcc-21a3-4aee-b174-028dd72ff0be)
pycaret: 3.3.0
python:3.10.13

I found a main warning in log related to metric.py

Regards

_Originally posted by @houpdelta in https://github.com/pycaret/pycaret/discussions/3918_

**Comment by celestinoxp** [comment] 2024-02-27 20:14
Duplicate of: https://github.com/pycaret/pycaret/issues/3916

**Comment by houpdelta** [comment] 2024-03-02 11:59
Hello,

I tried #3926 

but: 
`2024-03-01 19:08:58,832:WARNING:c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method='predict_proba', average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\sklearn\metrics\_scorer.py", line 345, in _score
    y_pred = method_caller(
  File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\sklearn\metrics\_scorer.py", line 87, in _cached_call
    result, _ = _get_response_values(
  File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\sklearn\utils\_response.py", line 210, in _get_response_values
    y_pred = prediction_method(X)
  File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\pycaret\internal\pipeline.py", line 341, in predict_proba
    Xt = transform.transform(Xt)
  File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\sklearn\utils\_set_output.py", line 295, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\pycaret\internal\preprocess\transformers.py", line 233, in transform
    X = to_df(X, index=getattr(y, "index", None))
  File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\pycaret\utils\generic.py", line 103, in to_df
    data = pd.DataFrame(data, index, columns)
  File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\pandas\core\frame.py", line 822, in __init__
    mgr = ndarray_to_mgr(
  File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\pandas\core\internals\construction.py", line 319, in ndarray_to_mgr
    values = _prep_ndarraylike(values, copy=copy_on_sanitize)
  File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\pandas\core\internals\construction.py", line 575, in _prep_ndarraylike
    values = np.array([convert(v) for v in values])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.`

**Comment by houpdelta** [comment] 2024-03-02 13:16
Hello
Tested #3926 

But same error:
`2024-03-02 14:11:43,296:WARNING:c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method=('decision_function', 'predict_proba'), average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
    return super()._score(
  File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\pycaret\internal\metrics.py", line 136, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
  File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\sklearn\metrics\_ranking.py", line 634, in roc_auc_score
    return _multiclass_roc_auc_score(
  File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\sklearn\metrics\_ranking.py", line 707, in _multiclass_roc_auc_score
    raise ValueError(
ValueError: Target scores need to be probabilities for multiclass roc_auc, i.e. they should sum up to 1.0 over classes

  warnings.warn(

2024-03-02 14:11:43,304:WARNING:c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\sklearn\metrics\_classification.py:1561: UserWarning: Note that pos_label (set to 'Très souple') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
`

PyCaret required dependencies:
pycaret: 3.3.0
IPython: 8.22.1
ipywidgets: 8.1.2
tqdm: 4.66.2
numpy: 1.26.4
pandas: 2.1.4
jinja2: 3.1.3
scipy: 1.11.4
joblib: 1.3.2
sklearn: 1.4.1.post1

**Closed** 2024-03-04 05:00 UTC
