### ISSUE TITLE
Using NLP model on unseen data seems awkward

### ISSUE THREAD

**Issue by mbeddo-crmz** [pycaret/pycaret#1922] opened 2021-12-05 02:21 UTC
For the NLP module, the assign_model() function is not useful for unseen document data. Maybe add arguments to handle new documents: assign_model(model, **newdata=NULL**, verbose=False)? If newdata is NULL then behavior is unchanged. If newdata is not null, then steps 1-8 from setup() are performed to preprocess the document(s) and step 9 is modified to use the is2word dictionary from the trained model (and not the one from the new data that step 9 would normally create). 

Essentially, factor out the code for steps 1-9 from setup() so both setup() and assign_model() can perform the same steps (except how id2word dictionary is built/used).

For now, this seems to work for me:

```
def assign_model_2(model, data, **kwargs):
    """
    We borrow parts of the pycaret source for applying a trained model on unseen data.
    Pass in a trained model, the new data, and the column containing the text for 
    pre-processing steps 1 - 8. We'll use the id2word dictionary that was used when
    training the model to override the corpus and id2word that step 9 produces so 
    mapping the unseen data to BOW corpus is consistent with when we first trained the model.
    """
  
    # Run setup again for unseen data. This pre-processes the text for us.
    text, unseen = setup(data = data, **kwargs)[0:2]

    """
    This code comes from "step 9" of setup() - we only need the bit that will rebuild
    the corpus data structure for the new data USING the id2word dictionary from the 
    trained model.
    """
    # Retrieve the dictionary mapping for the corpus that was trained with
    # so we can use it with the new unseen data.
    id2word = model.id2word

    corpus = []
    for i in text:
        d = id2word.doc2bow(i)
        corpus.append(d)

    """
    This code comes from assign_model()
    """
    # Get the topics and their probabilities
    c = saved_lda.get_document_topics(corpus, minimum_probability=0)

    # Construct a dataframe to return
    ls = []
    for i in range(len(c)):
        ls.append(c[i])
    bb = []
    for i in ls:
        bs = []
        for k in i:
            bs.append(k[1])
        bb.append(bs)

    Dominant_Topic = []
    for i in bb:
        max_ = max(i)
        max_ = i.index(max_)
        Dominant_Topic.append("Topic " + str(max_))

    pdt = []
    for i in range(0, len(bb)):
        l = max(bb[i]) / sum(bb[i])
        pdt.append(round(l, 2))

    col_names = []
    for i in range(len(saved_lda.show_topics(num_topics=999999))):
        a = "Topic_" + str(i)
        col_names.append(a)

    bb = pd.DataFrame(bb, columns=col_names)
    bb_ = pd.concat([unseen, bb], axis=1)

    dt_ = pd.DataFrame(Dominant_Topic, columns=["Dominant_Topic"])
    bb_ = pd.concat([bb_, dt_], axis=1)

    pdt_ = pd.DataFrame(pdt, columns=["Perc_Dominant_Topic"])
    bb_ = pd.concat([bb_, pdt_], axis=1)

    return bb_
```

**Comment by moezali1** [comment] 2021-12-05 19:01
@mbeddo-crmz I agree with you. To be honest, `pycaret.nlp` module was never a focus and I couldn't build a function like `predict_model` that can be used to pass next through the entire pipeline and generate inference. Hence it is not so much useful to create topic models in PyCaret since `predit_model` function is missing. 

Will you be interested in creating this new function `predict_model` in the `pycaret.nlp` module?

You can checkout how `predict_model` is working in any other module of PyCaret like `pycaret.classification` or `pycaret.regression`. 

Thanks!

**Comment by mbeddo-crmz** [comment] 2021-12-06 05:34
I would be interested in helping out. I'll take a look at the predict_model function from other modules and learn how it works.

**Comment by moezali1** [comment] 2021-12-10 18:52
Thanks. Feel free to reach out to me or @Yard1 as you need any help! Also, join us on [Slack](https://join.slack.com/t/pycaret/shared_invite/zt-row9phbm-BoJdEVPYnGf7_NxNBP307w).

**Comment by joelmsherman** [comment] 2023-01-01 23:46
> I would be interested in helping out. I'll take a look at the predict_model function from other modules and learn how it works.

Hi @mbeddo-crmz, any update on this augmentation?  I'd be interested in having a predict_model function for pycaret.nlp as well!

**Comment by mbeddo-crmz** [comment] 2023-01-02 00:11
﻿
I lost interest in the project when one of the maintainers (sorry, can’t recall who but I could search) mentioned there was discussion of dropping the NLP component from PyCaret, so I dropped the idea.

Best,

Mike

On Jan 1, 2023, at 4:46 PM, Joel Sherman ***@***.***> wrote:

﻿

I would be interested in helping out. I'll take a look at the predict_model function from other modules and learn how it works.

Hi @mbeddo-crmz<https://github.com/mbeddo-crmz>, any update on this augmentation? I'd be interested in having a predict_model function for pycaret.nlp as well!

**Comment by moezali1** [comment] 2023-03-18 13:05
We are no more supporting the `nlp` and `arules` module in PyCaret due to lack to resources. Closing the issue now.

**Closed by moezali1** 2023-03-18 13:05 UTC
Labels: enhancement, nlp
