### ISSUE TITLE
[BUG]: IDE Displaying problem

### ISSUE THREAD

**Issue by turkalpmd** [pycaret/pycaret#3466] opened 2023-04-07 22:58 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

I am currently running Pycaret in VSCode and PyCharm with all Jupyter extensions installed. However, I am facing an issue where the markdown table is not displaying properly. Instead of showing the table, it only displays the object name.

I have tried to configure the jupyter kernel to show the markdown table properly, but I still couldn't solve the issue.

### Reproducible Example

```python
from pycaret.datasets import get_data
juice = get_data('juice')
from pycaret.classification import *
exp_name = setup(data = juice,  target = 'Purchase')
```

### Expected Behavior

![Screenshot from 2023-04-08 01-53-03](https://user-images.githubusercontent.com/85236337/230689661-05c52a76-3e8f-4d6e-8b6a-86b1f403418a.png)

### Actual Results

```python-traceback
Empty
```

### Installed Versions

<details>
'3.0.0.rc9'
I try also with
'3.0.0'
</details>

**Comment by coconutattitude** [comment] 2023-04-12 16:17
I have the same issue.

**Comment by ngupta23** [comment] 2023-04-15 12:14
@Yard1 I am having the same issues in VSCode Jupyter notebook

![image](https://user-images.githubusercontent.com/33585645/232222663-24ab2cd5-f45c-468a-8f0a-79adfd133aa8.png)

**Comment by Yard1** [comment] 2023-04-16 16:50
I can reproduce. This seems to be related - https://github.com/ipython/ipython/issues/13983

**Comment by Yard1** [comment] 2023-04-16 17:09
https://github.com/microsoft/vscode-jupyter/issues/13105 seems to point to this being an issue with VSCode. Unsure about PyCharm

**Comment by Yard1** [comment] 2023-04-16 17:26
This is a VSCode bug and needs to be fixed there. I have posted in the issue I linked above.

**Comment by ngupta23** [comment] 2023-04-18 01:49
@Yard1  Should we close this if there is nothing to be done from pycaret side?

**Closed** 2023-04-21 20:34 UTC
Labels: bug, vscode, pycharm
