### ISSUE TITLE
[INSTALL]: 

### ISSUE THREAD

**Issue by psxpa3** [pycaret/pycaret#2716] opened 2022-07-05 23:47 UTC
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

macOS-10.16-x86_64-i386-64bit

### Installation Method

conda install

### pycaret Version

3.0.0

### Python Version

3.8.13

### Description

Hello, I am trying to use TimeSeries module. Got to know that {`pip install pycaret-ts-alpha`} has to be used. While trying to {`from pycaret.time_series import TSForecastingExperiment`}, I get `ImportError: cannot import name {'_check_param_grid' from 'sklearn.model_selection._search'}. I read this stack-overflow post  - https://stackoverflow.com/questions/72228607/pycaret-time-series-tsforecastingexperiment-importerror-cannot-import-name-ch. Followed, and reduced the sklearn package to {1.0.2}, but still getting the same error. This notebook states that everything goes well {https://gist.github.com/ngupta23/1dedff5bd94017f5e931614fcdb60187#file-ts-alpha-installed-ipynb}, but not in my case. 

My conda list:-
(conda_time_env) prpraror@prpraror-mac forecasting % conda list
# packages in environment at /Users/prpraror/opt/miniconda3/envs/conda_time_env:
#
# Name                    Version                   Build  Channel
appnope                   0.1.3                    pypi_0    pypi
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py38hca72f7f_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
attrs                     21.4.0             pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
beautifulsoup4            4.11.1           py38hecd8cb5_0  
bleach                    4.1.0              pyhd3eb1b0_0  
ca-certificates           2022.4.26            hecd8cb5_0  
category-encoders         2.5.0                    pypi_0    pypi
certifi                   2022.6.15        py38hecd8cb5_0  
cffi                      1.15.0           py38hc55c11b_1  
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.30                  pypi_0    pypi
dbus                      1.13.18              h18a8e69_0  
debugpy                   1.5.1            py38he9d5cce_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
deprecated                1.2.13                   pypi_0    pypi
entrypoints               0.4              py38hecd8cb5_0  
executing                 0.8.3              pyhd3eb1b0_0  
expat                     2.4.4                he9d5cce_0  
fonttools                 4.33.3                   pypi_0    pypi
gettext                   0.21.0               h7535e17_0  
glib                      2.69.1               h8346a28_1  
icu                       58.2                 h0a44026_3  
imbalanced-learn          0.9.1                    pypi_0    pypi
importlib_resources       5.2.0              pyhd3eb1b0_1  
ipykernel                 6.9.1            py38hecd8cb5_0  
ipython                   8.4.0                    pypi_0    pypi
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.5              pyhd3eb1b0_1  
jedi                      0.18.1           py38hecd8cb5_1  
jinja2                    3.0.3              pyhd3eb1b0_0  
joblib                    1.0.1                    pypi_0    pypi
jpeg                      9e                   hca72f7f_0  
jsonschema                4.4.0            py38hecd8cb5_0  
jupyter                   1.0.0                    py38_7  
jupyter_client            7.2.2            py38hecd8cb5_0  
jupyter_console           6.4.3              pyhd3eb1b0_0  
jupyter_core              4.10.0           py38hecd8cb5_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
kaleido                   0.2.1                    pypi_0    pypi
kiwisolver                1.4.3                    pypi_0    pypi
libcxx                    12.0.0               h2f01273_0  
libffi                    3.3                  hb1e8313_2  
libiconv                  1.16                 hca72f7f_2  
libpng                    1.6.37               ha441bb4_0  
libsodium                 1.0.18               h1de35cc_0  
libxml2                   2.9.14               hbf8cd5e_0  
lightgbm                  3.3.2                    pypi_0    pypi
llvm-openmp               12.0.0               h0dcd299_1  
llvmlite                  0.38.1                   pypi_0    pypi
markupsafe                2.1.1            py38hca72f7f_0  
matplotlib                3.5.2                    pypi_0    pypi
matplotlib-inline         0.1.3                    pypi_0    pypi
mistune                   0.8.4           py38h1de35cc_1001  
nbclient                  0.5.13           py38hecd8cb5_0  
nbconvert                 6.4.4            py38hecd8cb5_0  
nbformat                  5.3.0            py38hecd8cb5_0  
ncurses                   6.3                  hca72f7f_3  
nest-asyncio              1.5.5            py38hecd8cb5_0  
notebook                  6.4.11           py38hecd8cb5_0  
numba                     0.55.2                   pypi_0    pypi
numpy                     1.21.6                   pypi_0    pypi
openssl                   1.1.1p               hca72f7f_0  
packaging                 21.3               pyhd3eb1b0_0  
pandas                    1.4.3                    pypi_0    pypi
pandocfilters             1.5.0              pyhd3eb1b0_0  
parso                     0.8.3              pyhd3eb1b0_0  
patsy                     0.5.2                    pypi_0    pypi
pcre                      8.45                 h23ab428_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.2.0                    pypi_0    pypi
pip                       21.2.4           py38hecd8cb5_0  
plotly                    5.9.0                    pypi_0    pypi
pmdarima                  1.8.5                    pypi_0    pypi
prometheus_client         0.13.1             pyhd3eb1b0_0  
prompt-toolkit            3.0.30                   pypi_0    pypi
prompt_toolkit            3.0.20               hd3eb1b0_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
pycaret-ts-alpha          3.0.0.dev1649017462          pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pygments                  2.12.0                   pypi_0    pypi
pyod                      1.0.3                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyqt                      5.9.2            py38h655552a_2  
pyrsistent                0.18.0           py38hca72f7f_0  
python                    3.8.13               hdfd78df_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.15.1             pyhd3eb1b0_0  
pytz                      2022.1                   pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.3.0           py38he9d5cce_2  
qt                        5.9.7                h468cd18_1  
qtconsole                 5.3.0              pyhd3eb1b0_0  
qtpy                      2.0.1              pyhd3eb1b0_0  
readline                  8.1.2                hca72f7f_1  
scikit-learn              1.0.2                    pypi_0    pypi
scikit-plot               0.3.7                    pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
send2trash                1.8.0              pyhd3eb1b0_1  
setuptools                61.2.0           py38hecd8cb5_0  
sip                       4.19.8           py38h0a44026_0  
six                       1.16.0             pyhd3eb1b0_1  
sktime                    0.10.1                   pypi_0    pypi
soupsieve                 2.3.1              pyhd3eb1b0_0  
sqlite                    3.38.5               h707629a_0  
stack-data                0.3.0                    pypi_0    pypi
stack_data                0.2.0              pyhd3eb1b0_0  
statsmodels               0.13.2                   pypi_0    pypi
tbats                     1.1.0                    pypi_0    pypi
tenacity                  8.0.1                    pypi_0    pypi
terminado                 0.13.1           py38hecd8cb5_0  
testpath                  0.6.0            py38hecd8cb5_0  
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h5d9f67b_0  
tornado                   6.1              py38h9ed2024_0  
traitlets                 5.3.0                    pypi_0    pypi
typing-extensions         4.1.1                hd3eb1b0_0  
typing_extensions         4.1.1              pyh06a4308_0  
urllib3                   1.26.9                   pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1                    py38_1  
wheel                     0.37.1             pyhd3eb1b0_0  
widgetsnbextension        3.5.2            py38hecd8cb5_0  
wrapt                     1.14.1                   pypi_0    pypi
xz                        5.2.5                hca72f7f_1  
yellowbrick               1.4                      pypi_0    pypi
zeromq                    4.3.4                h23ab428_0  
zipp                      3.8.0            py38hecd8cb5_0  
zlib                      1.2.12               h4dc903c_2  
(conda_time_env) prpraror@prpraror-mac forecasting % 

Any help would be appreaciated. Thank you for developing this library.

### Installation Logs

<details>

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [25], in <cell line: 2>()
      1 # from pycaret.time_series.forecasting.oop import TSForecastingExperiment
----> 2 from pycaret.time_series import TSForecastingExperiment

File ~/opt/miniconda3/envs/conda_time_env/lib/python3.8/site-packages/pycaret/time_series/__init__.py:1, in <module>
----> 1 from pycaret.time_series.forecasting.oop import TSForecastingExperiment
      2 from pycaret.time_series.forecasting.functional import (
      3     setup,
      4     create_model,
   (...)
     25     check_stats,
     26 )
     28 __all__ = [
     29     "TSForecastingExperiment",
     30     "setup",
   (...)
     52     "check_stats",
     53 ]

File ~/opt/miniconda3/envs/conda_time_env/lib/python3.8/site-packages/pycaret/time_series/forecasting/oop.py:16, in <module>
     14 from sklearn.base import clone
     15 from sktime.forecasting.base import ForecastingHorizon
---> 16 from sktime.forecasting.model_selection import (
     17     temporal_train_test_split,
     18     ExpandingWindowSplitter,
     19     SlidingWindowSplitter,
     20 )
     22 from sktime.forecasting.base import BaseForecaster
     24 # from sktime.forecasting.compose import ForecastingPipeline

File ~/opt/miniconda3/envs/conda_time_env/lib/python3.8/site-packages/sktime/forecasting/model_selection/__init__.py:22, in <module>
     20 from sktime.forecasting.model_selection._split import SlidingWindowSplitter
     21 from sktime.forecasting.model_selection._split import temporal_train_test_split
---> 22 from sktime.forecasting.model_selection._tune import ForecastingGridSearchCV
     23 from sktime.forecasting.model_selection._tune import ForecastingRandomizedSearchCV

File ~/opt/miniconda3/envs/conda_time_env/lib/python3.8/site-packages/sktime/forecasting/model_selection/_tune.py:13, in <module>
     11 from sklearn.base import clone
     12 from sklearn.model_selection import ParameterGrid, ParameterSampler, check_cv
---> 13 from sklearn.model_selection._search import _check_param_grid
     14 from sklearn.utils.metaestimators import if_delegate_has_method
     16 from sktime.exceptions import NotFittedError

ImportError: cannot import name '_check_param_grid' from 'sklearn.model_selection._search' (/Users/prpraror/opt/miniconda3/envs/conda_time_env/lib/python3.8/site-packages/sklearn/model_selection/_search.py)

</details>

**Comment by ngupta23** [comment] 2022-07-10 07:28
@psxpa3 Is this a duplicate of https://github.com/pycaret/pycaret/issues/2720?

**Comment by ngupta23** [comment] 2022-07-18 18:16
Closing since this is a duplicate. Feel free to reopen if it is not.

**Closed by ngupta23** 2022-07-18 18:16 UTC
Labels: installation
