### ISSUE TITLE
Anomaly Detection Methods

### ISSUE THREAD

**Issue by linhy1993** [pycaret/pycaret#826] opened 2020-11-10 18:34 UTC
Hi there, I have a question about anomaly detection.

Is it only supporting "pca" as "outlier_methods" now? Because I find that class Outlier could send different methods including pca, knn and iso, but now is hard coded with pca, and there is not any method parameter could be used when I call setup().

Is there any way to use different methods for outlier detection now? 

Thanks in advance.

**Comment by pycaret** [comment] 2021-01-16 15:38
@linhy1993 At this moment, the `remove_outlier` parameter in the `setup`  for `pycaret.classification` and `pycaret.regression` only supports `pca`. In future, we may allow an additional parameter in the `setup` for the user to choose the method.

**Comment by ngupta23** [comment] 2021-05-13 13:48
Lets leave this open since it is marked as an enhancement.

**Closed** 2021-05-21 02:37 UTC
Labels: anomaly_detection, classification, enhancement, no-issue-activity, preprocessing, regression
