### ISSUE TITLE
Discrepancies in ROC Values in Classifier Module: Identifying Possible Errors

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#3514] opened 2023-04-26 21:53 UTC
### Discussed in https://github.com/pycaret/pycaret/discussions/3513

<div type='discussions-op-text'>

<sup>Originally posted by **turkalpmd** April 26, 2023</sup>
In the Classifier module, ROC values are coming out strange. Firstly, the ROC values obtained with the predict function and those obtained in the plot function are different. By default, the train data is not used in the plot_model function. Later, I calculated the roc auc score in scikit-learn using the results obtained with the predict_model function, which also turns out to be different. Where could my mistake be?

Here is the example;

plot_model:
AUC: 92
code: `plot_model(tuned_xgb, plot = 'auc')`
![image](https://user-images.githubusercontent.com/85236337/234708202-a467799a-6cb6-4db4-9026-b421b63fbd8e.png)

predict_model:
AUC : 83	
code: `predict_model(tuned_xgb,test)`

scikit_leran score is:
AUC: 80
code; `roc_auc = roc_auc_score(y_true, y_pred)`

### **I am quite surprised by this situation, how can I report it with confidence?**</div>

**Comment by ngupta23** [comment] 2023-04-26 21:54
Let's track it here: https://github.com/pycaret/pycaret/issues/3514

**Comment by moezali1** [comment] 2023-05-05 20:36
Even though I cannot reproduce AUC mismatch between `plot_model` and `predict_model`. I have tested on `juice` and `blood` dataset and the recall and precision numbers in the `predict_model` is returned as 0.0 which is wrong.

**Comment by moezali1** [comment] 2023-05-12 14:58
The issue has been fixed on `master`.

**Closed by moezali1** 2023-05-12 14:58 UTC
Labels: classification, plot_model

**Comment by ngupta23** [comment] 2023-05-15 00:24
Released as pycaret 3.0.1
