### ISSUE TITLE
[BUG]: Input contains NaN, infinity or a value too large for dtype('float32').

### ISSUE THREAD

**Issue by SSMK-wq** [pycaret/pycaret#3069] opened 2022-11-06 07:56 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

I am trying to run a regression to predict a continuous variable output which has values > 0

But as reported in earlier issue [here](https://github.com/pycaret/pycaret/issues/290), the error appears

When I turn off Transform_target, it works fine. But in my case, the error happens for linear regression and few more tree based models

### Reproducible Example

```python
compare_models(errors="raise")
```

### Expected Behavior

All regression models in pycaret should run when we run "Compare_models".

### Actual Results

```python-traceback
Model	MAE	MSE	RMSE	R2	RMSLE	MAPE	TT (Sec)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [61], in <cell line: 1>()
----> 1 compare_models(errors="raise")

File ~\AppData\Roaming\Python\Python38\site-packages\pycaret\regression.py:812, in compare_models(include, exclude, fold, round, cross_validation, sort, n_select, budget_time, turbo, errors, fit_kwargs, groups, experiment_custom_tags, verbose, display, parallel)
    809     del params["parallel"]
    810     return parallel.compare_models(compare_models, params)
--> 812 return pycaret.internal.tabular.compare_models(
    813     include=include,
    814     exclude=exclude,
    815     fold=fold,
    816     round=round,
    817     cross_validation=cross_validation,
    818     sort=sort,
    819     n_select=n_select,
    820     budget_time=budget_time,
    821     turbo=turbo,
    822     errors=errors,
    823     fit_kwargs=fit_kwargs,
    824     groups=groups,
    825     experiment_custom_tags=experiment_custom_tags,
    826     verbose=verbose,
    827     display=display,
    828 )

File ~\AppData\Roaming\Python\Python38\site-packages\pycaret\internal\tabular.py:2199, in compare_models(include, exclude, fold, round, cross_validation, sort, n_select, budget_time, turbo, errors, fit_kwargs, groups, experiment_custom_tags, probability_threshold, verbose, display)
   2184 create_model_args = dict(
   2185     estimator=model,
   2186     system=False,
   (...)
   2196     refit=False,
   2197 )
   2198 if errors == "raise":
-> 2199     model, model_fit_time = create_model_supervised(**create_model_args)
   2200     model_results = pull(pop=True)
   2201 else:

File ~\AppData\Roaming\Python\Python38\site-packages\pycaret\internal\tabular.py:3200, in create_model_supervised(estimator, fold, round, cross_validation, predict, fit_kwargs, groups, refit, verbose, system, X_train_data, y_train_data, metrics, experiment_custom_tags, add_to_model_list, probability_threshold, display, return_train_score, **kwargs)
   3197 logger.info(f"Cross validating with {cv}, n_jobs={n_jobs}")
   3199 model_fit_start = time.time()
-> 3200 scores = cross_validate(
   3201     pipeline_with_model,
   3202     data_X,
   3203     data_y,
   3204     cv=cv,
   3205     groups=groups,
   3206     scoring=metrics_dict,
   3207     fit_params=fit_kwargs,
   3208     n_jobs=n_jobs,
   3209     return_train_score=return_train_score,
   3210     error_score=0,
   3211 )
   3212 model_fit_end = time.time()
   3213 model_fit_time = np.array(model_fit_end - model_fit_start).round(2)

File ~\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\validation.py:72, in _deprecate_positional_args.<locals>.inner_f(*args, **kwargs)
     67     warnings.warn("Pass {} as keyword args. From version 0.25 "
     68                   "passing these as positional arguments will "
     69                   "result in an error".format(", ".join(args_msg)),
     70                   FutureWarning)
     71 kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 72 return f(**kwargs)

File ~\AppData\Roaming\Python\Python38\site-packages\sklearn\model_selection\_validation.py:242, in cross_validate(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, return_train_score, return_estimator, error_score)
    238 # We clone the estimator to make sure that all the folds are
    239 # independent, and that it is pickle-able.
    240 parallel = Parallel(n_jobs=n_jobs, verbose=verbose,
    241                     pre_dispatch=pre_dispatch)
--> 242 scores = parallel(
    243     delayed(_fit_and_score)(
    244         clone(estimator), X, y, scorers, train, test, verbose, None,
    245         fit_params, return_train_score=return_train_score,
    246         return_times=True, return_estimator=return_estimator,
    247         error_score=error_score)
    248     for train, test in cv.split(X, y, groups))
    250 zipped_scores = list(zip(*scores))
    251 if return_train_score:

File ~\Anaconda3\lib\site-packages\joblib\parallel.py:1056, in Parallel.__call__(self, iterable)
   1053     self._iterating = False
   1055 with self._backend.retrieval_context():
-> 1056     self.retrieve()
   1057 # Make sure that we get a last message telling us we are done
   1058 elapsed_time = time.time() - self._start_time

File ~\Anaconda3\lib\site-packages\joblib\parallel.py:935, in Parallel.retrieve(self)
    933 try:
    934     if getattr(self._backend, 'supports_timeout', False):
--> 935         self._output.extend(job.get(timeout=self.timeout))
    936     else:
    937         self._output.extend(job.get())

File ~\Anaconda3\lib\site-packages\joblib\_parallel_backends.py:542, in LokyBackend.wrap_future_result(future, timeout)
    539 """Wrapper for Future.result to implement the same behaviour as
    540 AsyncResults.get from multiprocessing."""
    541 try:
--> 542     return future.result(timeout=timeout)
    543 except CfTimeoutError as e:
    544     raise TimeoutError from e

File ~\Anaconda3\lib\concurrent\futures\_base.py:444, in Future.result(self, timeout)
    442     raise CancelledError()
    443 elif self._state == FINISHED:
--> 444     return self.__get_result()
    445 else:
    446     raise TimeoutError()

File ~\Anaconda3\lib\concurrent\futures\_base.py:389, in Future.__get_result(self)
    387 if self._exception:
    388     try:
--> 389         raise self._exception
    390     finally:
    391         # Break a reference cycle with the exception in self._exception
    392         self = None

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

```

### Installed Versions

<details>
2.3.10
</details>

**Comment by tvdboom** [comment] 2022-11-06 10:30
Please, retry this using the latest version of pycaret `pip install --pre pycaret` and post a reproducible example (with data and code)

**Comment by ngupta23** [comment] 2022-12-03 21:22
Closing due to missing information. Feel free to provide the information and reopen. Thanks!

**Closed by ngupta23** 2022-12-03 21:22 UTC
Labels: bug, missing_info
