### ISSUE TITLE
[BUG]: Error when feature_selection is set to True on setup

### ISSUE THREAD

**Issue by eljirg** [pycaret/pycaret#3415] opened 2023-03-20 07:30 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

I am using dry bean dataset from https://archive.ics.uci.edu/ml/datasets/dry+bean+dataset with pycaret 3.0.0

However when trying to create setup this error occurs
![image](https://user-images.githubusercontent.com/29477795/226270445-781669a1-e773-4966-a82d-64e95ac799a0.png)

I tested on the feature_selection_method and this issue occur only when feature_selection_method is set to 'classic'

Any idea what might be the cause?

### Reproducible Example

```python
s = setup(data=df, 
          target='Class', 
          feature_selection = True,
          feature_selection_method = 'classic')
```

### Expected Behavior

-

### Actual Results

```python-traceback
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~\Anaconda3\envs\freight\lib\site-packages\pandas\core\indexes\base.py:3803, in Index.get_loc(self, key, method, tolerance)
   3802 try:
-> 3803     return self._engine.get_loc(casted_key)
   3804 except KeyError as err:

File ~\Anaconda3\envs\freight\lib\site-packages\pandas\_libs\index.pyx:138, in pandas._libs.index.IndexEngine.get_loc()

File ~\Anaconda3\envs\freight\lib\site-packages\pandas\_libs\index.pyx:165, in pandas._libs.index.IndexEngine.get_loc()

File pandas\_libs\hashtable_class_helper.pxi:5745, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas\_libs\hashtable_class_helper.pxi:5753, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 0

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In [10], line 1
----> 1 s = setup(data=df, 
      2           target='Class', 
      3           feature_selection = True,
      4           feature_selection_method = 'classic')

File ~\Anaconda3\envs\freight\lib\site-packages\pycaret\classification\functional.py:603, in setup(data, data_func, target, index, train_size, test_data, ordinal_features, numeric_features, categorical_features, date_features, text_features, ignore_features, keep_features, preprocess, create_date_columns, imputation_type, numeric_imputation, categorical_imputation, iterative_imputation_iters, numeric_iterative_imputer, categorical_iterative_imputer, text_features_method, max_encoding_ohe, encoding_method, rare_to_value, rare_value, polynomial_features, polynomial_degree, low_variance_threshold, group_features, group_names, drop_groups, remove_multicollinearity, multicollinearity_threshold, bin_numeric_features, remove_outliers, outliers_method, outliers_threshold, fix_imbalance, fix_imbalance_method, transformation, transformation_method, normalize, normalize_method, pca, pca_method, pca_components, feature_selection, feature_selection_method, feature_selection_estimator, n_features_to_select, custom_pipeline, custom_pipeline_position, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, html, session_id, system_log, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, verbose, memory, profile, profile_kwargs)
    601 exp = _EXPERIMENT_CLASS()
    602 set_current_experiment(exp)
--> 603 return exp.setup(
    604     data=data,
    605     data_func=data_func,
    606     target=target,
    607     index=index,
    608     train_size=train_size,
    609     test_data=test_data,
    610     ordinal_features=ordinal_features,
    611     numeric_features=numeric_features,
    612     categorical_features=categorical_features,
    613     date_features=date_features,
    614     text_features=text_features,
    615     ignore_features=ignore_features,
    616     keep_features=keep_features,
    617     preprocess=preprocess,
    618     create_date_columns=create_date_columns,
    619     imputation_type=imputation_type,
    620     numeric_imputation=numeric_imputation,
    621     categorical_imputation=categorical_imputation,
    622     iterative_imputation_iters=iterative_imputation_iters,
    623     numeric_iterative_imputer=numeric_iterative_imputer,
    624     categorical_iterative_imputer=categorical_iterative_imputer,
    625     text_features_method=text_features_method,
    626     max_encoding_ohe=max_encoding_ohe,
    627     encoding_method=encoding_method,
    628     rare_to_value=rare_to_value,
    629     rare_value=rare_value,
    630     polynomial_features=polynomial_features,
    631     polynomial_degree=polynomial_degree,
    632     low_variance_threshold=low_variance_threshold,
    633     group_features=group_features,
    634     group_names=group_names,
    635     drop_groups=drop_groups,
    636     remove_multicollinearity=remove_multicollinearity,
    637     multicollinearity_threshold=multicollinearity_threshold,
    638     bin_numeric_features=bin_numeric_features,
    639     remove_outliers=remove_outliers,
    640     outliers_method=outliers_method,
    641     outliers_threshold=outliers_threshold,
    642     fix_imbalance=fix_imbalance,
    643     fix_imbalance_method=fix_imbalance_method,
    644     transformation=transformation,
    645     transformation_method=transformation_method,
    646     normalize=normalize,
    647     normalize_method=normalize_method,
    648     pca=pca,
    649     pca_method=pca_method,
    650     pca_components=pca_components,
    651     feature_selection=feature_selection,
    652     feature_selection_method=feature_selection_method,
    653     feature_selection_estimator=feature_selection_estimator,
    654     n_features_to_select=n_features_to_select,
    655     custom_pipeline=custom_pipeline,
    656     custom_pipeline_position=custom_pipeline_position,
    657     data_split_shuffle=data_split_shuffle,
    658     data_split_stratify=data_split_stratify,
    659     fold_strategy=fold_strategy,
    660     fold=fold,
    661     fold_shuffle=fold_shuffle,
    662     fold_groups=fold_groups,
    663     n_jobs=n_jobs,
    664     use_gpu=use_gpu,
    665     html=html,
    666     session_id=session_id,
    667     system_log=system_log,
    668     log_experiment=log_experiment,
    669     experiment_name=experiment_name,
    670     experiment_custom_tags=experiment_custom_tags,
    671     log_plots=log_plots,
    672     log_profile=log_profile,
    673     log_data=log_data,
    674     verbose=verbose,
    675     memory=memory,
    676     profile=profile,
    677     profile_kwargs=profile_kwargs,
    678 )

File ~\Anaconda3\envs\freight\lib\site-packages\pycaret\classification\oop.py:901, in ClassificationExperiment.setup(self, data, data_func, target, index, train_size, test_data, ordinal_features, numeric_features, categorical_features, date_features, text_features, ignore_features, keep_features, preprocess, create_date_columns, imputation_type, numeric_imputation, categorical_imputation, iterative_imputation_iters, numeric_iterative_imputer, categorical_iterative_imputer, text_features_method, max_encoding_ohe, encoding_method, rare_to_value, rare_value, polynomial_features, polynomial_degree, low_variance_threshold, group_features, group_names, drop_groups, remove_multicollinearity, multicollinearity_threshold, bin_numeric_features, remove_outliers, outliers_method, outliers_threshold, fix_imbalance, fix_imbalance_method, transformation, transformation_method, normalize, normalize_method, pca, pca_method, pca_components, feature_selection, feature_selection_method, feature_selection_estimator, n_features_to_select, custom_pipeline, custom_pipeline_position, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, html, session_id, system_log, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, engine, verbose, memory, profile, profile_kwargs)
    898 if ("placeholder", None) in self.pipeline.steps and len(self.pipeline) > 1:
    899     self.pipeline.steps.remove(("placeholder", None))
--> 901 self.pipeline.fit(self.X_train, self.y_train)
    903 self.logger.info("Finished creating preprocessing pipeline.")
    904 self.logger.info(f"Pipeline: {self.pipeline}")

File ~\Anaconda3\envs\freight\lib\site-packages\pycaret\internal\pipeline.py:260, in Pipeline.fit(self, X, y, **fit_params)
    258 if self._final_estimator != "passthrough":
    259     fit_params_last_step = fit_params_steps[self.steps[-1][0]]
--> 260     fitted_estimator = self._memory_fit(
    261         clone(self.steps[-1][1]), X, y, **fit_params_last_step
    262     )
    263     # Hacky way to make sure that the state of the estimator
    264     # loaded from cache is carried over to the estimator
    265     # in steps
    266     _copy_estimator_state(fitted_estimator, self.steps[-1][1])

File ~\Anaconda3\envs\freight\lib\site-packages\joblib\memory.py:594, in MemorizedFunc.__call__(self, *args, **kwargs)
    593 def __call__(self, *args, **kwargs):
--> 594     return self._cached_call(args, kwargs)[0]

File ~\Anaconda3\envs\freight\lib\site-packages\pycaret\internal\memory.py:398, in FastMemorizedFunc._cached_call(self, args, kwargs, shelving)
    395 if must_call:
    396     # PYCARET CHANGES
    397     self._cached_output_identifiers = func_id, args_id
--> 398     out, metadata = self.call(*args, **kwargs)
    399     if self.mmap_mode is not None and metadata is not None:
    400         # PYCARET CHANGES END
    401         # Memmap the output at the first call to be consistent with
    402         # later calls
    403         if self._verbose:

File ~\Anaconda3\envs\freight\lib\site-packages\pycaret\internal\memory.py:309, in FastMemorizedFunc.call(self, *args, **kwargs)
    307 # PYCARET CHANGES
    308 func_start_time = time.monotonic()
--> 309 output = self.func(*args, **kwargs)
    310 func_duration = time.monotonic() - func_start_time
    311 if func_duration >= self.min_time_to_cache:

File ~\Anaconda3\envs\freight\lib\site-packages\pycaret\internal\pipeline.py:66, in _fit_one(transformer, X, y, message, **fit_params)
     64         if "y" in signature(transformer.fit).parameters:
     65             args.append(y)
---> 66         transformer.fit(*args, **fit_params)
     67 return transformer

File ~\Anaconda3\envs\freight\lib\site-packages\pycaret\internal\preprocess\transformers.py:219, in TransformerWrapper.fit(self, X, y, **fit_params)
    216 if "y" in transformer_params and y is not None:
    217     args.append(y)
--> 219 self.transformer.fit(*args, **fit_params)
    220 return self

File ~\Anaconda3\envs\freight\lib\site-packages\sklearn\feature_selection\_from_model.py:317, in SelectFromModel.fit(self, X, y, **fit_params)
    310 if self.max_features is not None:
    311     if isinstance(self.max_features, numbers.Integral):
    312         check_scalar(
    313             self.max_features,
    314             "max_features",
    315             numbers.Integral,
    316             min_val=0,
--> 317             max_val=len(X[0]),
    318         )
    319         self.max_features_ = self.max_features
    320     elif callable(self.max_features):

File ~\Anaconda3\envs\freight\lib\site-packages\pandas\core\frame.py:3805, in DataFrame.__getitem__(self, key)
   3803 if self.columns.nlevels > 1:
   3804     return self._getitem_multilevel(key)
-> 3805 indexer = self.columns.get_loc(key)
   3806 if is_integer(indexer):
   3807     indexer = [indexer]

File ~\Anaconda3\envs\freight\lib\site-packages\pandas\core\indexes\base.py:3805, in Index.get_loc(self, key, method, tolerance)
   3803     return self._engine.get_loc(casted_key)
   3804 except KeyError as err:
-> 3805     raise KeyError(key) from err
   3806 except TypeError:
   3807     # If we have a listlike key, _check_indexing_error will raise
   3808     #  InvalidIndexError. Otherwise we fall through and re-raise
   3809     #  the TypeError.
   3810     self._check_indexing_error(key)

KeyError: 0
```

### Installed Versions

<details>
System:
    python: 3.9.13 (main, Oct 13 2022, 21:23:06) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\01142280\Anaconda3\envs\freight\python.exe
   machine: Windows-10-10.0.19044-SP0

PyCaret required dependencies:
                 pip: 22.2.2
          setuptools: 63.4.1
             pycaret: 3.0.0
             IPython: 8.5.0
          ipywidgets: 7.7.2
                tqdm: 4.64.0
               numpy: 1.21.6
              pandas: 1.5.2
              jinja2: 3.0.3
               scipy: 1.7.3
              joblib: 1.2.0
             sklearn: 1.1.0
                pyod: 1.0.9
            imblearn: 0.10.1
   category_encoders: 2.6.0
            lightgbm: 3.3.5
               numba: 0.56.4
            requests: 2.28.1
          matplotlib: 3.5.0
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.11.0
             kaleido: 0.2.1
         statsmodels: 0.13.0
              sktime: 0.16.1
               tbats: 1.1.2
            pmdarima: 2.0.3
              psutil: 5.9.3

PyCaret optional dependencies:
                shap: 0.41.0
           interpret: Not installed
                umap: Not installed
    pandas_profiling: 4.1.1
  explainerdashboard: Not installed
             autoviz: Not installed
           fairlearn: Not installed
             xgboost: 1.7.2
            catboost: Not installed
              kmodes: Not installed
             mlxtend: Not installed
       statsforecast: Not installed
        tune_sklearn: Not installed
                 ray: Not installed
            hyperopt: Not installed
              optuna: 2.10.0
               skopt: 0.9.0
              mlflow: Not installed
              gradio: Not installed
             fastapi: Not installed
             uvicorn: Not installed
              m2cgen: Not installed
           evidently: Not installed
               fugue: Not installed
           streamlit: 1.16.0
             prophet: 1.1.1
</details>

**Comment by moezali1** [comment] 2023-03-21 12:59
@eljirg Which version of pycaret are you using?

**Comment by eljirg** [comment] 2023-03-27 03:48
@moezali1 I am using pycaret 3.0.0

**Comment by moezali1** [comment] 2023-08-18 19:24
@eljirg I tried to reproduce this bug with the beans dataset but couldn't. Maybe the issue is resolved in latest version. I am using 3.0.4. 

Here is the link to Colab for you to try: https://colab.research.google.com/drive/1eQWt9yNBkjNkogeTQ88lm2WZKCRcZXZS?usp=sharing

**Closed by moezali1** 2023-08-18 19:24 UTC
Labels: bug
