### ISSUE TITLE
Weird predictions when using own exogenous variable data

### ISSUE THREAD

**Issue by thommyeur** [pycaret/pycaret#3548] opened 2023-05-12 07:54 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Hi all,

I have created a time series model with Pycaret which uses exogenous variables to come to the correct prediction for the production quantities of the upcoming ten days. Every day the model is refreshed with the latest data from the datawarehouse and the model runs again.

To get the data for the exogenous variables we have two options:
- Providing the data ourself -> loading in data concerning the weather forecast and variables like weeknumber, year, yearweekday and the 7daysaverage (which uses previous predictions to get filled). 
- Let Pycaret predict the values for these exogenous variables, which often leads to incorrect values for these variables, leading to inaccurate predictions.

The problem I face is that when I use the predictions made by Pycaret for the exogenous variables the predictions regarding the production quantities make sense but are not accurate and when I provide the data myself the predictions regarding the production quantities does not make sense at all (negative production quantities, really high production quantities). 

As I use the SQL datawarehouse to make a direct connection the files that I provide are exports and the code is a little bit adjusted because of this but the problem remains. 

I will provide two notebooks, one containing the predictive model with my own exogenous data (where the error happens). And the other file will contain the predictive model with the exogenous variables predicted by Pycaret.

I have been struggling with this issue for some weeks and tried a lot of things but haven't been able to find the reason this issue arises. #

I will add the necessary Excel files to run the notebooks and provide the links to the notebooks as well:

# Input data needed for both notebooks:
[Input_dfbase.xlsx](https://github.com/pycaret/pycaret/files/11460639/Input_dfbase.xlsx)

# Exogenous datasets only necessary for the TS_own_exogenous
[APIData.xlsx](https://github.com/pycaret/pycaret/files/11460637/APIData.xlsx)
[df_7dayavg.xlsx](https://github.com/pycaret/pycaret/files/11460638/df_7dayavg.xlsx)
[YearWeekDayExInput.xlsx](https://github.com/pycaret/pycaret/files/11460640/YearWeekDayExInput.xlsx)

# Notebook with own exogenous variables
https://colab.research.google.com/drive/16dXhUlRZlmTBPU00afocIkbyeXagmlTJ?usp=sharing

# Notebook with predicted exogenous variables
https://colab.research.google.com/drive/1SvPW5snXVzE262UPsRaxWQR4hkOh1uhb?usp=sharing

I hope that I provided enough information. Otherwise please let me know.

### Reproducible Example

```python
Provided the code and necessary data up
```

### Expected Behavior

The expected behaviour that I desire is the output from the TS_pred_exogenous.ipynb file.

### Actual Results

```python-traceback
The output that I currently receive is the output from the TS_own_exogenous.ipynb file
```

### Installed Versions

<details>
System:
    python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
executable: c:\Users\Thoma\OneDrive - Erasmus University Rotterdam\Documents\BIM\Thesis\Python\venv\Scripts\python.exe
   machine: Windows-10-10.0.22621-SP0

PyCaret required dependencies:
                 pip: 23.0.1
          setuptools: 56.0.0
             pycaret: 3.0.0
             IPython: 8.11.0
          ipywidgets: 8.0.5
                tqdm: 4.64.1
               numpy: 1.23.5
              pandas: 1.5.3
              jinja2: 3.1.2
               scipy: 1.9.1
              joblib: 1.2.0
             sklearn: 1.2.2
                pyod: 1.0.9
            imblearn: 0.10.1
   category_encoders: 2.6.0
            lightgbm: 3.3.5
               numba: 0.56.4
            requests: 2.28.2
          matplotlib: 3.7.1
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.13.1
             kaleido: 0.2.1
         statsmodels: 0.13.5
              sktime: 0.16.1
               tbats: 1.1.2
            pmdarima: 2.0.3
              psutil: 5.9.4

PyCaret optional dependencies:
                shap: Not installed
           interpret: 0.3.2
                umap: Not installed
    pandas_profiling: Not installed
  explainerdashboard: Not installed
             autoviz: Not installed
           fairlearn: Not installed
             xgboost: 1.7.4
            catboost: Not installed
              kmodes: Not installed
             mlxtend: Not installed
       statsforecast: Not installed
        tune_sklearn: Not installed
                 ray: Not installed
            hyperopt: Not installed
              optuna: Not installed
               skopt: Not installed
              mlflow: Not installed
              gradio: Not installed
             fastapi: Not installed
             uvicorn: Not installed
              m2cgen: Not installed
           evidently: Not installed
               fugue: Not installed
           streamlit: Not installed
             prophet: Not installed
</details>

**Comment by ngupta23** [comment] 2023-05-13 13:16
First of all, thanks for providing the data and code to reproduce the problem. I saw a few issues with this while running it.

1. Since you are using a mix of statistical and regression models in `compare_models`, the features extracted from datetime such as week number, etc. should only be provided to the regression-based models. The statistical models already have a notion of time and can derive it automatically. 
2. In pycaret time series module, you do not have to provide features these datetime features (such as week number) since it has internal mechanisms to take care of that through deseasonalizing and detrending. It also takes into account prior lags appropriately for these regression models. 
3. You have a choice to manually provide these features as well. e.g. prior lagged values + other features that you create such as rolling mean values. For this, you would use the `fe_target_rr ` argument as shown below.

So to summarize, you are only going to give temp as an exogenous variable and let pycaret handle the internal feature engineering using appropriate arguments.

Once I made these changes, the results seemed more reasonable. Please have a look.

PS: I had to clean up the code to remove the unnecessary bits of code that were not needed. Kindly reduce your code to a minimal example needed to reproduce the problem the next time you post the issue. It will help the person who is debugging it for you. Thanks!



```python
# Importing libraries
import pandas as pd
from pycaret.time_series import TSForecastingExperiment
from sktime.transformations.series.summarize import WindowSummarizer


# Global Plot Settings
fig_kwargs = {"renderer": "notebook"}

# We want to forecast the next 10 days of data and we will use 10 fold cross-validation to test the models.
fh = 10
fold = 3

df_base = pd.read_excel(r"issues\3548\Input_dfbase.xlsx")

# Joining on itself to retrieve the last years production quantities
df_merged = df_base.merge(
    df_base,
    how="left",
    left_on=["JaarWeekDagVorigJaar"],
    right_on=["JaarWeekDag"],
    suffixes=("", "PY"),
)

# Retaining only the necessary columns
df_productie_per_dag = df_merged[
    [
        "JaarWeekDag",
        "JaarWeekDagVorigJaar",
        "TotaalProductie",
        "TotaalProductiePY",
        "ProductieM2",
        "ProductieM2PY",
        "Datum",
        "Jaar",
        "Maand",
        "WeekDag",
        "WeekNum",
        "KasTemperatuurEtmaal",
        "AVEtmaal",
        "PlantTemperatuurEtmaal",
        "BuitenTemperatuurEtmaal",
        "BuitenStralingssom",
        "BelichtingsUren",
        "DonkerTijd",
    ]
]

# Selecting only the rows with a date later than 1 January 2020
df_productie_per_dag["Datum"] = pd.to_datetime(df_productie_per_dag["Datum"])

df_productie_per_dag = df_productie_per_dag[
    df_productie_per_dag["Datum"] > "2020-01-01"
]

# Sort the dataset by datum column in ascending order (already done in query but just to be sure)
df_productie_per_dag = df_productie_per_dag.sort_values("Datum")

# Loop through the sorted dataset and insert missing rows - For every year, the 1st of January is not evident in the data
for i in range(len(df_productie_per_dag) - 1):
    if (
        df_productie_per_dag.iloc[i + 1]["Datum"]
        - df_productie_per_dag.iloc[i]["Datum"]
    ).days > 1:
        new_date = df_productie_per_dag.iloc[i]["Datum"] + pd.DateOffset(days=1)
        new_row = df_productie_per_dag.iloc[i].copy()
        new_row["Datum"] = new_date
        df_productie_per_dag = pd.concat(
            [
                df_productie_per_dag.iloc[: i + 1],
                pd.DataFrame(new_row).T,
                df_productie_per_dag.iloc[i + 1 :],
            ]
        ).reset_index(drop=True)

# Define data types for each column
dtypes = {
    "JaarWeekDag": "int64",
    "JaarWeekDagVorigJaar": "int64",
    "TotaalProductiePY": "float64",
    "Datum": "datetime64[ns]",
    "ProductieM2": "float64",
    "ProductieM2PY": "float64",
    "WeekDag": "int64",
    "WeekNum": "int64",
    "Maand": "int64",
    "Jaar": "int64",
    "TotaalProductie": "float64",
    "KasTemperatuurEtmaal": "float64",
    "AVEtmaal": "float64",
    "PlantTemperatuurEtmaal": "float64",
    "BuitenTemperatuurEtmaal": "float64",
    "BuitenStralingssom": "int64",
    "BelichtingsUren": "float64",
    "DonkerTijd": "float64",
}

# Convert columns to specified data types
df_productie_per_dag = df_productie_per_dag.astype(dtypes)

# Set the Datum column as the index of the dataset
df_productie_per_dag["Datum"] = pd.to_datetime(df_productie_per_dag["Datum"])
df_productie_per_dag.set_index(df_productie_per_dag["Datum"], inplace=True)

# Create a subset of the data with the exogenous variables which are most important for the forecast
data = df_productie_per_dag[["TotaalProductie", "BuitenTemperatuurEtmaal"]]

# For the target variable: Take last 7 lags and the mean of the last 7 days as features
kwargs = {"lag_feature": {"lag": [1, 2, 3, 4, 5, 6, 7], "mean": [[1, 7]]}}
fe_target_rr = [WindowSummarizer(n_jobs=1, truncate="bfill", **kwargs)]

# Set up the model
exp = TSForecastingExperiment()
s = exp.setup(
    data,
    target="TotaalProductie",
    fold=fold,
    fh=fh,
    fe_target_rr=fe_target_rr,
    fig_kwargs=fig_kwargs,
)

# top 3 models based on MAPE - which is the most important metric for the analysis
best_mape_models_top3 = exp.compare_models(
    sort="MAPE", n_select=3, exclude=["auto_arima"]
)

# Blend the top 3 models to create the ensemble model
ensemble_ts = exp.blend_models(best_mape_models_top3)


# Train the ensemble model on all the data to use it for future datapoints
final_ensemble = exp.finalize_model(ensemble_ts)

"""
Using the Ensemble Time-Series Model to make predictions for the coming 10 days
"""

# Loading in the weather forecast data and implementing it into the exogenous variables
API_data = pd.read_excel(r"issues\3548\APIData.xlsx")

# new data frame with split value columns
splitdata = API_data["tijd_nl"].str.split(" ", n=1, expand=True)

# making separate columns from dataframe
API_data["Datum"] = splitdata[0]
API_data["Tijd"] = splitdata[1]
API_data.drop(columns=["tijd_nl"], inplace=True)

# Changing the data types to the correct ones
API_data["Datum"] = pd.to_datetime(API_data["Datum"], dayfirst=True)
API_data = API_data.astype({"temp": "float64"})

# Get the average temperature per day
pred_temp = API_data.groupby("Datum", as_index=False)["temp"].mean()

# Set the Datum column as the index of the dataset
pred_temp["Datum"] = pd.to_datetime(pred_temp["Datum"])
pred_temp.set_index(pred_temp["Datum"], inplace=True)

# Using the first predicted temperature to be used in the predictions
pred_temp = pred_temp.rename(columns={"temp": "BuitenTemperatuurEtmaal"})
var_first_temp = pred_temp["BuitenTemperatuurEtmaal"].iloc[1]
pred_temp["BuitenTemperatuurEtmaal"].iloc[0] = var_first_temp


# Creating the predictions for the upcoming 10 days
exp_future = TSForecastingExperiment()
future_preds = exp_future.predict_model(final_ensemble, X=pred_temp)

print("DONE")
```

![image](https://github.com/pycaret/pycaret/assets/33585645/fca1ccd2-f660-4beb-96d7-e57871213ad3)

**Comment by ngupta23** [comment] 2023-05-13 16:07
@thommyeur If this resolved the issue, please close this issue. Thanks!

**Comment by ngupta23** [comment] 2023-05-15 21:54
> If Pycaret handles the time features, why does the model performance increase when I add time features as variables?

> I am already helped a lot but the difference in performance is approximately 13% when looking at the MAPE for the new method and my old method.

It is possible that the model was overfitting and so when you did the future forecasts, it gave you the weird results (even though you Cross-validation results are better).

I also noticed that you were feeding the data time features such as month number as an integer. This will not work in theory since the impact of Dec (month 12) is not 12 times the impact of Jan (month 1). In fact, they should be relatively close to each other. Hence use of a cyclical term e.g. sin(month) or cos(month) may be more meaningful.

**Comment by thommyeur** [comment] 2023-05-16 07:55
Thanks! I will close the issue.

**Closed** 2023-05-16 07:55 UTC
Labels: time_series
