### ISSUE TITLE
[BUG] Getting error "cannot clone object DataTypes_Auto_Infer" after loading saved model and running blend_models(estimator_list=[tuned_model, bagged_model], method="soft").

### ISSUE THREAD

**Issue by maverick-scientist** [pycaret/pycaret#2420] opened 2022-04-17 15:53 UTC
**Describe the bug**
I loaded the saved models and ran the command blend_models(estimator_list=[tuned_model, bagged_model], method="soft"), but it resulted in the error as mentioned in the description.

**To Reproduce**
tuned_model = load_model(model_paths+'tuned_model_file_name')
bagged_model = load_model(model_paths+'bagged_model_file_name')
blend_models(estimator_list=[tuned_model, bagged_model], method="soft")

**Expected behavior**
The command should run without any issues.

Pycaret Version

2.3.10

**Comment by ngupta23** [comment] 2022-04-18 01:15
Did you run setup again before loading the models?

**Comment by maverick-scientist** [comment] 2022-04-18 01:27
Hi Nikhil,

Yes I did. I then loaded the saved models. I just don’t wish to retrain the
modes when I have them saved. And yes, model metadata was also saved
automatically.

Please advise.

Best Regards,
Abhinav

**Comment by ngupta23** [comment] 2022-04-18 01:57
Can you add a complete reproducible example so we can debug? See here:

📌 Overview: http://ow.ly/LoIv50IL5RQ
📌 Examples (Do's and Dont's): http://ow.ly/AXKm50IL5RR

**Comment by maverick-scientist** [comment] 2022-04-18 04:12
Steps to reproduce:

from pycaret.classification import *

exp01 = setup(data=data, target="Churn", session_id=789, ignore_features=["CUSTOMER_ID"],normalize=True, 
              feature_selection=True,log_experiment = True, experiment_name = 'churn_04',
              log_plots=True, log_profile=True, handle_unknown_categorical=True, 
              unknown_categorical_method='least_frequent',
              numeric_imputation='mean', 
              categorical_imputation='constant',
              profile=True,
              profile_kwargs={"explorative" : True, "minimal" : True},
              fix_imbalance=False)

model_paths = "path to the saved models"
tuned_model = load_model(model_paths+'tuned_model_version0.1_17apr22')
bagged_model = load_model(model_paths+'bagged_model_version0.1_17apr22')

blended_model = blend_models(estimator_list=[tuned_model, bagged_model], method="soft")

I could only share this much due to compliance policies in place.

Is there some parameter I'm missing in the "setup" method?

Please advise.

Thanks,
Abhinav

**Comment by ngupta23** [comment] 2022-04-18 17:32
@maverick-scientist again, there is not enough information here to recreate the issue or debug it. Note that if the data is proprietary, you can create a fake dataset yourself to recreate the issue. 

- The do's and dont's have an example of how to create the fake data - minimal to reproduce the problem.
- Alternately, you could try to reproduce the issue with a publicly available dataset or one available in pycaret itself.

Also, we need to also see how the model was created before saving as that may offer clues so provide the code for that as well.

**Comment by ngupta23** [comment] 2022-04-20 15:59
Since we are unable to recreate this and information seems to be missing, we will close this for now. Feel free to create a new issue. We add a new Bug template that will guide you through the process of submitting a reproducible example.

Thanks!

**Closed by ngupta23** 2022-04-20 15:59 UTC
Labels: bug, missing_info, load_models

**Comment by maverick-scientist** [comment] 2022-04-21 01:34
Sure Nikhil. Thank you for your support.
