### ISSUE TITLE
[BUG]: PYCARET AttributeError: 'NoneType' object has no attribute 'split' 

### ISSUE THREAD

**Issue by alvarado1984** [pycaret/pycaret#3605] opened 2023-06-15 21:53 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Hello, I have the same problem that has been reported. Two weeks ago everything was working fine. Has anyone solved it?
Error in Pycaret 3.0.0, 3.0.1. y 3.0.2

### Reproducible Example

```python
from pycaret.classification import *
```

### Expected Behavior

-.-

### Actual Results

```python-traceback
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_18180\796378970.py in <cell line: 30>()
     28 #importa librerias Pycaret
     29 # from pycaret import *
---> 30 from pycaret.classification import *

~\anaconda3\lib\site-packages\pycaret\classification\__init__.py in <module>
----> 1 from pycaret.classification.functional import (
      2     add_metric,
      3     automl,
      4     blend_models,
      5     calibrate_model,

~\anaconda3\lib\site-packages\pycaret\classification\functional.py in <module>
      6 from joblib.memory import Memory
      7 
----> 8 from pycaret.classification.oop import ClassificationExperiment
      9 from pycaret.internal.parallel.parallel_backend import ParallelBackend
     10 from pycaret.loggers.base_logger import BaseLogger

~\anaconda3\lib\site-packages\pycaret\classification\oop.py in <module>
     15 
     16 from pycaret.containers.metrics import get_all_class_metric_containers
---> 17 from pycaret.containers.models import get_all_class_model_containers
     18 from pycaret.containers.models.classification import (
     19     ALL_ALLOWED_ENGINES,

~\anaconda3\lib\site-packages\pycaret\containers\models\__init__.py in <module>
----> 1 from .anomaly import get_all_model_containers as get_all_anomaly_model_containers
      2 from .base_model import ModelContainer
      3 from .classification import get_all_model_containers as get_all_class_model_containers
      4 from .clustering import get_all_model_containers as get_all_clust_model_containers
      5 from .regression import get_all_model_containers as get_all_reg_model_containers

~\anaconda3\lib\site-packages\pycaret\containers\models\anomaly.py in <module>
     15 import pycaret.containers.base_container
     16 import pycaret.internal.cuml_wrappers
---> 17 from pycaret.containers.models.base_model import ModelContainer
     18 from pycaret.internal.distributions import Distribution
     19 from pycaret.utils.generic import get_logger, param_grid_to_lists

~\anaconda3\lib\site-packages\pycaret\containers\models\base_model.py in <module>
      7 from pycaret.containers.base_container import BaseContainer
      8 from pycaret.internal.distributions import CategoricalDistribution
----> 9 from pycaret.internal.pycaret_experiment.pycaret_experiment import _PyCaretExperiment
     10 from pycaret.utils.generic import get_allowed_engines, get_logger
     11 

~\anaconda3\lib\site-packages\pycaret\internal\pycaret_experiment\pycaret_experiment.py in <module>
     10 import pycaret.internal.patches.sklearn
     11 import pycaret.internal.patches.yellowbrick
---> 12 import pycaret.internal.persistence
     13 from pycaret import show_versions
     14 from pycaret.internal.logging import get_logger

~\anaconda3\lib\site-packages\pycaret\internal\persistence.py in <module>
     11 from pycaret.utils._dependencies import _check_soft_dependencies
     12 from pycaret.utils.generic import MLUsecase, get_logger
---> 13 from pycaret.utils.time_series.forecasting.pipeline import _add_model_to_pipeline
     14 
     15 

~\anaconda3\lib\site-packages\pycaret\utils\time_series\forecasting\pipeline.py in <module>
      4 import pandas as pd
      5 from sktime.forecasting.base import BaseForecaster
----> 6 from sktime.forecasting.compose import ForecastingPipeline
      7 from sktime.transformations.compose import TransformerPipeline
      8 from sktime.transformations.series.impute import Imputer

~\anaconda3\lib\site-packages\sktime\forecasting\compose\__init__.py in <module>
     30 ]
     31 
---> 32 from sktime.forecasting.compose._bagging import BaggingForecaster
     33 from sktime.forecasting.compose._column_ensemble import ColumnEnsembleForecaster
     34 from sktime.forecasting.compose._ensemble import (

~\anaconda3\lib\site-packages\sktime\forecasting\compose\_bagging.py in <module>
     12 from sklearn import clone
     13 from sklearn.utils import check_random_state
---> 14 from sklearn.utils._testing import set_random_state
     15 
     16 from sktime.datatypes._utilities import update_data

~\anaconda3\lib\site-packages\sklearn\utils\_testing.py in <module>
    398     fails_if_pypy = pytest.mark.xfail(IS_PYPY, reason="not compatible with PyPy")
    399     fails_if_unstable_openblas = pytest.mark.xfail(
--> 400         _in_unstable_openblas_configuration(),
    401         reason="OpenBLAS is unstable for this configuration",
    402     )

~\anaconda3\lib\site-packages\sklearn\utils\__init__.py in _in_unstable_openblas_configuration()
     88     import scipy  # noqa
     89 
---> 90     modules_info = threadpool_info()
     91 
     92     open_blas_used = any(info["internal_api"] == "openblas" for info in modules_info)

~\anaconda3\lib\site-packages\sklearn\utils\fixes.py in threadpool_info()
    148         return controller.info()
    149     else:
--> 150         return threadpoolctl.threadpool_info()
    151 
    152 

~\anaconda3\lib\site-packages\threadpoolctl.py in threadpool_info()
    122     In addition, each module may contain internal_api specific entries.
    123     """
--> 124     return _ThreadpoolInfo(user_api=_ALL_USER_APIS).todicts()
    125 
    126 

~\anaconda3\lib\site-packages\threadpoolctl.py in __init__(self, user_api, prefixes, modules)
    338 
    339             self.modules = []
--> 340             self._load_modules()
    341             self._warn_if_incompatible_openmp()
    342         else:

~\anaconda3\lib\site-packages\threadpoolctl.py in _load_modules(self)
    371             self._find_modules_with_dyld()
    372         elif sys.platform == "win32":
--> 373             self._find_modules_with_enum_process_module_ex()
    374         else:
    375             self._find_modules_with_dl_iterate_phdr()

~\anaconda3\lib\site-packages\threadpoolctl.py in _find_modules_with_enum_process_module_ex(self)
    483 
    484                 # Store the module if it is supported and selected
--> 485                 self._make_module_from_path(filepath)
    486         finally:
    487             kernel_32.CloseHandle(h_process)

~\anaconda3\lib\site-packages\threadpoolctl.py in _make_module_from_path(self, filepath)
    513             if prefix in self.prefixes or user_api in self.user_api:
    514                 module_class = globals()[module_class]
--> 515                 module = module_class(filepath, prefix, user_api, internal_api)
    516                 self.modules.append(module)
    517 

~\anaconda3\lib\site-packages\threadpoolctl.py in __init__(self, filepath, prefix, user_api, internal_api)
    604         self.internal_api = internal_api
    605         self._dynlib = ctypes.CDLL(filepath, mode=_RTLD_NOLOAD)
--> 606         self.version = self.get_version()
    607         self.num_threads = self.get_num_threads()
    608         self._get_extra_info()

~\anaconda3\lib\site-packages\threadpoolctl.py in get_version(self)
    644                              lambda: None)
    645         get_config.restype = ctypes.c_char_p
--> 646         config = get_config().split()
    647         if config[0] == b"OpenBLAS":
    648             return config[1].decode("utf-8")

AttributeError: 'NoneType' object has no attribute 'split'
```

### Installed Versions

Python 3.10.11
Pycaret 3.0.0
Pycaret 3.0.1
Pycaret 3.0.2

**Comment by ngupta23** [comment] 2023-06-15 22:30
Duplicate of #3569 and #3582.
The fix needs sktime to make a new release after removing private imports.

**Comment by ngupta23** [comment] 2023-06-16 22:39
Can you verify if installing sktime from git directly (which supposedly has the fix) resolves the issue.
i.e. in your current environment which is giving the failure, try installing

```
git clone https://github.com/sktime/sktime.git
```

**Comment by ngupta23** [comment] 2023-06-23 01:48
See https://github.com/pycaret/pycaret/issues/3569#issuecomment-1602729600 and https://github.com/pycaret/pycaret/issues/3569#issuecomment-1603527436 for potential solutions.

**Comment by alvarado1984** [comment] 2023-06-27 17:37
Hello, the problem still persists. Same error.

**Comment by ngupta23** [comment] 2023-06-27 22:33
If you have updated sktime to the latest version, you should not get the same error as that code has been removed. It may be coming from somewhere else. Can you paste the complete new error?

**Comment by alvarado1984** [comment] 2023-06-28 15:56
Update sktime its not was solve. The solution is !pip install --upgrade threadpoolctl. 

now pycaret 2.0 without error!

thank you so much!!! :)

**Comment by ngupta23** [comment] 2023-06-30 14:34
> now pycaret 2.0 without error!

You should not have done back to pycaret 2.0. Please try to use the latest pycaret version if possible.

> Update sktime its not was solve.

Could you still post the error message that you got when you upgraded to the latest sktime version (also indicate what sktime version it is)? It will help debug further.

**Comment by ngupta23** [comment] 2023-07-03 10:57
Closing for now. Please feel free to comment and/or reopen this if the issue persists.

Summary of Possible Solutions:

- Upgrade `threadpool`: `pip install --upgrade threadpoolctl`
- Upgrade `sktime`: `pip install sktime >= 0.19.2`

**Closed by ngupta23** 2023-07-03 10:57 UTC
Labels: bug, duplicate, time_series
