### ISSUE TITLE
Automated documentation / readthedocs account needed

### ISSUE THREAD

**Issue by pycaret** [pycaret/pycaret#374] opened 2020-08-06 01:56 UTC
# Help needed

Looking for somebody who can help develop automated documentation with theme. Currently, documentation is manually managed on website through wordpress template. It's a lot of work to maintain. We should create automated documentation using sphinx and set up a workflow to generate documents automatically with PR requests. 

Some work has already been done. Check closed PR and /doc folder in the repo. The problem with current work is that the formatting is completely out. Although structure should remain similiar / or if you want you can build new structure using pycaret.org/guide as building blocks.

Thanks for your help. For discussion reach out moez.ali@queensu.ca

**Comment by Yard1** [comment] 2020-08-06 17:40
If nobody picks this up I can take a look in a day or two.

**Comment by pycaret** [comment] 2020-08-07 12:10
@Yard1 Thanks

**Comment by Yard1** [comment] 2020-08-07 16:40
What's the formatting issue exactly? Could you show me an example of how it should look like? Or should I look at the current site for guidance?

**Comment by Yard1** [comment] 2020-08-07 16:46
Ok, yeah, it seems that the issue is that the current docstrings don't follow a format recommended by Sphinx. I'll see if this is something that can be fixed with Sphinx configuration itself, but I fear that we may need to rewrite all the docstrings to one standardized format. While we're at it, we could add typing to all the methods, too.

**Comment by Yard1** [comment] 2020-08-07 16:59
Ok, found the issue. The formatting for docstrings is missing indents. For example:

bad:
```
    Parameters
    ----------
    optimize : string, default = 'R2'
    Other values you can pass in optimize param are 'MAE', 'MSE', 'RMSE',
    'RMSLE', and 'MAPE'. 

    use_holdout: bool, default = False
    When set to True, metrics are evaluated on holdout set instead of CV.
```
good:
```
    Parameters
    ----------
    optimize : string, default = 'R2'
        Other values you can pass in optimize param are 'MAE', 'MSE', 'RMSE',
        'RMSLE', and 'MAPE'. 

    use_holdout: bool, default = False
        When set to True, metrics are evaluated on holdout set instead of CV.
```
I'll add indents where necessary and open a PR. Sphinx configuration itself seems to be fine.

**Comment by Yard1** [comment] 2020-08-07 19:00
https://github.com/pycaret/pycaret/pull/390

If you want me to, I can set up an account on readthedocs as well - though I am not sure whether it will require some repo permissions or not.

**Closed** 2020-08-08 17:15 UTC
Labels: Author's Announcement

**Comment by pycaret** [comment] 2020-08-14 04:21
@Yard1 One question. The sequence of modules in the documentation and the sequence of functions inside each module? Is it automatically determined by the position of code or is it something we can control? Can we have the following order of modules in documentation

- Classification
- Regression
- Clustering
- Anomaly Detection
- Natural Language Processing
- Association Rule Mining

**Comment by Yard1** [comment] 2020-08-14 08:10
It's something we can control by editing the Sphinx files, yes. I'll make a PR for this.
