### ISSUE TITLE
Feature Proposal: adding support for GCP model deployment

### ISSUE THREAD

**Issue by amjadraza** [pycaret/pycaret#148] opened 2020-05-18 11:10 UTC
# Deploy Models on GCP

Adding support to deploy models on GCP along with aws. 

## Assignees
happy to contribute

## Background
the idea is to add another cloud deployment such as GCP. Currently, library supports deployment on aws, I think we can easily add support for gcp.

## Constraints and Assumptions
the life cycle of code would remains the same. Adding one more `gcp`  parameter for in `save_model` and `load_model`

## Minimal Working example
https://medium.com/@amjadraza24/build-with-pycaret-deploy-with-gcp-97df8682ee92

[enhancement]

**Comment by pycaret** [comment] 2020-05-21 13:47
@amjadraza Thanks for sharing. I haven't gone through the entire medium article but I like the post. I will try to read it over the weekend. I would be happy to take this enhancement.

Can you please review the code of deploy_model function. That's how I have handled AWS. It seems like GCP will also be a similar idea i.e. save pickle file on GCP through your notebook. 

For AWS deployment. I am using aws sdk that allows to configure keys and access through command line by using aws configure (one time only). Hence when deploying model using pycaret the only thing required from user is bucket name hence no keys / passwords are passed in function. Is it going to be similar for GCP?

Do you also have expertise in Azure? 

Thanks for your help. Wonderful suggestions.

[ENHANCEMENT]

**Comment by amjadraza** [comment] 2020-05-22 23:35
@pycaret I have included working google colab notebook and written the code after reading deploy_model function for `aws`.  I followed the similar idea of authentication must be done through command line or notebook also set the target project in your environment. No keys are passwords needed to be passed. 

I am not expert with Azure, however looking at briefly it is pretty straight forward to store blob (model) at Azure. Will give it a try and share the codes. 

Can you point to me about the contributing guide so I can prepare a PR ?

Thanks

**Comment by amjadraza** [comment] 2020-05-23 04:44
@pycaret I have given a try with Azure and made it work. see the below article.

https://medium.com/@amjadraza24/build-with-pycaret-deploy-on-azure-6099fd4bce24

**Comment by pycaret** [comment] 2020-05-24 13:02
@amjadraza I have read your article. Beauty. It seems like we can use the same approach as AWS and can include Azure and GCP under deploy_model function. Do you plan to submit a PR on this?

**Comment by amjadraza** [comment] 2020-05-25 07:52
@pycaret , yes I will prepare `deploy_model` and `load_model` functions with azure and GCP and will send a PR. 

Is there any deadline for next public release?

**Comment by amjadraza** [comment] 2020-05-26 11:37
@pycaret , I have noticed that there repetition of `deploy_model` and `load_model` function in `regression.py` and `clustering.py`. Is it something intended? 

I have modified above function in below file for initial review. 

https://github.com/amjadraza/pycaret/blob/feature/gcp-azure-deploy/utils.py

Any feedback is welcomed. 

I have not tested tested them yet so no PR ready.

**Comment by amjadraza** [comment] 2020-06-30 08:03
@pycaret , any update regarding above issue?

**Comment by pycaret** [comment] 2020-08-04 03:36
@amjadraza Hi Amjad, Sorry for this long delay in getting back. Since PyCaret 2.0 is now released, I was planning to include this functionality in next sprint (2.1). Let me know if you have availability to work on this? I think you have already done most of the work, its just the testing.

We will have to incorporate this change in deploy_model function in all modules separately as the function uses global environment variables. That's why there is repitition, but let's start with one module, rest of them would be replica.

Let's start with `classification.py` and see how that goes?

**Comment by amjadraza** [comment] 2020-08-04 06:54
@pycaret, I understand your point. I had tested the functionality using google colab. Let me fork the Latest version and add the extra modules. 

I can work on it and will send you the pull request soon.

Thanks

**Comment by amjadraza** [comment] 2020-08-06 12:50
@pycaret , I have added some functionality on below branch in `classification.py`

https://github.com/amjadraza/pycaret/blob/feature/gcp_zure_integration/pycaret/classification.py

Please have a look if I am following entirely different approach. Targeting to finalise GCP over the weekend.

Thanks

**Comment by pycaret** [comment] 2020-08-06 19:34
@amjadraza Which function should I look at?  Is this the code chunk? 

```
    elif platform == 'gcp':
        import gcp_utils as gcp_utils
        save_model(model, model_name=model_name, verbose=False)
        filename = str(model_name) + '.pkl'
        key = str(model_name) + '.pkl'
        bucket_name = authentication.get('bucket')
        project_name = authentication.get('project')
        print('Deploying model to Google Cloud Platform')
        # Create Bucket
        gcp_utils.create_bucket(project_name, bucket_name)
        gcp_utils.upload_blob(project_name, bucket_name, filename, key)

    elif platform == 'azure':
        import azure_utils as azure_utils
        print('Deploying model to Microsoft Azure')
        save_model(model, model_name=model_name, verbose=False)
        filename = str(model_name) + '.pkl'
        key = str(model_name) + '.pkl'
        container_name = authentication.get('container')
        container_client = azure_utils.create_container(container_name)
        azure_utils.upload_blob(container_name, filename, key)
```

**Comment by amjadraza** [comment] 2020-08-07 00:26
@pycaret , Sorry I should have mentioned the exact location since file is more than 10,000 lines (May be you can think of modularisation later on) .

I have add my code in two functions and added two utility files

1. `gcp_utils.py` and `azure_utils.py`
2. `load_model` and 'deploy_model` are the functions with the code. 

Added the documentation same format as were being adopted.

**Comment by amjadraza** [comment] 2020-08-08 03:13
@pycaret 

I have tested for GCP and Azure. Below is the link to the test google colab.

https://github.com/amjadraza/pycaret/blob/feature/gcp_zure_integration/tutorials/GCP_AZURE_Binary_Classification_Tutorial_Level_Beginner_CLF101.ipynb

**Comment by amjadraza** [comment] 2020-08-09 01:51
@pycaret 

I have completed the documentation for GCP and azure utilities in `classification.py`

I think, we can include the features in `regression.py` and other modules..

**Comment by pycaret** [comment] 2020-08-09 14:34
@amjadraza That's great. I tried `azure` and it works perfectly fine. For GCP I am getting the following error. 

Any idea?

![image](https://user-images.githubusercontent.com/58118658/89734724-d332eb80-da2b-11ea-8819-438b0eedaaf8.png)

**Comment by pycaret** [comment] 2020-08-09 14:44
@amjadraza Also, Recently I have removed direct predict functionality from `predict_model` function so need to worry about that part. Going forward, `load_model` must load model from platform and then used loaded model object inside `predict_model`. This simplifies things a little. So we only have to manage the impact in `deploy_model` and `load_model`. Also following steps:

- `azure_utils.py` `gcp_utils.py` <-- are these files imported in `classification.py`. There are few new functions added at the bottom of `classification.py` but I am not sure if we are using `azure_utils.py` and `gcp_utils.py`? A little bit clarification would help.

- let's add azure and gcp sdk in `requirements.txt` but comment them out just like I did for 'awscli'

- in `deploy_model` function, I have added an exception to check `awscli` if not found, give sys error. Now that we have `azure` and `gcp`, you will also have to create similar exceptions but this time, exception should show up in their relevant if statement. For example, `awscli` exception should move into if statement of `platform = aws`.

- I think we are almost there in regards to this change. I am just not too sure about the point 1. Let's target to add this functionality for `azure` and `gcp` in `2.1` release targeted by the end of August 2020.  

Thanks for working on it.

**Comment by amjadraza** [comment] 2020-08-09 23:21
> @amjadraza That's great. I tried `azure` and it works perfectly fine. For GCP I am getting the following error.
> 
> Any idea?
> 
> ![image](https://user-images.githubusercontent.com/58118658/89734724-d332eb80-da2b-11ea-8819-438b0eedaaf8.png)

It is because, the project on GCP might not created or permissions are not set properly. For GCP, in order to create storage bucket, you must have a project created and enable the services to use. Once you create the project, it should be simple. we can create project from python command but it is easy to use the GUI for it.

**Comment by amjadraza** [comment] 2020-08-10 08:22
> @amjadraza Also, Recently I have removed direct predict functionality from `predict_model` function so need to worry about that part. Going forward, `load_model` must load model from platform and then used loaded model object inside `predict_model`. This simplifies things a little. So we only have to manage the impact in `deploy_model` and `load_model`. Also following steps:
> 
> * `azure_utils.py` `gcp_utils.py` <-- are these files imported in `classification.py`. There are few new functions added at the bottom of `classification.py` but I am not sure if we are using `azure_utils.py` and `gcp_utils.py`? A little bit clarification would help.
> Not required as you suggested to copy the functions inside the classification modules.

> * let's add azure and gcp sdk in `requirements.txt` but comment them out just like I did for 'awscli' 
> DONE
> * in `deploy_model` function, I have added an exception to check `awscli` if not found, give sys error. Now that we have `azure` and `gcp`, you will also have to create similar exceptions but this time, exception should show up in their relevant if statement. For example, `awscli` exception should move into if statement of `platform = aws`.
> DONE
> * `logger` functionality must exist for `azure` and `gcp`. See how I have added logs in `platform = aws`  in `deploy_model` function. You can copy-paste that.
> DONE
> * Recently @Yard1 has updated the format for all the docstrings to comply with `numpy` standards. Please make sure you either sync to latest repo or account for the formatting changes.
> DONE, I was wondering, documentation was not standard but its fixed now.
> * I think we are almost there in regards to this change. I am just not too sure about the point 1. Let's target to add this functionality for `azure` and `gcp` in `2.1` release targeted by the end of August 2020.

> No problem, we will be ready by then.
> 
> Thanks for working on it.


A new branch with above modifications.

https://github.com/amjadraza/pycaret/tree/feature/gcp_azure_np_docs

Example Notebokks for classification and Regression 

https://github.com/amjadraza/pycaret/tree/feature/gcp_azure_np_docs/examples

**Comment by pycaret** [comment] 2020-08-12 23:53
@amjadraza Hi.

I am still facing issues with deploying on GCP. I followed the instructions given here: https://cloud.google.com/docs/authentication/production and

- created a service account and downloaded `json`
- set environment var `GOOGLE_APPLICATION_CREDENTIALS` to `json path`
- executed `deploy_model`, this is my code and the error traceback: 

Can you please sync the latest repo and try to deploy on `GCP` by creating a new project altogether. The reason I am doing this so that we can make documentation more clear and easy to understand. 

Thanks

```
deploy_model(lr, model_name = 'lr-gcp', authentication = {'project': 'upload-test', 'bucket' : 'pycaret-test'}, platform = 'gcp')
```

Forbidden                                 Traceback (most recent call last)
<ipython-input-7-a7ab3e27ef99> in <module>
----> 1 deploy_model(lr, model_name = 'lr-gcp', authentication = {'project': 'upload-test', 'bucket' : 'pycaret-test'}, platform = 'gcp')

~\pycaret\pycaret\pycaret\classification.py in deploy_model(model, model_name, authentication, platform)
   9921         bucket_name = authentication.get('bucket')
   9922         project_name = authentication.get('project')
-> 9923         _create_bucket_gcp(project_name, bucket_name)
   9924         _upload_blob_gcp(project_name, bucket_name, filename, key)
   9925         os.remove(filename)

~\pycaret\pycaret\pycaret\classification.py in _create_bucket_gcp(project_name, bucket_name)
  10778     buckets = storage_client.list_buckets()
  10779 
> 10780     if bucket_name not in buckets:
  10781         bucket = storage_client.create_bucket(bucket_name)
  10782         logger.info("Bucket {} created".format(bucket.name))

~\Anaconda3\envs\pycaret-dev\lib\site-packages\google\api_core\page_iterator.py in _items_iter(self)
    210     def _items_iter(self):
    211         """Iterator for each item returned."""
--> 212         for page in self._page_iter(increment=False):
    213             for item in page:
    214                 self.num_results += 1

~\Anaconda3\envs\pycaret-dev\lib\site-packages\google\api_core\page_iterator.py in _page_iter(self, increment)
    241             Page: each page of items from the API.
    242         """
--> 243         page = self._next_page()
    244         while page is not None:
    245             self.page_number += 1

~\Anaconda3\envs\pycaret-dev\lib\site-packages\google\api_core\page_iterator.py in _next_page(self)
    367         """
    368         if self._has_next_page():
--> 369             response = self._get_next_page_response()
    370             items = response.get(self._items_key, ())
    371             page = Page(self, items, self.item_to_value, raw_page=response)

~\Anaconda3\envs\pycaret-dev\lib\site-packages\google\api_core\page_iterator.py in _get_next_page_response(self)
    417         if self._HTTP_METHOD == "GET":
    418             return self.api_request(
--> 419                 method=self._HTTP_METHOD, path=self.path, query_params=params
    420             )
    421         elif self._HTTP_METHOD == "POST":

~\Anaconda3\envs\pycaret-dev\lib\site-packages\google\cloud\_http.py in api_request(self, method, path, query_params, data, content_type, headers, api_base_url, api_version, expect_json, _target_object, timeout)
    421 
    422         if not 200 <= response.status_code < 300:
--> 423             raise exceptions.from_http_response(response)
    424 
    425         if expect_json and response.content:

Forbidden: 403 GET https://storage.googleapis.com/storage/v1/b?project=upload-test&projection=noAcl: gcp-service-account-upload-tes@upload-test-285914.iam.gserviceaccount.com does not have storage.buckets.list access to the Google Cloud project.

**Comment by amjadraza** [comment] 2020-08-14 01:25
> @amjadraza Hi.
> 
> I am still facing issues with deploying on GCP. I followed the instructions given here: https://cloud.google.com/docs/authentication/production and
> 
> * created a service account and downloaded `json`
> * set environment var `GOOGLE_APPLICATION_CREDENTIALS` to `json path`
> * executed `deploy_model`, this is my code and the error traceback:
> 
> Can you please sync the latest repo and try to deploy on `GCP` by creating a new project altogether. The reason I am doing this so that we can make documentation more clear and easy to understand.
> 
> Thanks
> 
> ```
> deploy_model(lr, model_name = 'lr-gcp', authentication = {'project': 'upload-test', 'bucket' : 'pycaret-test'}, platform = 'gcp')
> ```
> 
> Forbidden Traceback (most recent call last)
> in
> ----> 1 deploy_model(lr, model_name = 'lr-gcp', authentication = {'project': 'upload-test', 'bucket' : 'pycaret-test'}, platform = 'gcp')
> 
> ~\pycaret\pycaret\pycaret\classification.py in deploy_model(model, model_name, authentication, platform)
> 9921 bucket_name = authentication.get('bucket')
> 9922 project_name = authentication.get('project')
> -> 9923 _create_bucket_gcp(project_name, bucket_name)
> 9924 _upload_blob_gcp(project_name, bucket_name, filename, key)
> 9925 os.remove(filename)
> 
> ~\pycaret\pycaret\pycaret\classification.py in _create_bucket_gcp(project_name, bucket_name)
> 10778 buckets = storage_client.list_buckets()
> 10779
> 
> > 10780     if bucket_name not in buckets:
> > 10781         bucket = storage_client.create_bucket(bucket_name)
> > 10782         logger.info("Bucket {} created".format(bucket.name))
> 
> ~\Anaconda3\envs\pycaret-dev\lib\site-packages\google\api_core\page_iterator.py in _items_iter(self)
> 210 def _items_iter(self):
> 211 """Iterator for each item returned."""
> --> 212 for page in self._page_iter(increment=False):
> 213 for item in page:
> 214 self.num_results += 1
> 
> ~\Anaconda3\envs\pycaret-dev\lib\site-packages\google\api_core\page_iterator.py in _page_iter(self, increment)
> 241 Page: each page of items from the API.
> 242 """
> --> 243 page = self._next_page()
> 244 while page is not None:
> 245 self.page_number += 1
> 
> ~\Anaconda3\envs\pycaret-dev\lib\site-packages\google\api_core\page_iterator.py in _next_page(self)
> 367 """
> 368 if self._has_next_page():
> --> 369 response = self._get_next_page_response()
> 370 items = response.get(self._items_key, ())
> 371 page = Page(self, items, self.item_to_value, raw_page=response)
> 
> ~\Anaconda3\envs\pycaret-dev\lib\site-packages\google\api_core\page_iterator.py in _get_next_page_response(self)
> 417 if self._HTTP_METHOD == "GET":
> 418 return self.api_request(
> --> 419 method=self._HTTP_METHOD, path=self.path, query_params=params
> 420 )
> 421 elif self._HTTP_METHOD == "POST":
> 
> ~\Anaconda3\envs\pycaret-dev\lib\site-packages\google\cloud_http.py in api_request(self, method, path, query_params, data, content_type, headers, api_base_url, api_version, expect_json, _target_object, timeout)
> 421
> 422 if not 200 <= response.status_code < 300:
> --> 423 raise exceptions.from_http_response(response)
> 424
> 425 if expect_json and response.content:
> 
> Forbidden: 403 GET https://storage.googleapis.com/storage/v1/b?project=upload-test&projection=noAcl: [gcp-service-account-upload-tes@upload-test-285914.iam.gserviceaccount.com](mailto:gcp-service-account-upload-tes@upload-test-285914.iam.gserviceaccount.com) does not have storage.buckets.list access to the Google Cloud project.


Looks like your service account does not have proper roles. 


From the Role list, select Project > Owner.

Note: The Role field authorizes your service account to access resources. You can view and change this field later by using the Cloud Console. If you are developing a production app, specify more granular permissions than Project > Owner. For more information, see granting roles to service accounts.

I will test myself to recreate the error..

**Comment by pycaret** [comment] 2020-08-14 01:45
@amjadraza Actually you are right. No need to reproduce this. I have figured it out. Closing this now.

**Closed by pycaret** 2020-08-14 01:45 UTC
Labels: enhancement
