### ISSUE TITLE
[BUG]: Nested runs stacked indefinetely (Databricks)

### ISSUE THREAD

**Issue by sebwen** [pycaret/pycaret#3142] opened 2022-12-02 12:35 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

I use pycaret from within databricks. I intent to log my experiments via mlflow. Everything runs fine and every experiment is logged, but each run becomes a child of the previous run. This seems to go on indefinetely.

I have first encountered this issue with the latest stable version 2.3.10. I can also confirm that this issue is already present in v2.3.8 and v2.3.7. The curious behaviour has changed though. Each setup initiation is listed independently in v2.3.8, whereas each run becomes the child of the previous run. In v2.3.10 everything, regardless of it being the setup initation or a run, becomes nested. Please have a look at the following screenshots of the mlflow UI for clarification. 

When I run and log the identical experiment in v3.2.6 all runs are listed independently as well assigned correctly to the respective setups. The feature of nested runs was first introduced in v2.3.5: [PR](https://github.com/pycaret/pycaret/pull/1660/commits/da39a45c267dea41acb22b20a8ee05df4bdc9377).

### Reproducible Example

```python
from pycaret import regression
regression.setup(data=df, target='target', log_experiment=True, experiment_name="some name")
regression.compare_models()
regression.setup(data=df, target='target', log_experiment=True, experiment_name="some name")
regression.compare_models()
```

### Expected Behavior

![grafik](https://user-images.githubusercontent.com/68019575/205292672-521ef54f-3eab-4078-bb97-0be30d805486.png)

### Actual Results

v2.3.10
![grafik](https://user-images.githubusercontent.com/68019575/205291898-e62f9d32-233c-4f6c-9d92-ff2e2643245d.png)

v2.3.8
![grafik](https://user-images.githubusercontent.com/68019575/205291101-760af336-e5d6-45fb-bd50-2d44ff78367a.png)

### Installed Versions

I have tried pycaret v2.3.7, v2.3.8 and v2.3.10. These verions all show the odd behaviour as described above.

**Comment by ngupta23** [comment] 2022-12-02 12:43
Possible duplicate of https://github.com/pycaret/pycaret/issues/2975 & https://github.com/pycaret/pycaret/issues/3059. Can you check with the pre-release version of pycaret

```
pip install -U --pre pycaret
```

**Comment by moezali1** [comment] 2022-12-02 12:57
@sebwen Please install the latest version of pycaret. The issue has already been resolved.

```
pip install --pre pycaret
```

**Closed by moezali1** 2022-12-02 12:57 UTC
Labels: bug, duplicate, mlflow, databricks
