### ISSUE TITLE
[BUG]: fix_imbalance doesn't give equal number between positive and negative class

### ISSUE THREAD

**Issue by westwashin** [pycaret/pycaret#3718] opened 2023-08-30 14:57 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Im working with pycaret and streamlit to visualize the research.
the result for this classification is high, but i don't know how the fix_imbalance using smote work, because i don't get an equal number between transformed_test and transformed_train. when i visualize it using plotbar it doesnt give an equal number after i using smote to oversample the dataset in Outcome features in pima indian diabetic dataset.

i need help for this or at least some explanation about why fix_imbalance using smote did not make the data equal?

### Reproducible Example

```python
def model():
    st.title("Setup Dataset untuk dilakukan Klasifikasi")
    st.write("Pada Tahapan ini, akan mempersiapkan dataset untuk diklasifikasi. Dataset akan di preprocess n\
        menggunakan SMOTE untuk menghilangkan ketidakseimbangan pada kolom categorical.")

    if "df_clean" not in st.session_state:
        st.session_state.df_clean = None

    df_clean = st.session_state.df_clean
    with st.container():
        placeholder_md = st.button("Setup Klasifikasi")
        if placeholder_md:
            with st.spinner("Melakukan Setup pada Dataset..."):
                setup(data=df_clean, train_size=0.8, target="Outcome", fix_imbalance=True, fix_imbalance_method='smote')
                setup_df = pull()
                st.write("Setup Klasifikasi pada Dataset yang akan digunakan:")
                st.dataframe(setup_df, use_container_width=True)
                train_transformed = get_config('train_transformed')
                test_transformed = get_config('test_transformed')
                transformed_data = get_config('dataset_transformed')

                st.write("Transformed Test Data shape:", test_transformed.shape)
                st.dataframe(test_transformed, use_container_width=True)               

                st.write("Transformed Traning Data shape:", train_transformed.shape)
                st.dataframe(train_transformed, use_container_width=True)

                st.write("Data yang telah bersih dari ketidakseimbangan data:")
                pd.value_counts(transformed_data['Outcome']).plot.bar()
                plt.title('Outcome')
                plt.xlabel('Kelas')
                plt.ylabel('Jumlah')
                transformed_data['Outcome'].value_counts()
                st.pyplot(plt)
```

### Expected Behavior

result :
![image](https://github.com/pycaret/pycaret/assets/61764924/82b43b54-343e-4ef8-bf95-ff4ba03f261c)

`expected: 1 : 500`
`                0 : 500`

### Actual Results

```python-traceback
when i print this it shows 954 transformed dataset shape, it splits into 800 as traning and 154 as testing, but in the plotbar shows the negative and positive class is not imbalance
```

### Installed Versions

<details>
pycaret 3.0.4
</details>

**Comment by whatsmynameidontknow** [comment] 2023-08-31 04:16
That's not a bug, and there's nothing wrong with PyCaret. In your code, you have written:
```Python
pd.value_counts(transformed_data['Outcome']).plot.bar()
```
This code displays the entire dataset. However, please note that SMOTE only balances the training data. Consequently, your plot might depict an imbalanced class distribution. To address this, you should modify your code to:
```Python
pd.value_counts(train_transformed['Outcome']).plot.bar()
```
This adjustment ensures that you plot the balanced data resulting from the application of SMOTE. Please close this issue, Thanks!

**Comment by moezali1** [comment] 2023-10-06 20:20
What @whatsmynameidontknow is correct. The SMOTE is applied on train set only. Thanks.

**Closed by moezali1** 2023-10-06 20:20 UTC
Labels: bug
