### ISSUE TITLE
[BUG]: PicklingError: Could not pickle the task to send it to the workers.

### ISSUE THREAD

**Issue by ArtificialZeng** [pycaret/pycaret#2961] opened 2022-09-13 06:19 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?610f0d53-45c7-4838-a265-8be04a2659ab)
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "e:\A_IDE\Anaconda3\envs\py382\lib\site-packages\joblib\externals\loky\backend\queues.py", line 153, in _feed
    obj_ = dumps(obj, reducers=reducers)
  File "e:\A_IDE\Anaconda3\envs\py382\lib\site-packages\joblib\externals\loky\backend\reduction.py", line 271, in dumps
    dump(obj, buf, reducers=reducers, protocol=protocol)
  File "e:\A_IDE\Anaconda3\envs\py382\lib\site-packages\joblib\externals\loky\backend\reduction.py", line 264, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
  File "e:\A_IDE\Anaconda3\envs\py382\lib\site-packages\joblib\externals\cloudpickle\cloudpickle_fast.py", line 602, in dump
    return Pickler.dump(self, obj)
  File "e:\A_IDE\Anaconda3\envs\py382\lib\site-packages\joblib\_memmapping_reducer.py", line 442, in __call__
    for dumped_filename in dump(a, filename):
  File "e:\A_IDE\Anaconda3\envs\py382\lib\site-packages\joblib\numpy_pickle.py", line 482, in dump
    NumpyPickler(f, protocol=protocol).dump(value)
  File "e:\A_IDE\Anaconda3\envs\py382\lib\pickle.py", line 485, in dump
    self.save(obj)
  File "e:\A_IDE\Anaconda3\envs\py382\lib\site-packages\joblib\numpy_pickle.py", line 281, in save
    wrapper.write_array(obj, self)
  File "e:\A_IDE\Anaconda3\envs\py382\lib\site-packages\joblib\numpy_pickle.py", line 104, in write_array
    pickler.file_handle.write(chunk.tobytes('C'))
OSError: [Errno 28] No space left on device
"""
...
--> 388         raise self._exception
    389     else:
    390         return self._result

PicklingError: Could not pickle the task to send it to the workers.

### Reproducible Example

```python
tuned_lgb = tune_model(lightgbm)
```

### Expected Behavior

tuned_lgb = tune_model(lightgbm)

### Actual Results

```python-traceback
tuned_lgb = tune_model(lightgbm)
```

### Installed Versions

<details>
Replace this line with the output of the version code above.
</details>

**Comment by tvdboom** [comment] 2022-09-15 06:19
Please, add a full reproducible example. We can't debug without it.

**Comment by ngupta23** [comment] 2022-11-26 19:18
Closing due to missing information. Feel free to reopen if you have an update.

**Closed by ngupta23** 2022-11-26 19:18 UTC
Labels: bug, missing_info
