### ISSUE TITLE
[INSTALL]: How to install pycaret 2.3.10 with timeseries

### ISSUE THREAD

**Issue by 5xcor** [pycaret/pycaret#2505] opened 2022-05-05 16:20 UTC
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

macOS-10.15.7-x86_64-i386-64bit

### Installation Method

Built from source

### pycaret Version

2.3.10

### Python Version

3.8.10

### Description

1. step - create new conda env with python 3.8
2. Install: pip install pycaret 
3. test version - output is: '2.3.10'
4. install: pip install pycaret-ts-alpha
5. test version - output is: '3.0.0'

### Installation Logs

<details>
...
  Attempting uninstall: imbalanced-learn
    Found existing installation: imbalanced-learn 0.7.0
    Uninstalling imbalanced-learn-0.7.0:
      Successfully uninstalled imbalanced-learn-0.7.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pycaret 2.3.10 requires imbalanced-learn==0.7.0, but you have imbalanced-learn 0.9.0 which is incompatible.
pycaret 2.3.10 requires numba<0.55, but you have numba 0.55.1 which is incompatible.
pycaret 2.3.10 requires scikit-learn==0.23.2, but you have scikit-learn 1.0.2 which is incompatible.
pycaret 2.3.10 requires scipy<=1.5.4, but you have scipy 1.7.3 which is incompatible.
pandas-profiling 3.2.0 requires joblib~=1.1.0, but you have joblib 1.0.1 which is incompatible.
Successfully installed Cython-0.29.28 category-encoders-2.4.0 deprecated-1.2.13 imbalanced-learn-0.9.0 joblib-1.0.1 kaleido-0.2.1 llvmlite-0.38.0 numba-0.55.1 numpy-1.21.6 pmdarima-1.8.5 pycaret-ts-alpha-3.0.0.dev1649017462 scikit-learn-1.0.2 scipy-1.7.3 sktime-0.10.1 tbats-1.1.0 wrapt-1.14.1 yellowbrick-1.4
</details>

**Comment by ngupta23** [comment] 2022-05-05 20:06
You can not install `pycaret-ts-alpha` with `pycaret` < 3.0.0 (unreleased) in the same env due to dependency conflicts. In the `pycaret` 3.0.0 release, you will be able to do that. If you would like to test that, you can try this for now:

```bash
pip install -U git+https://github.com/pycaret/pycaret.git@develop
```

This should be the one that eventually gets released as `pycaret` 3.0.0 with time series integrated with other modules like regression/classification, etc.

**Comment by ngupta23** [comment] 2022-05-05 20:07
Just a caveat, this is still in development, so exercise caution for now.

**Comment by ngupta23** [comment] 2022-05-14 19:48
Closing for now, feel free to reopen (or submit a new issue) if your have more questions.

**Closed by ngupta23** 2022-05-14 19:48 UTC
Labels: installation, time_series, mac
