### ISSUE TITLE
Getting Error : Feature Names Mismatch

### ISSUE THREAD

**Issue by neuratree** [pycaret/pycaret#387] opened 2020-08-07 14:05 UTC
feature_names mismatch: ['f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22', 'f23', 'f24', 'f25', 'f26', 'f27', 'f28', 'f29', 'f30', 'f31', 'f32', 'f33', 'f34', 'f35', 'f36', 'f37', 'f38', 'f39', 'f40', 'f41', 'f42', 'f43', 'f44'] ['Component_1', 'Component_2', 'Component_3', 'Component_4', 'Component_5', 'Component_6', 'Component_7', 'Component_8', 'Component_9', 'Component_10', 'Component_11', 'Component_12', 'Component_13', 'Component_14', 'Component_15', 'Component_16', 'Component_17', 'Component_18', 'Component_19', 'Component_20', 'Component_21', 'Component_22', 'Component_23', 'Component_24', 'Component_25', 'Component_26', 'Component_27', 'Component_28', 'Component_29', 'Component_30', 'Component_31', 'Component_32', 'Component_33', 'Component_34', 'Component_35', 'Component_36', 'Component_37', 'Component_38', 'Component_39', 'Component_40', 'Component_41', 'Component_42', 'Component_43', 'Component_44', 'Component_45']
expected f5, f35, f15, f0, f9, f11, f34, f36, f7, f20, f42, f8, f33, f22, f27, f41, f18, f30, f4, f12, f14, f32, f43, f37, f19, f28, f25, f13, f2, f44, f16, f3, f17, f29, f31, f24, f38, f39, f10, f23, f26, f1, f40, f6, f21 in input data
training data did not have the following fields: Component_21, Component_43, Component_36, Component_41, Component_12, Component_16, Component_34, Component_33, Component_4, Component_13, Component_32, Component_45, Component_3, Component_39, Component_40, Component_35, Component_38, Component_31, Component_44, Component_15, Component_37, Component_26, Component_9, Component_29, Component_23, Component_14, Component_11, Component_1, Component_8, Component_7, Component_19, Component_42, Component_17, Component_18, Component_6, Component_22, Component_2, Component_27, Component_28, Component_24, Component_20, Component_10, Component_5, Component_30, Component_25

**Comment by neuratree** [comment] 2020-08-07 14:05
clf1 = setup(dataset, target = 'resolved', pca = True, pca_components = 0.9, fix_imbalance = True)

**Comment by mahmoudyusof** [comment] 2020-08-08 15:56
did this error occur when you called the `setup` function or when?

**Comment by neuratree** [comment] 2020-08-08 16:28
I got this on running the compare_models()

**Comment by pycaret** [comment] 2020-08-08 17:43
@neuratree Can you please provide more details. Can you also upload sample dataset here so that we can try to reproduce the error?

**Comment by yashmehta10** [comment] 2020-08-10 04:00
Hi @neuratree, did you get this error while running XGBoost? I got the same error while running XGBoost in compare_models()

**Comment by neuratree** [comment] 2020-08-10 13:06
Yes, it was in one specific model, but then I am not sure if other models are running correctly

**Comment by yashmehta10** [comment] 2020-08-10 14:13
I am not sure about the solution but for time being try blacklisting the model when this happens.

**Comment by joaomicunha** [comment] 2020-08-17 16:05
any news on this? getting the same error with xgboost

**Comment by neuratree** [comment] 2020-08-17 17:50
@pycaret : I also got this error with XGBoost..... Seems like a common issue....

@joaomicunha : Is it possible for you to share your dataset? My dataset is clients, so I can't share.....

**Comment by hamzahmhmmd** [comment] 2020-08-18 02:05
@pycaret I got same error when comparing xgboost model, I think this happens because of the fix_imbalance parameter.
@joaomicunha https://drive.google.com/file/d/1l00mewy1ir54zBo6_jG-25xKurNFvmrW/view?usp=sharing -> dataset
envy = setup(data,
             target = 'default',
             categorical_features=['province'],
             fix_imbalance=True)

**Comment by pycaret** [comment] 2020-09-10 17:34
Great. Closing this issue.

**Closed by pycaret** 2020-09-10 17:34 UTC

**Comment by traveler000** [comment] 2020-12-03 14:54
I came across this mistake "ValueError: feature_names mismatch: " while  use the 'predict_model()', and the data  is pandas DataFrame which was  same as the training. however I can use compare_models() successfully

**Comment by Yard1** [comment] 2020-12-03 15:37
@traveler000 Could you please make a new issue and attach the dataset there?
