### ISSUE TITLE
Unable to show complete models list when training with Pycaret timeseries

### ISSUE THREAD

**Issue by nithinreddyyyy** [pycaret/pycaret#1886] opened 2021-11-24 07:57 UTC
When i'm trying to userpycaret auto timeseries, it's not showing all the models when i'm trying to compare the models.

Below is the image for your reference.
<img width="657" alt="compare" src="https://user-images.githubusercontent.com/75740154/143197356-10e72688-166c-4ead-a19c-13489351c3ee.PNG">

I'm uploading the image of the data also. Please look into it.
<img width="289" alt="data" src="https://user-images.githubusercontent.com/75740154/143197411-be80ce69-ac11-46c9-8890-ab8e074b63ab.PNG">

**Comment by ngupta23** [comment] 2021-11-26 13:26
Sorry, we can not debug using images. We need to know lot more details about this. e.g. How was your experiment setup? Also, check `models()` to see what you get. Do you see all the models? 

**Can you send a minimally reproducible example with code and dataset so it can be debugged further?**

**Comment by nithinreddyyyy** [comment] 2021-11-26 18:14
Sure. Here it is
[data.csv](https://github.com/pycaret/pycaret/files/7610232/data.csv)
https://github.com/nithinreddyyyy/Time-series-with-Pycaret/blob/main/pycaret-ts.ipynb

**Comment by ngupta23** [comment] 2021-11-28 14:14
@nithinreddyyyy It looks like you have very few training data points in the first fold so the other models fail to train. Consider reducing the folds to 3 or alternately, reducing the fh to less than 30 and it should work (I have confirmed that it works with folds = 3).

![image](https://user-images.githubusercontent.com/33585645/143771550-1a42ab56-dbf6-460f-add0-5223a8f81adf.png)

**Comment by ngupta23** [comment] 2021-11-28 14:15
I will close this out but feel free to reopen if you want. Thanks!

**Closed by ngupta23** 2021-11-28 14:15 UTC
Labels: time_series
