### ISSUE TITLE
[BUG]: Can't train with data frequency of 30 minutes

### ISSUE THREAD

**Issue by rantos9** [pycaret/pycaret#2607] opened 2022-05-30 12:33 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

Can't train most models when freq='30T'.

### Reproducible Example

```python
import numpy as np
import pandas as pd
from pycaret.time_series import TSForecastingExperiment

index = pd.date_range(start='2020-10-01 00:00:00', end='2020-10-01 23:30:00', freq='30T')

np.random.seed(5005)

df = pd.DataFrame({
    'index': index,
    'target': np.random.randint(0, 255, index.shape[0], dtype=int),
}).set_index('index')

df

exp = TSForecastingExperiment()

s = exp.setup(
    data=df,
    target='target',
    fh=1,
    fold=3,
    session_id=5005
)

exp.create_model('lr_cds_dt')
```

### Expected Behavior

Model to be trained.

### Actual Results

```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [1], in <cell line: 26>()
     16 exp = TSForecastingExperiment()
     18 s = exp.setup(
     19     data=df,
     20     target='target',
   (...)
     23     session_id=5005
     24 )
---> 26 exp.create_model('lr_cds_dt')

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\pycaret\time_series\forecasting\oop.py:1718, in TSForecastingExperiment.create_model(self, estimator, fold, round, cross_validation, fit_kwargs, experiment_custom_tags, verbose, **kwargs)
   1623 """
   1624 This function trains and evaluates the performance of a given estimator
   1625 using cross validation. The output of this function is a score grid with
   (...)
   1713 
   1714 """
   1716 self._check_setup_ran()
-> 1718 return super().create_model(
   1719     estimator=estimator,
   1720     fold=fold,
   1721     round=round,
   1722     cross_validation=cross_validation,
   1723     fit_kwargs=fit_kwargs,
   1724     experiment_custom_tags=experiment_custom_tags,
   1725     verbose=verbose,
   1726     **kwargs,
   1727 )

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py:1472, in _SupervisedExperiment.create_model(self, estimator, fold, round, cross_validation, predict, fit_kwargs, groups, refit, probability_threshold, experiment_custom_tags, verbose, system, add_to_model_list, X_train_data, y_train_data, metrics, display, **kwargs)
   1469         return model, model_fit_time
   1470     return model
-> 1472 model, model_fit_time, model_results, avgs_dict = self._create_model_with_cv(
   1473     model,
   1474     data_X,
   1475     data_y,
   1476     fit_kwargs,
   1477     round,
   1478     cv,
   1479     groups,
   1480     metrics,
   1481     refit,
   1482     system,
   1483     display,
   1484 )
   1486 # end runtime
   1487 runtime_end = time.time()

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\pycaret\time_series\forecasting\oop.py:1932, in TSForecastingExperiment._create_model_with_cv(self, model, data_X, data_y, fit_kwargs, round, cv, groups, metrics, refit, system, display)
   1930 self.logger.info("Finalizing model")
   1931 with io.capture_output():
-> 1932     pipeline_with_model.fit(y=data_y, X=data_X, **fit_kwargs)
   1933 model_fit_end = time.time()
   1934 model_fit_time = np.array(model_fit_end - model_fit_start).round(2)

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\forecasting\base\_base.py:139, in BaseForecaster.fit(self, y, X, fh)
    134 self._update_y_X(y_inner, X_inner)
    136 # checks and conversions complete, pass to inner fit
    137 #####################################################
--> 139 self._fit(y=y_inner, X=X_inner, fh=fh)
    141 # this should happen last
    142 self._is_fitted = True

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\forecasting\compose\_pipeline.py:245, in ForecastingPipeline._fit(self, y, X, fh)
    243 name, forecaster = self.steps[-1]
    244 f = clone(forecaster)
--> 245 f.fit(y, X, fh)
    246 self.steps_[-1] = (name, f)
    248 return self

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\forecasting\base\_base.py:139, in BaseForecaster.fit(self, y, X, fh)
    134 self._update_y_X(y_inner, X_inner)
    136 # checks and conversions complete, pass to inner fit
    137 #####################################################
--> 139 self._fit(y=y_inner, X=X_inner, fh=fh)
    141 # this should happen last
    142 self._is_fitted = True

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\forecasting\compose\_pipeline.py:396, in TransformedTargetForecaster._fit(self, y, X, fh)
    394 name, forecaster = self.steps[-1]
    395 f = clone(forecaster)
--> 396 f.fit(y, X, fh)
    397 self.steps_[-1] = (name, f)
    398 return self

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\forecasting\base\_base.py:139, in BaseForecaster.fit(self, y, X, fh)
    134 self._update_y_X(y_inner, X_inner)
    136 # checks and conversions complete, pass to inner fit
    137 #####################################################
--> 139 self._fit(y=y_inner, X=X_inner, fh=fh)
    141 # this should happen last
    142 self._is_fitted = True

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\pycaret\containers\models\time_series.py:2558, in BaseCdsDtForecaster._fit(self, y, X, fh)
   2536 def _fit(self, y, X=None, fh=None):
   2537     self._forecaster = TransformedTargetForecaster(
   2538         [
   2539             (
   (...)
   2556         ]
   2557     )
-> 2558     self._forecaster.fit(y=y, X=X, fh=fh)
   2559     self._cutoff = self._forecaster.cutoff
   2561     # this should happen last

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\forecasting\base\_base.py:139, in BaseForecaster.fit(self, y, X, fh)
    134 self._update_y_X(y_inner, X_inner)
    136 # checks and conversions complete, pass to inner fit
    137 #####################################################
--> 139 self._fit(y=y_inner, X=X_inner, fh=fh)
    141 # this should happen last
    142 self._is_fitted = True

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\forecasting\compose\_pipeline.py:390, in TransformedTargetForecaster._fit(self, y, X, fh)
    388 for step_idx, name, transformer in self._iter_transformers():
    389     t = clone(transformer)
--> 390     y = t.fit_transform(y, X)
    391     self.steps_[step_idx] = (name, t)
    393 # fit forecaster

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\transformations\base.py:445, in BaseTransformer.fit_transform(self, X, y, Z)
    442 X = _handle_alias(X, Z)
    443 # Non-optimized default implementation; override when a better
    444 # method is possible for a given algorithm.
--> 445 return self.fit(X, y).transform(X, y)

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\transformations\base.py:242, in BaseTransformer.fit(self, X, y, Z)
    237 X_inner, y_inner = self._convert_X_y(X, y)
    239 # todo: uncomment this once Z is completely gone
    240 # self._fit(X=X_inner, y=y_inner)
    241 # less robust workaround until then
--> 242 self._fit(X_inner, y_inner)
    244 self._is_fitted = True
    245 return self

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\transformations\series\detrend\_detrend.py:108, in Detrender._fit(self, X, y)
    106     forecaster = clone(self.forecaster)
    107     # note: the y in the transformer is exogeneous in the forecaster, i.e., X
--> 108     self.forecaster_ = forecaster.fit(y=X, X=y)
    109 # multivariate
    110 elif isinstance(X, pd.DataFrame):

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\forecasting\base\_base.py:139, in BaseForecaster.fit(self, y, X, fh)
    134 self._update_y_X(y_inner, X_inner)
    136 # checks and conversions complete, pass to inner fit
    137 #####################################################
--> 139 self._fit(y=y_inner, X=X_inner, fh=fh)
    141 # this should happen last
    142 self._is_fitted = True

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\forecasting\trend.py:188, in PolynomialTrendForecaster._fit(self, y, X, fh)
    185 X = np.arange(n_timepoints).reshape(-1, 1)
    187 # fit regressor
--> 188 self.regressor_.fit(X, y)
    189 return self

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\sklearn\pipeline.py:394, in Pipeline.fit(self, X, y, **fit_params)
    392     if self._final_estimator != "passthrough":
    393         fit_params_last_step = fit_params_steps[self.steps[-1][0]]
--> 394         self._final_estimator.fit(Xt, y, **fit_params_last_step)
    396 return self

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\sklearn\linear_model\_base.py:662, in LinearRegression.fit(self, X, y, sample_weight)
    658 n_jobs_ = self.n_jobs
    660 accept_sparse = False if self.positive else ["csr", "csc", "coo"]
--> 662 X, y = self._validate_data(
    663     X, y, accept_sparse=accept_sparse, y_numeric=True, multi_output=True
    664 )
    666 if sample_weight is not None:
    667     sample_weight = _check_sample_weight(sample_weight, X, dtype=X.dtype)

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\sklearn\base.py:581, in BaseEstimator._validate_data(self, X, y, reset, validate_separately, **check_params)
    579         y = check_array(y, **check_y_params)
    580     else:
--> 581         X, y = check_X_y(X, y, **check_params)
    582     out = X, y
    584 if not no_val_X and check_params.get("ensure_2d", True):

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\sklearn\utils\validation.py:981, in check_X_y(X, y, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, multi_output, ensure_min_samples, ensure_min_features, y_numeric, estimator)
    964 X = check_array(
    965     X,
    966     accept_sparse=accept_sparse,
   (...)
    976     estimator=estimator,
    977 )
    979 y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)
--> 981 check_consistent_length(X, y)
    983 return X, y

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\sklearn\utils\validation.py:332, in check_consistent_length(*arrays)
    330 uniques = np.unique(lengths)
    331 if len(uniques) > 1:
--> 332     raise ValueError(
    333         "Found input variables with inconsistent numbers of samples: %r"
    334         % [int(l) for l in lengths]
    335     )

ValueError: Found input variables with inconsistent numbers of samples: [1381, 47]
```

### Installed Versions

<details>
System:
    python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\Renan\anaconda3\envs\pycaret-ts\python.exe
   machine: Windows-10-10.0.19044-SP0

Python dependencies:
          pip: 21.2.2
   setuptools: 61.2.0
      pycaret: 3.0.0
      sklearn: 1.0.2
       sktime: 0.10.1
  statsmodels: 0.13.2
        numpy: 1.21.6
        scipy: 1.7.3
       pandas: 1.4.2
   matplotlib: 3.5.1
       plotly: 5.6.0
       joblib: 1.0.1
        numba: 0.55.1
       mlflow: Not installed
     lightgbm: 3.3.2
      xgboost: Not installed
     pmdarima: 1.8.5
        tbats: Installed but version unavailable
      prophet: Not installed
      tsfresh: Not installed
</details>

**Comment by ngupta23** [comment] 2022-05-30 15:33
@rantos9 Thanks for reporting and providing a reproducible example. This does not work on the develop branch either although with a different error message. https://gist.github.com/ngupta23/40d0fd8ed90b0544f7e90438c1e921ad

I will need to look into this and get back to you.

**Comment by ngupta23** [comment] 2022-05-31 00:35
This seems to be coming from our base library sktime. I have reported it in their repo. Will wait for their response to close this out.

https://github.com/alan-turing-institute/sktime/issues/2724

**Comment by ngupta23** [comment] 2022-07-01 06:31
Update:

- This does not work in sktime 0.11.4 (https://gist.github.com/ngupta23/c502c32f2faa4dc7b68d8719ad2ae8dd)
- But it works in sktime 0.12.1 now (https://gist.github.com/ngupta23/a2aeca813d6d651c20dc17e56625dcbb)

However, we can not update pycaret to use sktime 0.12.1 just yet due to this (https://github.com/pycaret/pycaret/issues/2674). Once this issue is resolved, we can close this issue.

**Closed** 2022-07-25 14:53 UTC
Labels: bug, time_series, priority_medium
