### ISSUE TITLE
ValueError: at least one array or dtype is required during classification

### ISSUE THREAD

**Issue by ajatau** [pycaret/pycaret#245] opened 2020-06-25 16:22 UTC
I have a data with 97 columns and I cant seem to get a multi class classification to work.

Heres a sample of the data `

str0 | str1 | str2 | str3 | str4 | str5 | str6 | str7 | str8 | str9 | str10 | str11 | str12 | str13 | str14 | str15 | str16 | str17 | str18 | str19 | str20 | str21 | str22 | str23 | str24 | str25 | str26 | str27 | str28 | str29 | str30 | str31 | str32 | str33 | str34 | str35 | str36 | str37 | str38 | str39 | ... | str58 | str59 | str60 | str61 | str62 | str63 | str64 | str65 | str66 | str67 | str68 | str69 | str70 | str71 | str72 | str73 | str74 | str75 | str76 | str77 | str78 | str79 | str80 | str81 | str82 | str83 | str84 | str85 | str86 | str87 | str88 | str89 | str90 | str91 | str92 | str93 | str94 | str95 | str96 | label
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
8666.89 | 8667.17 | 8668.44 | 8669.02 | 8669.99 | 8668.19 | 8666.94 | 8663.20 | 8667.55 | 8667.11 | 8667.16 | 8665.00 | 8666.18 | 8667.10 | 8666.50 | 8666.81 | 8666.90 | 8666.65 | 8667.17 | 8666.91 | 8666.99 | 8667.66 | 8662.75 | 8662.00 | 8661.94 | 8663.74 | 8661.50 | 8660.55 | 8660.02 | 8660.58 | 8661.00 | 8661.02 | 8661.76 | 8658.79 | 8658.49 | 8659.41 | 8659.81 | 8660.76 | 8662.74 | 8668.03 | ... | 8667.65 | 8664.06 | 8663.99 | 8664.14 | 8664.97 | 8664.74 | 8663.82 | 8663.83 | 8662.59 | 8663.00 | 8663.36 | 8660.10 | 8660.00 | 8661.01 | 8661.60 | 8661.16 | 8662.03 | 8660.97 | 8659.57 | 8657.43 | 8656.80 | 8655.24 | 8654.10 | 8653.23 | 8648.62 | 8655.40 | 8660.88 | 8658.35 | 8658.80 | 8657.97 | 8658.02 | 8658.77 | 8657.32 | 8656.90 | 8656.26 | 8652.25 | 8652.21 | 8654.37 | 8654.37 | 0
7149.99 | 7149.99 | 7149.99 | 7149.98 | 7149.85 | 7149.85 | 7149.85 | 7140.03 | 7141.98 | 7149.93 | 7140.01 | 7140.02 | 7140.00 | 7121.04 | 7135.03 | 7135.02 | 7122.22 | 7129.03 | 7129.05 | 7116.86 | 7116.86 | 7116.86 | 7116.86 | 7116.21 | 7135.47 | 7135.47 | 7141.29 | 7138.48 | 7138.48 | 7135.47 | 7135.47 | 7141.19 | 7141.21 | 7141.19 | 7141.19 | 7141.19 | 7138.66 | 7137.96 | 7116.21 | 7116.21 | ... | 7085.00 | 7085.00 | 7085.01 | 7100.00 | 7101.00 | 7085.02 | 7101.00 | 7101.23 | 7128.00 | 7128.01 | 7091.01 | 7127.93 | 7127.93 | 7127.93 | 7080.00 | 7116.96 | 7116.89 | 7116.89 | 7116.89 | 7080.01 | 7080.01 | 7115.97 | 7095.01 | 7115.00 | 7115.00 | 7080.13 | 7115.00 | 7085.00 | 7100.01 | 7080.14 | 7100.01 | 7100.01 | 7100.01 | 7100.00 | 7080.18 | 7080.18 | 7080.23 | 7095.00 | 7095.00 | 0
4568.59 | 4577.00 | 4576.26 | 4575.08 | 4577.89 | 4582.00 | 4581.92 | 4583.18 | 4586.47 | 4581.76 | 4584.41 | 4584.99 | 4581.22 | 4577.49 | 4574.15 | 4563.57 | 4568.04 | 4571.88 | 4577.75 | 4579.47 | 4572.05 | 4576.73 | 4579.28 | 4576.47 | 4581.18 | 4588.21 | 4595.00 | 4591.17 | 4590.00 | 4582.18 | 4584.60 | 4590.98 | 4591.43 | 4593.65 | 4593.12 | 4591.52 | 4591.52 | 4584.55 | 4594.01 | 4597.00 | ... | 4579.43 | 4579.91 | 4580.20 | 4577.98 | 4581.01 | 4581.80 | 4583.38 | 4581.69 | 4588.64 | 4587.03 | 4583.63 | 4584.03 | 4584.93 | 4584.85 | 4583.13 | 4576.90 | 4574.68 | 4577.63 | 4572.92 | 4571.41 | 4565.99 | 4563.12 | 4563.18 | 4560.84 | 4543.00 | 4546.00 | 4548.00 | 4547.01 | 4539.21 | 4540.74 | 4524.78 | 4528.17 | 4530.00 | 4543.41 | 4536.01 | 4543.50 | 4544.63 | 4538.09 | 4538.50 | 1
11825.67 | 11819.08 | 11822.95 | 11820.47 | 11806.75 | 11793.46 | 11799.07 | 11813.74 | 11816.46 | 11815.96 | 11835.25 | 11833.33 | 11819.25 | 11801.60 | 11797.73 | 11781.88 | 11774.68 | 11772.16 | 11767.85 | 11784.93 | 11796.88 | 11783.81 | 11771.50 | 11777.25 | 11797.04 | 11782.29 | 11771.38 | 11781.83 | 11778.16 | 11795.58 | 11813.87 | 11810.78 | 11803.99 | 11805.07 | 11789.96 | 11788.76 | 11796.97 | 11806.94 | 11802.07 | 11805.57 | ... | 11761.90 | 11759.61 | 11756.58 | 11764.90 | 11757.96 | 11740.83 | 11733.66 | 11749.62 | 11736.75 | 11733.44 | 11730.00 | 11730.00 | 11730.42 | 11739.99 | 11737.03 | 11736.79 | 11745.97 | 11735.39 | 11735.17 | 11711.04 | 11710.89 | 11704.66 | 11725.01 | 11729.24 | 11734.77 | 11746.51 | 11755.88 | 11753.59 | 11733.14 | 11742.42 | 11752.62 | 11769.85 | 11774.65 | 11773.01 | 11777.99 | 11789.87 | 11788.03 | 11781.00 | 11787.04 | 0
6379.00 | 6379.00 | 6378.99 | 6391.99 | 6391.99 | 6390.00
`

 `from pycaret.classification import *`

`clf1 = setup(data = result, target = 'label')`

and I am getting this error 

`ValueError: at least one array or dtype is required`

```
ValueError                                Traceback (most recent call last)
<ipython-input-79-232f1b87375b> in <module>
      1 from pycaret.classification import *
----> 2 clf1 = setup(data = normalized_df_1, target = 'label', train_size = 0.9)

~/opt/anaconda3/lib/python3.7/site-packages/pycaret/classification.py in setup(data, target, train_size, sampling, sample_estimator, categorical_features, categorical_imputation, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_interaction, feature_ratio, interaction_threshold, session_id, silent, profile)
   1133             X_, X__, y_, y__ = train_test_split(X, y, test_size=1-i, stratify=y, random_state=seed)
   1134             X_train, X_test, y_train, y_test = train_test_split(X_, y_, test_size=0.3, stratify=y_, random_state=seed)
-> 1135             model.fit(X_train,y_train)
   1136             pred_ = model.predict(X_test)
   1137             try:

~/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py in fit(self, X, y, sample_weight)
   1523     Cs : int or list of floats, default=10
   1524         Each of the values in Cs describes the inverse of regularization
-> 1525         strength. If Cs is as an int, then a grid of Cs values are chosen
   1526         in a logarithmic scale between 1e-4 and 1e4.
   1527         Like in support vector machines, smaller values specify stronger

~/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py in check_X_y(X, y, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, multi_output, ensure_min_samples, ensure_min_features, y_numeric, warn_on_dtype, estimator)
    737         be triggered by a conversion.
    738 
--> 739     force_all_finite : boolean or 'allow-nan', (default=True)
    740         Whether to raise an error on np.inf, np.nan, pd.NA in X. This parameter
    741         does not influence whether y can have np.inf, np.nan, pd.NA values.

~/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, warn_on_dtype, estimator)
    457 
    458         .. versionchanged:: 0.23
--> 459            Accepts `pd.NA` and converts it into `np.nan`
    460 
    461     ensure_2d : boolean (default=True)

<__array_function__ internals> in result_type(*args, **kwargs)

ValueError: at least one array or dtype is required
```

**Comment by pycaret** [comment] 2020-06-25 17:44
@ajatau Thanks for reporting. Can you share the same dataset?

**Comment by ajatau** [comment] 2020-06-25 18:04
https://github.com/trality-bots/wizard-challenge/blob/master/data/train_input.txt

**Comment by pycaret** [comment] 2020-06-26 04:54
@ajatau Hi.. I have investigated this. It turns out that there is an internal functionality in **preprocess.py** that removes all the X features that are 100% or approximately 100% correlated. It turns out in this example all the 97 features are 99.9% correlated so a process in preprocess.py file gets executed when you run setup() and that process removes all the columns in X feature set. I was able to figure that out by subsetting the data. 

At this point there is no way you can switch off that functionality. However if you would like a immediate fix you can search for remove_perfect_collinarity parameter within setup function of classification.py and set that to False from True. That should fix your problem.

Please let me know if that helps.

Thanks.

**Comment by pycaret** [comment] 2020-06-26 04:55
I am also tagging this issue as an enhancement so that we can expose the **remove_perfect_multicollinearity** parameter within **setup()** in next release. It seems like there will be cases like this where it will be useful.

**Comment by ajatau** [comment] 2020-06-26 05:30
Hi that worked I guess but I am running into a new error on the same dataset

`ValueError: DataFrame constructor not properly called!`

**Comment by pycaret** [comment] 2020-07-06 18:17
@ajatau This issue has been fixed in pycaret-nightly build. Can you please install **pycaret-nightly** using pip and let me know if the issue is gone. If not, the source code is on dev-1.0.1 branch.

**Closed** 2020-07-30 21:44 UTC
Labels: available-in-pycaret-nightly, enhancement

**Comment by nkalhan** [comment] 2020-08-02 17:33
Hi, I have the same error now: I used the below code:
(Downloaded the new Pycaret 2.0 as well)

from pycaret.regression import *
reg1 = setup(data, target='Division', high_cardinality_features=['Account Name'] , high_cardinality_method='clustering', remove_multicollinearity=True , session_id=123)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-41060b6a998e> in <module>
      1 from pycaret.regression import *
----> 2 reg1 = setup(data, target='Division', high_cardinality_features=['Account Name'] , high_cardinality_method='clustering', remove_multicollinearity=True , session_id=123)

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\pycaret\regression.py in setup(data, target, train_size, sampling, sample_estimator, categorical_features, categorical_imputation, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_interaction, feature_ratio, interaction_threshold, transform_target, transform_target_method, data_split_shuffle, folds_shuffle, n_jobs, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile)
   1215                                           target_transformation = transform_target,
   1216                                           target_transformation_method = transform_target_method_pass,
-> 1217                                           random_state = seed)
   1218 
   1219     progress.value += 1

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\pycaret\preprocess.py in Preprocess_Path_One(train_data, target_variable, ml_usecase, test_data, categorical_features, numerical_features, time_features, features_todrop, display_types, imputation_type, numeric_imputation_strategy, categorical_imputation_strategy, apply_zero_nearZero_variance, club_rare_levels, rara_level_threshold_percentage, apply_untrained_levels_treatment, untrained_levels_treatment_method, apply_ordinal_encoding, ordinal_columns_and_categories, apply_cardinality_reduction, cardinal_method, cardinal_features, apply_binning, features_to_binn, apply_grouping, group_name, features_to_group_ListofList, apply_polynomial_trigonometry_features, max_polynomial, trigonometry_calculations, top_poly_trig_features_to_select_percentage, scale_data, scaling_method, Power_transform_data, Power_transform_method, target_transformation, target_transformation_method, remove_outliers, outlier_contamination_percentage, outlier_methods, apply_feature_selection, feature_selection_top_features_percentage, remove_multicollinearity, maximum_correlation_between_features, remove_perfect_collinearity, apply_feature_interactions, feature_interactions_to_apply, feature_interactions_top_features_to_select_percentage, cluster_entire_data, range_of_clusters_to_try, apply_pca, pca_method, pca_variance_retained_or_number_of_components, random_state)
   2563     return(pipe.fit_transform(train_data),pipe.transform(test_data))
   2564   else:
-> 2565     return(pipe.fit_transform(train_data))
   2566 
   2567 

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\pipeline.py in fit_transform(self, X, y, **fit_params)
    365         """
    366         fit_params_steps = self._check_fit_params(**fit_params)
--> 367         Xt = self._fit(X, y, **fit_params_steps)
    368 
    369         last_step = self._final_estimator

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\pipeline.py in _fit(self, X, y, **fit_params_steps)
    294                 message_clsname='Pipeline',
    295                 message=self._log_message(step_idx),
--> 296                 **fit_params_steps[name])
    297             # Replace the transformer of the step with the fitted
    298             # transformer. This is necessary when loading the transformer

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\joblib\memory.py in __call__(self, *args, **kwargs)
    350 
    351     def __call__(self, *args, **kwargs):
--> 352         return self.func(*args, **kwargs)
    353 
    354     def call_and_shelve(self, *args, **kwargs):

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\pipeline.py in _fit_transform_one(transformer, X, y, weight, message_clsname, message, **fit_params)
    738     with _print_elapsed_time(message_clsname, message):
    739         if hasattr(transformer, 'fit_transform'):
--> 740             res = transformer.fit_transform(X, y, **fit_params)
    741         else:
    742             res = transformer.fit(X, y, **fit_params).transform(X)

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\pycaret\preprocess.py in fit_transform(self, dataset, y)
   1405     # now make PLS
   1406     self.pls = PLSRegression(n_components=2) # since we are only using two componenets to group #PLSRegression(n_components=len(data_t1.columns)-1)
-> 1407     data_pls = self.pls.fit_transform(data_t.drop(self.target,axis=1),data_t[self.target])[0]
   1408 
   1409     # # now we will take one component and then we calculate mean, median, min, max and sd of that one component grouped by the catagorical levels

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\cross_decomposition\_pls.py in fit_transform(self, X, y)
    517         x_scores if Y is not given, (x_scores, y_scores) otherwise.
    518         """
--> 519         return self.fit(X, y).transform(X, y)
    520 
    521     def _more_tags(self):

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\cross_decomposition\_pls.py in fit(self, X, Y)
    281         check_consistent_length(X, Y)
    282         X = self._validate_data(X, dtype=np.float64, copy=self.copy,
--> 283                                 ensure_min_samples=2)
    284         Y = check_array(Y, dtype=np.float64, copy=self.copy, ensure_2d=False)
    285         if Y.ndim == 1:

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\base.py in _validate_data(self, X, y, reset, validate_separately, **check_params)
    418                     f"requires y to be passed, but the target y is None."
    419                 )
--> 420             X = check_array(X, **check_params)
    421             out = X
    422         else:

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     71                           FutureWarning)
     72         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 73         return f(**kwargs)
     74     return inner_f
     75 

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    532 
    533         if all(isinstance(dtype, np.dtype) for dtype in dtypes_orig):
--> 534             dtype_orig = np.result_type(*dtypes_orig)
    535 
    536     if dtype_numeric:

<__array_function__ internals> in result_type(*args, **kwargs)

ValueError: at least one array or dtype is required

**Comment by nkalhan** [comment] 2020-08-02 17:35
Hi, I have the same error now: I used the below code:
(Downloaded the new Pycaret 2.0 as well.)

from pycaret.regression import *
reg1 = setup(data, target='Division', high_cardinality_features=['Account Name'] , high_cardinality_method='clustering', remove_multicollinearity=True , session_id=123)

ValueError Traceback (most recent call last)
in
1 from pycaret.regression import *
----> 2 reg1 = setup(data, target='Division', high_cardinality_features=['Account Name'] , high_cardinality_method='clustering', remove_multicollinearity=True , session_id=123)

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\pycaret\regression.py in setup(data, target, train_size, sampling, sample_estimator, categorical_features, categorical_imputation, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_interaction, feature_ratio, interaction_threshold, transform_target, transform_target_method, data_split_shuffle, folds_shuffle, n_jobs, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile)
1215 target_transformation = transform_target,
1216 target_transformation_method = transform_target_method_pass,
-> 1217 random_state = seed)
1218
1219 progress.value += 1

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\pycaret\preprocess.py in Preprocess_Path_One(train_data, target_variable, ml_usecase, test_data, categorical_features, numerical_features, time_features, features_todrop, display_types, imputation_type, numeric_imputation_strategy, categorical_imputation_strategy, apply_zero_nearZero_variance, club_rare_levels, rara_level_threshold_percentage, apply_untrained_levels_treatment, untrained_levels_treatment_method, apply_ordinal_encoding, ordinal_columns_and_categories, apply_cardinality_reduction, cardinal_method, cardinal_features, apply_binning, features_to_binn, apply_grouping, group_name, features_to_group_ListofList, apply_polynomial_trigonometry_features, max_polynomial, trigonometry_calculations, top_poly_trig_features_to_select_percentage, scale_data, scaling_method, Power_transform_data, Power_transform_method, target_transformation, target_transformation_method, remove_outliers, outlier_contamination_percentage, outlier_methods, apply_feature_selection, feature_selection_top_features_percentage, remove_multicollinearity, maximum_correlation_between_features, remove_perfect_collinearity, apply_feature_interactions, feature_interactions_to_apply, feature_interactions_top_features_to_select_percentage, cluster_entire_data, range_of_clusters_to_try, apply_pca, pca_method, pca_variance_retained_or_number_of_components, random_state)
2563 return(pipe.fit_transform(train_data),pipe.transform(test_data))
2564 else:
-> 2565 return(pipe.fit_transform(train_data))
2566
2567

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\pipeline.py in fit_transform(self, X, y, **fit_params)
365 """
366 fit_params_steps = self._check_fit_params(**fit_params)
--> 367 Xt = self._fit(X, y, **fit_params_steps)
368
369 last_step = self._final_estimator

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\pipeline.py in _fit(self, X, y, **fit_params_steps)
294 message_clsname='Pipeline',
295 message=self._log_message(step_idx),
--> 296 **fit_params_steps[name])
297 # Replace the transformer of the step with the fitted
298 # transformer. This is necessary when loading the transformer

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\joblib\memory.py in call(self, *args, **kwargs)
350
351 def call(self, *args, **kwargs):
--> 352 return self.func(*args, **kwargs)
353
354 def call_and_shelve(self, *args, **kwargs):

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\pipeline.py in _fit_transform_one(transformer, X, y, weight, message_clsname, message, **fit_params)
738 with _print_elapsed_time(message_clsname, message):
739 if hasattr(transformer, 'fit_transform'):
--> 740 res = transformer.fit_transform(X, y, **fit_params)
741 else:
742 res = transformer.fit(X, y, **fit_params).transform(X)

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\pycaret\preprocess.py in fit_transform(self, dataset, y)
1405 # now make PLS
1406 self.pls = PLSRegression(n_components=2) # since we are only using two componenets to group #PLSRegression(n_components=len(data_t1.columns)-1)
-> 1407 data_pls = self.pls.fit_transform(data_t.drop(self.target,axis=1),data_t[self.target])[0]
1408
1409 # # now we will take one component and then we calculate mean, median, min, max and sd of that one component grouped by the catagorical levels

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\cross_decomposition_pls.py in fit_transform(self, X, y)
517 x_scores if Y is not given, (x_scores, y_scores) otherwise.
518 """
--> 519 return self.fit(X, y).transform(X, y)
520
521 def _more_tags(self):

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\cross_decomposition_pls.py in fit(self, X, Y)
281 check_consistent_length(X, Y)
282 X = self._validate_data(X, dtype=np.float64, copy=self.copy,
--> 283 ensure_min_samples=2)
284 Y = check_array(Y, dtype=np.float64, copy=self.copy, ensure_2d=False)
285 if Y.ndim == 1:

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\base.py in _validate_data(self, X, y, reset, validate_separately, **check_params)
418 f"requires y to be passed, but the target y is None."
419 )
--> 420 X = check_array(X, **check_params)
421 out = X
422 else:

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
71 FutureWarning)
72 kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 73 return f(**kwargs)
74 return inner_f
75

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
532
533 if all(isinstance(dtype, np.dtype) for dtype in dtypes_orig):
--> 534 dtype_orig = np.result_type(*dtypes_orig)
535
536 if dtype_numeric:

<array_function internals> in result_type(*args, **kwargs)

ValueError: at least one array or dtype is required
