### ISSUE TITLE
AUC Plot, minor error. Please check.

### ISSUE THREAD

**Issue by Leo-Ji2020** [pycaret/pycaret#996] opened 2021-01-13 09:24 UTC
**Is your feature request related to a problem? Please describe.**
The section 10.1 in "Binary Classification Tutorial Level Beginner -  CLF101" shows the AUC curves. However, the same line style was used for both **_micro-average_** & **_macro-average_** ROC curves. Please modify it in the next version. Thank you.

<img width="393" alt="10 1AUC" src="https://user-images.githubusercontent.com/62948124/104432523-12a9c900-55c4-11eb-8a95-8cb539a3cb2c.png">

**Comment by pycaret** [comment] 2021-01-16 15:09
@Leo-Ji2020 Thanks for reporting. It seems like this is caused by the dependency we are using for the plots.

I will appreciate it if you can report the issue on their repo.

https://www.scikit-yb.org/en/latest/

**Comment by ngupta23** [comment] 2021-05-05 13:17
Hi @Leo-Ji2020 , we will close this out, but feel free to reopen it or open another issue if needed. Thanks!

**Closed by ngupta23** 2021-05-05 13:17 UTC
Labels: classification, no-issue-activity
