### ISSUE TITLE
Error message while displaying the result-dataframe? 

### ISSUE THREAD

**Issue by saruarlive** [pycaret/pycaret#2654] opened 2022-06-12 20:24 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

Could you say a bit more regarding the error shown below

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/24542592/173252093-79891dfa-b4e9-4516-8339-65889ffdafc1.png">

### Reproducible Example

```python
-!
```

### Expected Behavior

-!-

### Actual Results

```python-traceback
--------!
```

### Installed Versions

PyCaret 2.3.10

**Comment by ngupta23** [comment] 2022-06-13 13:57
I am sorry, but your "reproducible" example is not helpful. In general `compare_models` does not have an issue so this is specific to the code and data you have used before you call `compare_models` and hence we would need that to debug.

Can you provide the complete reproducible example so we can debug this further? Thanks!

**Comment by moezali1** [comment] 2022-06-21 23:24
@saruarlive Hi. Can you please provide more information so we can resolve the issue?

**Comment by ngupta23** [comment] 2022-07-01 06:16
We will close this for now due to a lack of information (reproducible example). Feel free to add details and reopen it. Thanks!

**Closed by ngupta23** 2022-07-01 06:16 UTC
Labels: invalid, missing_info
