### ISSUE TITLE
load_model is failing when loading model back from aws

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#1172] opened 2021-04-15 21:48 UTC
I have trained and pushed a model on AWS using the `deploy_model` function but when loading the model back from `load_model` I get the error.

```
from pycaret.classification import load_model, predict_model
l = load_model('dsc123', platform = 'aws', authentication = {'bucket' : 'XXX'})
```

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-6-64ada9a45af4> in <module>
      1 from pycaret.classification import load_model, predict_model
----> 2 l = load_model('dsc123', platform = 'aws', authentication = {'bucket' : 'pycaret-test'})
      3 predict_model(l, data=data)

~\Anaconda3\lib\site-packages\pycaret\classification.py in load_model(model_name, platform, authentication, verbose)
   2161         platform=platform,
   2162         authentication=authentication,
-> 2163         verbose=verbose,
   2164     )
   2165 

~\Anaconda3\lib\site-packages\pycaret\internal\tabular.py in load_model(model_name, platform, authentication, verbose)
   9013 
   9014     return pycaret.internal.persistence.load_model(
-> 9015         model_name, platform, authentication, verbose
   9016     )
   9017 

~\Anaconda3\lib\site-packages\pycaret\internal\persistence.py in load_model(model_name, platform, authentication, verbose)
    391             s3.Bucket(bucketname).download_file(key, filename)
    392 
--> 393         model = load_model(filename, verbose=False)
    394 
    395         if verbose:

~\Anaconda3\lib\site-packages\pycaret\internal\persistence.py in load_model(model_name, platform, authentication, verbose)
    371         if verbose:
    372             print("Transformation Pipeline and Model Successfully Loaded")
--> 373         return joblib.load(model_name)
    374 
    375     # cloud providers

~\Anaconda3\lib\site-packages\joblib\numpy_pickle.py in load(filename, mmap_mode)
    575             obj = _unpickle(fobj)
    576     else:
--> 577         with open(filename, 'rb') as f:
    578             with _read_fileobject(f, filename, mmap_mode) as fobj:
    579                 if isinstance(fobj, str):

**FileNotFoundError: [Errno 2] No such file or directory: 'dsc123.pkl.pkl'**

For some reasons `.pkl` is assumed twice at the end of the name. The problem is in the `load_model` function so must be fixed somewhere in pycaret/persistence.py.

**Comment by moezali1** [comment] 2021-04-15 21:49
@Yard1 @amjadraza Any thoughts?

Also, I am not sure but maybe it's also causing the issue for platform = 'azure' and 'gcp' as well.

**Comment by Yard1** [comment] 2021-04-16 13:23
We are automatically adding pkl to the file names but I think we should not be doing that. This will be a breaking change, however.

**Comment by amjadraza** [comment] 2021-04-16 14:36
It depends on how to model is being saved on AWS

```
model_name_to_save = test_model_aws

model_name_to_load = test_model_aws

```

I suspect that when saving `mode_name` has `.pkl` at the end and when loading `model_name` was not included `.pkl` at the end. 

This is not a bug but an adopted logic at the time of implementation however can be changed in upcoming versions.

**Comment by amjadraza** [comment] 2021-04-16 16:04
@Yard1 and @moezali1, This is a Bug and can be fixed easily. I have just tested it.

The issue looks like in our `save_model` function where `model_name` has been modified. To fix this I have to set it up a proper test. 

@Yard1, you may try debugging meanwhile...

@moezali1 , you can assign this issue to me. I will fix it.

**Comment by Yard1** [comment] 2021-04-16 20:07
Yeah it's due to inconsistent adding of `.pkl`. I think that it'd be best if we were not adding it anywhere (`load_model`/`save_model`). A PR would be appreciated!

**Comment by moezali1** [comment] 2021-04-27 13:16
@amjadraza @Yard1 Is this issue fixed already? I don't face the issue anymore when I am using the `master` branch.

**Comment by Yard1** [comment] 2021-04-27 13:20
There was a temporary fix by @markgrujic but we'll just remove the `.pkl` suffix for the next major release

**Closed** 2021-05-06 11:19 UTC
Labels: bug
