### ISSUE TITLE
[BUG]: create_api errors!

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#2803] opened 2022-07-26 22:30 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

try create api and receive error IndentationError: unexpected indent

### Reproducible Example

```python
create_api(final_model, 'final_model_api')
!python final_model_api.py
```

### Expected Behavior

no errors

### Actual Results

```python-traceback
File "C:\...\final_model_api.py", line 2
    import pandas as pd
IndentationError: unexpected indent
```

### Installed Versions

<details>
pycaret 3 rc3
</details>

**Comment by celestinoxp** [comment] 2022-07-26 22:48
After edit file final_model_api.py and run notebook cell to run file, i receive new error: Traceback (most recent call last):
  File "C:\...\final_model_api.py", line 3, in <module>
    from pycaret.MLUsecase.CLASSIFICATION import load_model, predict_model
ModuleNotFoundError: No module named 'pycaret.MLUsecase'

**Comment by celestinoxp** [comment] 2022-07-28 15:03
@ngupta23 create_api maybe work on pycaret 2.3.x, however pycaret code as changed but create_api command needs changes too. Can you have a look on that?

**Comment by celestinoxp** [comment] 2022-07-29 08:58
I tried to test the create_app command and it also doesn't work in pycaret 3. It doesn't assume the features that pycaret itself created, like the year, month, day extracted from date_time feature...

**Comment by ngupta23** [comment] 2022-08-15 10:33
Reproduced in August 15th meeting. Fix needed in these 2 places

- Indent
- correct import per latest library structure

![image](https://user-images.githubusercontent.com/33585645/184620403-b4ad8e7b-0f61-44e1-aafa-9186103e230a.png)

**Comment by celestinoxp** [comment] 2022-08-15 10:38
Reproduced in August 15th meeting...where is the meeting? Live on Youtube?

**Comment by ngupta23** [comment] 2022-08-15 11:00
> Reproduced in August 15th meeting...where is the meeting? Live on Youtube?

The core developers try to meet once a week to discuss next steps, etc.

**Comment by ngupta23** [comment] 2022-08-29 10:30
Per August 29th meeting, reassigned to @tvdboom.

**Comment by tvdboom** [comment] 2022-08-31 08:17
I fixed this error but my app is not launching correctly. @moezali1 can you try using the [change_engine_param_name](https://github.com/pycaret/pycaret/tree/change_engine_param_name) repo? Not sure what the error is now

**Comment by moezali1** [comment] 2022-09-06 21:01
@tvdboom Just did. The exact same error.

![image](https://user-images.githubusercontent.com/54699234/188737302-a7de6c11-f783-4d83-9530-8abd11c3504a.png)

**Comment by tvdboom** [comment] 2022-09-07 06:33
@moezali1 That can't be because that code is no longer there. Are you using the [change_engine_param_name](https://github.com/pycaret/pycaret/tree/change_engine_param_name) repo?

**Closed** 2022-09-14 13:46 UTC
Labels: bug, priority_high, create_api
