### ISSUE TITLE
[BUG]: Jupyter-Lab - evaluate_model(best) Issue?

### ISSUE THREAD

**Issue by msdumanlc** [pycaret/pycaret#2825] opened 2022-08-04 17:21 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Downloaded lastest version of jupyter-lab notebook.  Basically copied an example script from CoLab.  Everything runs fine except on line:  evaluate_model(best).  

### Reproducible Example

```python
!pip install --pre pycaret
from pycaret.datasets import get_data
data = get_data('juice')
from pycaret.classification import *
s = setup(data, target = 'Purchase')
best = compare_models()
plot_model(best)
evaluate_model(best)
```

### Expected Behavior

evaluate model(best) should return a results to pick different plots.

### Actual Results

```python-traceback
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'VBoxModel' from module '@jupyter-widgets/controls'
Error: Module @jupyter-widgets/controls, version ^1.5.0 is not registered, however,         2.0.0 is
    at f.loadClass (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.f391daa337629accea43.js?v=f391daa337629accea43:1:75008)
    at f.loadModelClass (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.5d96364f7e4f19c4dfdb.js?v=5d96364f7e4f19c4dfdb:1:10655)
    at f._make_model (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.5d96364f7e4f19c4dfdb.js?v=5d96364f7e4f19c4dfdb:1:7451)
    at f.new_model (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.5d96364f7e4f19c4dfdb.js?v=5d96364f7e4f19c4dfdb:1:5137)
    at f.handle_comm_open (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.5d96364f7e4f19c4dfdb.js?v=5d96364f7e4f19c4dfdb:1:3894)
    at _handleCommOpen (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.f391daa337629accea43.js?v=f391daa337629accea43:1:73424)
    at b._handleCommOpen (http://localhost:8888/static/lab/jlab_core.081dc2b13065c79d8463.js?v=081dc2b13065c79d8463:2:994257)
    at async b._handleMessage (http://localhost:8888/static/lab/jlab_core.081dc2b13065c79d8463.js?v=081dc2b13065c79d8463:2:996247)
![image](https://user-images.githubusercontent.com/109091381/182910399-0f89a094-8f4a-41c1-975b-739e728a421b.png)
```

### Installed Versions

<details>
from pycaret import show_versions; show_versions()
System:
    python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
executable: c:\users\mduman\.pyenv\pyenv-win\versions\3.7.4\python.exe
   machine: Windows-10-10.0.19041-SP0

PyCaret required dependencies:
                 pip: 22.2.2
          setuptools: 40.8.0
             pycaret: 3.0.0.rc3
             IPython: 7.34.0
          ipywidgets: 7.7.1
                tqdm: 4.64.0
               numpy: 1.21.6
              pandas: 1.3.5
              jinja2: 3.1.2
               scipy: 1.7.3
              joblib: 1.1.0
             sklearn: 1.0.2
                pyod: Installed but version unavailable
            imblearn: 0.9.0
   category_encoders: 2.5.0
            lightgbm: 3.3.2
               numba: 0.55.2
            requests: 2.28.1
          matplotlib: 3.5.2
          scikitplot: 0.3.7
         yellowbrick: 1.4
              plotly: 5.9.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.11.4
               tbats: Installed but version unavailable
            pmdarima: 1.8.5
              psutil: 5.9.1
</details>

**Comment by celestinoxp** [comment] 2022-08-17 08:09
Hi @msdumanlc,

It looks as though you have the newest labextension, however i think the problem is from python 3.7.

Try create new environment with python 3.8 or python 3.9, and install packages jupyterlab, pycaret....

If works you can close this issue.

**Comment by msdumanlc** [comment] 2022-08-18 19:10
Resolved

**Closed** 2022-11-05 13:00 UTC
Labels: bug, evaluate_model
