### ISSUE TITLE
Is there any way to get the top keywords as a separate columns while assigning LDA for topic modelling

### ISSUE THREAD

**Issue by sathishkumar999** [pycaret/pycaret#274] opened 2020-07-09 13:29 UTC
Hi Pycaret team!

could you please add one more column, which is top_keywords in topic modelling while assigning LDA.

lda = create_model(model='lda', num_topics=6, top_keywords=10, multi_core = True)

I'm expecting the above syntax with number of top_keywords as a new column.

below figure is the Actual result of pycaret.

![Screenshot (270)](https://user-images.githubusercontent.com/40235632/87045699-cd23d200-c215-11ea-809a-0158b1e79b86.png)

I'm Expecting result,which is showing in the below figure. here I mapped keywords manually for top_keywords column.
if I have less than 5 or 10 topics,I can map it manually. but If I have more than 100 topics, it would be difficult to map them.

![Screenshot (269)](https://user-images.githubusercontent.com/40235632/87045992-30adff80-c216-11ea-9b7f-71eae1041f2b.png)

**Comment by pycaret** [comment] 2020-07-09 16:50
@sathishkumar369 

Hi Sathish, It wouldn't be a good to add key words in column to original dataset. There would be a lot of repetition. If dataframe has 10000 cols with 5 topics. You should build a df with 5 rows and 2 cols (each row for a topic and key word in col) instead of repeating it throughout the dataframe.

Let me know what you think.

**Comment by sathishkumar369** [comment] 2020-07-10 03:18
Yes, Moez! I got your point. It wouldn't be good to add keywords as a column, there will be a lot of repetition through out the data frame.if we give only 5 topics.

We have come up with a solution for that, actually we have 11thousand documents(rows). We apply clustering on this . So we got 138 clusters.
Then we group the documents based on the cluster.finally we got only 138 documents.
On this 138 documents we did text preprocessing and topic modeling with 138 topics. We got 99% matched keywords in each topic in manual analysis.
But the problem is we need a separate column with top_10 keywords for each topic. Instead of visualizing the keywords in each topic by using plots. Becz you know the end-users don't want to see the visualization,they just need the results.

Please see the below link to get top10_keywords as a new column. Hope This might help for implementation in pycaret.

https://www.machinelearningplus.com/nlp/topic-modeling-gensim-

python/#16buildingldamalletmodel
 
Thanks to the pycaret team if we see this new feature in topic modeling.

**Comment by karthikavarmar** [comment] 2021-07-27 07:05
How to get the top keywords (together) out of the dominant topics created in a column ? Any updates?

**Comment by moezali1** [comment] 2023-03-18 13:06
We are no more supporting the `nlp` and `arules` module in PyCaret due to lack to resources. Closing the issue now.

**Closed by moezali1** 2023-03-18 13:06 UTC
Labels: enhancement, nlp
