### ISSUE TITLE
plots are not saving through MLFLOW

### ISSUE THREAD

**Issue by akashg116414** [pycaret/pycaret#2439] opened 2022-04-19 04:21 UTC
This is the error I get  "plot_model() got an unexpected keyword argument 'system'"

**Comment by moezali1** [comment] 2022-04-19 13:53
@akashg116414 We can't help you with this. Can you please describe a little bit more, show the code, show the complete error, etc.

**Comment by akashg116414** [comment] 2022-04-20 04:53
this error happens when i install pycaret[full]==2.3.9 and pycaret-ts-alpha both and tried basic classification example
example:
from pycaret.datasets import get_data
data = get_data('juice')
from pycaret.classification import *
clf1 = setup(data, target = 'Purchase', session_id=123, log_experiment=True, experiment_name='juice1',log_plots=True)

**Comment by ngupta23** [comment] 2022-04-20 09:37
> this error happens when i install pycaret[full]==2.3.9 and pycaret-ts-alpha both and tried basic classification example

Are you installing both of them in the same environment? That should not be done as there may be conflicts at this time (until we officially release the 3.0.0 pycaret version which will have time-series integrated with the main pycaret package).

Try installing one of them in a fresh (clean) environment and see if it works.

**Comment by ngupta23** [comment] 2022-04-20 09:46
@akashg116414 By the way, I am not able to recreate the issue with the information (code) you have provided. It works fine for me (see attached notebook below).

https://gist.github.com/ngupta23/f7f33a5361928cac2f36f855f7398c88

Please provide a completely reproducible example that shows the steps to get to the error you are getting.

**Comment by ngupta23** [comment] 2022-04-20 15:58
Since we are unable to recreate this and information seems to be missing, we will close this for now. Feel free to create a new issue. We add a new Bug template that will guide you through the process of submitting a reproducible example. 

Thanks!

**Closed by ngupta23** 2022-04-20 15:58 UTC
Labels: bug, mlflow, missing_info
