### ISSUE TITLE
[BUG] remove_multicollinearity = True Error: dtype for the target variable should be int32 or int64 only

### ISSUE THREAD

**Issue by djlacombe** [pycaret/pycaret#1811] opened 2021-11-07 00:45 UTC
**Describe the bug**
I tried to use the setup command with remove_multicollinearity=True and it throws an error: dtype for the target variable should be int32 or int64 only

**To Reproduce**
To reproduce the error, please run the following code. 

```python
from pycaret.regression import *
from pycaret.datasets import get_data
dataset = get_data('mice')

exp_clu101 = setup(dataset, normalize = True, 
                   ignore_features = ['MouseID'],
                   target = 'DYRK1A_N',
                   session_id = 123, remove_multicollinearity = True)
```

**Expected behavior**

I expected the setup command to work on this problem, however, an error gets thrown. The target variable has the following type: 

```python
dataset['DYRK1A_N'].dtype
dtype('float64')
```
The details are here:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_17584/1299069053.py in <module>
      2 dataset = get_data('mice')
      3 
----> 4 exp_clu101 = setup(dataset, normalize = True, 
      5                    ignore_features = ['MouseID'],
      6                    target = 'DYRK1A_N',

~\Anaconda3\envs\mypycaret\lib\site-packages\pycaret\regression.py in setup(data, target, train_size, test_data, preprocess, imputation_type, iterative_imputation_iters, categorical_features, categorical_imputation, categorical_iterative_imputer, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, numeric_iterative_imputer, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_selection_method, feature_interaction, feature_ratio, interaction_threshold, transform_target, transform_target_method, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, custom_pipeline, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile, profile_kwargs)
    571         log_plots = ["residuals", "error", "feature"]
    572 
--> 573     return pycaret.internal.tabular.setup(
    574         ml_usecase="regression",
    575         available_plots=available_plots,

~\Anaconda3\envs\mypycaret\lib\site-packages\pycaret\internal\tabular.py in setup(data, target, ml_usecase, available_plots, train_size, test_data, preprocess, imputation_type, iterative_imputation_iters, categorical_features, categorical_imputation, categorical_iterative_imputer, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, numeric_iterative_imputer, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_selection_method, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, transform_target, transform_target_method, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, custom_pipeline, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile, profile_kwargs, display)
   1328             test_data = pd.concat([X_test, y_test], axis=1)
   1329 
-> 1330         train_data = prep_pipe.fit_transform(train_data)
   1331         # workaround to also transform target
   1332         dtypes.final_training_columns.append(target)
~\Anaconda3\envs\mypycaret\lib\site-packages\sklearn\pipeline.py in fit_transform(self, X, y, **fit_params)
    365         """
    366         fit_params_steps = self._check_fit_params(**fit_params)
--> 367         Xt = self._fit(X, y, **fit_params_steps)
    368 
    369         last_step = self._final_estimator

~\Anaconda3\envs\mypycaret\lib\site-packages\sklearn\pipeline.py in _fit(self, X, y, **fit_params_steps)
    290                 cloned_transformer = clone(transformer)
    291             # Fit or load from cache the current transformer
--> 292             X, fitted_transformer = fit_transform_one_cached(
    293                 cloned_transformer, X, y, None,
    294                 message_clsname='Pipeline',

~\Anaconda3\envs\mypycaret\lib\site-packages\joblib\memory.py in __call__(self, *args, **kwargs)
    350 
    351     def __call__(self, *args, **kwargs):
--> 352         return self.func(*args, **kwargs)
    353 
    354     def call_and_shelve(self, *args, **kwargs):

~\Anaconda3\envs\mypycaret\lib\site-packages\sklearn\pipeline.py in _fit_transform_one(transformer, X, y, weight, message_clsname, message, **fit_params)
    738     with _print_elapsed_time(message_clsname, message):
    739         if hasattr(transformer, 'fit_transform'):
--> 740             res = transformer.fit_transform(X, y, **fit_params)
    741         else:
    742             res = transformer.fit(X, y, **fit_params).transform(X)

~\Anaconda3\envs\mypycaret\lib\site-packages\pycaret\internal\preprocess.py in fit_transform(self, data, y)
   2712             data frame
   2713     """
-> 2714         self.fit(data)
   2715         return self.transform(data)
   2716 
~\Anaconda3\envs\mypycaret\lib\site-packages\pycaret\internal\preprocess.py in fit(self, data, y)
   2514 
   2515         if data[self.target_variable].dtype not in ["int32", "int64"]:
-> 2516             raise ValueError('dtype for the target variable should be int32 or int64 only')
   2517 
   2518         # global data1

ValueError: dtype for the target variable should be int32 or int64 only

-->

**Additional context**
I am using Pycaret 2.3.4 on Windows 10 in VS Code using the Jupyter notebook feature.

**Versions**

>>> pycaret.__version__
'2.3.4'

**Comment by moezali1** [comment] 2021-11-07 04:02
@wkuopt I remember you worked on a similar issue in past. Can you help on this one as well please?

**Comment by djlacombe** [comment] 2021-11-07 17:26
I’m actually a different user but used the same example to point out the bug.

 

Thanks for looking into this.

**Comment by moezali1** [comment] 2021-11-09 01:58
@djlacombe The message was intended for @wkuopt!

**Comment by wkuopt** [comment] 2021-11-09 03:20
@djlacombe this bug was fixed in https://github.com/pycaret/pycaret/pull/1640. The nightly build should contain the correct code for it.

**Closed** 2021-11-09 03:21 UTC
Labels: bug
