### ISSUE TITLE
[BUG] Unable to specify test_data as an argument during setup.

### ISSUE THREAD

**Issue by yinghawl** [pycaret/pycaret#1387] opened 2021-06-22 16:39 UTC
When trying to run the following code to use a hold-out dataset as test set, it does not work
 336 exp_reg = setup(data = train,  test_data = test,  normalize = True, transformation = True,
      337                  transform_target = True, target = target, session_id=1234,  log_experiment = True,
      338                  experiment_name = 'Trial_2')
      339 

TypeError: setup() got an unexpected keyword argument 'test_data'
-->

**Versions**
Running pycaret==2.3.0 and 2.3.1 (both does not work)

**Comment by wkuopt** [comment] 2021-08-20 04:25
Hi @yinghawl , I was not able to reproduce the error, as test_data is indeed an optional argument. Could you check if your pycaret installation is correct?

**Comment by wkuopt** [comment] 2021-11-21 00:57
Since test_data is indeed an argument and I was not able to reproduce the error, I will close this issue.

**Closed by wkuopt** 2021-11-21 00:57 UTC
Labels: bug
