### ISSUE TITLE
get_data('diamond', profile=True) throws an error.

### ISSUE THREAD

**Issue by tech-a-go-go** [pycaret/pycaret#179] opened 2020-05-28 00:11 UTC
Hi there,

I followed "Regression Tutorial Level Intermediate - REG102" in pycaret repository with jupyter notebook but the line `get_data('diamond', profile=True)` gave the following errors.

```
> from pycaret.datasets import get_data
> dataset = get_data('diamond', profile=True)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-56755cd7057f> in <module>
      1 from pycaret.datasets import get_data
----> 2 dataset = get_data('diamond', profile=True)

~/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pycaret/datasets.py in get_data(dataset, save_copy, profile)
     71         if profile:
     72             import pandas_profiling
---> 73             pf = pandas_profiling.ProfileReport(data_for_profiling)
     74             display(pf)
     75 

~/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pandas_profiling/__init__.py in __init__(self, df, **kwargs)
     66 
     67         # Get dataset statistics
---> 68         description_set = describe_df(df)
     69 
     70         # Get sample

~/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pandas_profiling/model/describe.py in describe(df)
    549 
    550     # Get correlations
--> 551     correlations = calculate_correlations(df, variables)
    552 
    553     # Check correlations between numerical variables

~/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pandas_profiling/model/correlations.py in calculate_correlations(df, variables)
    191                     # Get the Phi_k sorted order
    192                     current_order = (
--> 193                         correlations["phi_k"].index.get_level_values("var1").tolist()
    194                     )
    195 

~/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pandas/core/indexes/base.py in _get_level_values(self, level)
   1477         Index(['a', 'b', 'c'], dtype='object')
   1478         """
-> 1479         self._validate_index_level(level)
   1480         return self
   1481 

~/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pandas/core/indexes/base.py in _validate_index_level(self, level)
   1413                 )
   1414         elif level != self.name:
-> 1415             raise KeyError(
   1416                 f"Requested level ({level}) does not match index name ({self.name})"
   1417             )

KeyError: 'Requested level (var1) does not match index name (None)'
```
Any tips ??
Btw, get_data('diamond') without profile=True option works well.

Cheers

**Comment by MauGal** [comment] 2020-05-31 07:22
Hi, same issue following tutorial CLF102.
In this case I'm using google colab.
Library versions installed of pandas and pandas-profiling  are respectively 1.0.3 and 2.3.0.
These modules are upgraded when I run the command !pip install pycaret.
I hope this information is useful.

**Comment by pycaret** [comment] 2020-06-06 18:36
@MauGal When you used it in colab with pandas==1.0.3 and pandas-profiling==2.3.0. Did it worked or not?

**Comment by MauGal** [comment] 2020-06-07 18:52
> @MauGal When you used it in colab with pandas==1.0.3 and pandas-profiling==2.3.0. Did it worked or not?

No, It didn't work.

**Comment by JBOE22175** [comment] 2020-07-06 12:46
I just installed PyCaret based on current installation guide in Win10 with Anaconda evnironment and got the same error. 
I saved the diamond dataset as csv, created a separate environment and installed pandas-profiling based on their installation guide. Loading the diamond dataset and and executing pf = pandas_profiling.ProfileReport(dataset) does work!
Difference: PyCaret installs pandas-profiling version 2.3.0 while pandas-profiling installation installs version 2.8.0.

Similarly a problem occurs with XGBoost (your requriement is xgboost==0.90 but current version is 1.2.0). When running compare_models() in "Regression Tutorial Level Intermediate - REG102.ipynb" (same problem in REG101) then the kernel dies. You can continue the tutorial only if you use a blacklist = ['xgboost'].

It is frustrating if tutorials don't work. Shouldn't you update your requirements?

**Comment by pycaret** [comment] 2020-07-06 20:28
@JBOE22175 Thanks for reporting. This problem has been resolved in pycaret nightly build. Would you please like to test this and let me know if the issue is fixed for you. You can install pycaret nightly build using pip.

> pip install pycaret-nightly

Thanks for your help.

**Comment by JBOE22175** [comment] 2020-07-07 16:17
After removing current environment and creating a new one with pycaret-nightly it works perfectly.
Thank you!

**Closed** 2020-07-30 19:32 UTC
Labels: available-in-pycaret-nightly, question
