### ISSUE TITLE
Issue with tsne plot in clustering when using PCA

### ISSUE THREAD

**Issue by jruots** [pycaret/pycaret#2031] opened 2022-01-07 13:47 UTC
Hello!
I'm working on clustering with PyCaret 3.5.0. I have the following setup:
`#initialize setup`
`pycaret_cluster_raw = setup(data = pycaret_raw_data`
`                            ,session_id = 42`
`                            ,log_experiment=True`
`                           ,log_plots=True`
`                            ,preprocess=True`
`                           ,ignore_features = ['ID']`
`                            ,normalize=True`
`                           ,normalize_method='minmax'`
`                           ,pca=True`
 `                           ,pca_method='linear'`
  `                          ,pca_components=0.75)`
                          
I then run the model with:
`#run the kmeans model after setup`
`pycaret_kmeans_raw = create_model('kmeans', num_clusters=4)`

After this I try to plot the tsne plot like this:
`#plot the tsne graph in 3d`
`plot_model(pycaret_kmeans_raw, plot = 'tsne')`

And I get the following error:
`KeyError: 'Component_1'`

This has something to do with using PCA in setup. Without it, there are no issues with producing the tsne plot.
Can't share dataset as it it proprietary.

Mike Paulonis on the PyCaret Slack channel reproduced the issue with the mice dataset and had the following to say:
"I tried your approach of doing PCA before clustering and then attempting a t-SNE plot.  I did this with the 'mice' dataset from the clustering tutorial.  My results are the same.  the t-SNE plot failed.  The error arises from this part of the code
`~\Anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py in _tsne_clustering()
   6241                 X_embedded["Feature"] = data_before_preprocess[feature_name]
   6242             else:
-> 6243                 X_embedded["Feature"] = data_before_preprocess[data_X.columns[0]]
   6244 
   6245             if label:`

Line 6243 is trying to extract a specific column from data_before_preprocess, but it is using the label of the 0th column of the X data to identify the column.  This won't work if PCA has been applied.  The column names in the X data get replaced with 'Component_n' after PCA, and these will not be among the original column names in data_before_preprocess."

**Comment by mpaulonis** [comment] 2022-01-07 14:16
The problem can be worked around by including one of the original (pre-PCA) dataset column names as the feature argument in `plot_model`.  For example, using the included 'mice' dataset:

`plot_model(kmeans, plot='tsne', feature='DYRK1A_N')`

This shouldn't be needed, but is easy to do.  Having the plot function go back to data_before_preprocess seems like it could also run into trouble if the first column of the original dataset is a categorical feature that gets encoded.

**Comment by moezali1** [comment] 2022-01-07 14:53
@jruots Thanks for reporting. Just fixed this.

**Comment by moezali1** [comment] 2022-01-07 17:32
The issue is fixed now. Will be included in next release which is tomorrow! :)

**Closed by moezali1** 2022-01-07 17:32 UTC
Labels: bug
