### ISSUE TITLE
Predict issue for Timeseries branch

### ISSUE THREAD

**Issue by akashg116414** [pycaret/pycaret#1185] opened 2021-04-21 09:37 UTC
Hello,
Is there is any way to get prediction on passing start and end date as of now there is only way to pass integer value of test_dataframe.

model.predict(start,end) not working...

please provide some solution. 

Thanks

**Comment by ngupta23** [comment] 2021-04-27 13:48
Hi @akashg116414 , Can you provide a reproducible example of what you are trying to do? 

Also, you also mentioned the `timeseries` branch. Are you running from the GitHub code directly?

**Comment by akashg116414** [comment] 2021-05-03 09:41
In model.predict(), if we pass the date or a date range, the model should forecast or predict but it giving error that "in sktime==0.5.3, TypeError: `values` type not supported. `values` must be one of ('int', 'np.array', 'list', 'pd.Int64Index', 'pd.RangeIndex', 'pd.PeriodIndex', 'pd.DatetimeIndex'), but found: <class 'str'>" 

But with statsmodel.arima or sarimax allows date or dateRange to predict which is natural in timeseries forecasting or prediction frequency or number of forecast passing numeric value, I have never seen passing numeric value in forecast or predict. i have been using date and dateRanges from very long time as it is a standard practice.

Both prediction and out of sample forecasting is not working as expected like statsmodel.arima or sarimax

yes, I am using the timeseries branch from pycaret github

**Comment by ngupta23** [comment] 2021-05-03 10:39
From the error, it looks like your index is a `string` and not `datetime`. Can you check the type of the index?
Also, please provide a reproducible example, otherwise we are just guessing at what is happening.

**Comment by akashg116414** [comment] 2021-05-04 08:07
[timeseries_predict.zip](https://github.com/pycaret/pycaret/files/6419743/timeseries_predict.zip)
Upload a Notebook Example where Model is loaded using joblib but fails to predict which is serialized pipeline stored by pycaret in MLFLOW.

**Comment by ngupta23** [comment] 2021-05-04 11:15
Hi @akashg116414 , Unfortunately, this is not a reproducible example and I am unable to run it for the following reasons.

1. You are loading model from your local directory (No one else has access to this model)
2. We don't know how you have trained your model. Please provide the code for training as well.
3. The data set is also on your local directory so it can not be loaded by anyone else.

Please see guidelines for providing a [reproducible example here](https://stackoverflow.com/help/minimal-reproducible-example). 

Also, have you tried the flow in the time_series_101.ipynb? Does it give the same issue as your flow?

I also want to warn you that time_series is still in development. As such, MLFlow, save_model and load_model and a few other functionality has not yet been tested yet. So something to keep in mind as you try out these examples.

**Comment by ngupta23** [comment] 2021-09-19 20:08
We will close this issue since it has been open for a long time without any activity. As far as I understand, predict model is working just fine right now. Feel free to reopen (with a reproducible example) if the issue persists.

**Closed by ngupta23** 2021-09-19 20:08 UTC
Labels: bug, time_series
