### ISSUE TITLE
[BUG]: ordinal_features = None is not working?

### ISSUE THREAD

**Issue by tonpimenta** [pycaret/pycaret#3846] opened 2023-12-07 16:51 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Hi,
I'm trying to deal with one classification and one regression problems. I apologize in advance if I'm doing something dumb (I'm very far from being a programmer).
On both, I don't want ordinal features and I'm using `ordinal_features = None`, but still, I'm having them as a result: 
![Here's screenshot](https://github.com/pycaret/pycaret/assets/97309305/95fdcd1b-e606-452d-a42f-428567a9f9aa)
Code:
```
from pycaret.regression import *
df = df.replace('?', 'NaN')
s = setup(df, target = 'MU', session_id = 125,
          preprocess = True,
          remove_multicollinearity = True,
          feature_selection = False,
          ordinal_features = None, 
          numeric_features = ['dose_beam_3Dmax', 'ave_depth','fractions', 'dose_fraction', 'dose_beam', 'arc_lenght', 'num_of_CPs', 'cum_W_Area2'],      
          categorical_features = ['cid', 'site', 'energy', 'machine'], 
          normalize = True,
          profile = True)
```
Please note that:
- I'm using `ordinal_features = None`,
- Specifying `categorical_features = ['cid', 'site', 'energy', 'machine']` (including 'machine'),
- After running setup, I'm having 'machine' as ordinal feature (`s._fxs["Ordinal"]`) and, this feature refers to two machine names, so it really does not make sense on being inferred as ordinal.

Will try to provide a reproducible example (sorry, I'm very far from being a programmer)...

### Reproducible Example

```python
import pandas as pd
df_test = pd.DataFrame({
    'num1': [0.1, 0.2, 0.3, 0.4],
    'num2': [1, 2, 3, 4],
    'cat1': ['NovalisTX', 'TrueBeamSN1234', 'TrueBeamSN1234', 'NovalisTx'],
    'cat2': ['Head', 'Shoulders', 'Knees', 'Toes'],
    'MU': [120, 130, 50, 40]
    })
from pycaret.regression import *
exp = setup(df_test, target = 'MU', session_id = 125,
          feature_selection = False,
          ordinal_features = None, 
          numeric_features = ['num1', 'num2'],      
          categorical_features = ['cat1','cat2'])          

print(f'Ordinal features: {exp._fxs["Ordinal"]}')
print(f'Categorical features: {exp._fxs["Categorical"]}')
print(f'Numeric features: {exp._fxs["Numeric"]}')
```

### Expected Behavior

I would expect to have:
- Ordinal Features = 0
- Categorical Features = 2
- Numeric Features = 2

### Actual Results

```python-traceback
I'm having as a result:
- Ordinal Features = 2
- Categorical Features = 2
- Numeric Features = 2
Here's the output:
Ordinal features: {'cat1': ['NovalisTx', 'TrueBeamSN1234'], 'cat2': ['Shoulders', 'Toes']}
Categorical features: ['cat1', 'cat2']
Numeric features: ['num1', 'num2']
```

### Installed Versions

<details>
System:
    python: 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\wfjunior\Anaconda3\python.exe
   machine: Windows-10-10.0.19042-SP0

PyCaret required dependencies:
                 pip: 23.3.1
          setuptools: 68.0.0
             pycaret: 3.2.1
             IPython: 8.12.2
          ipywidgets: 8.0.4
                tqdm: 4.65.0
               numpy: 1.24.3
              pandas: 2.0.3
              jinja2: 3.1.2
               scipy: 1.9.3
              joblib: 1.2.0
             sklearn: 1.3.0
                pyod: 1.1.2
            imblearn: 0.11.0
   category_encoders: 2.6.3
            lightgbm: 4.1.0
               numba: 0.58.1
            requests: 2.31.0
          matplotlib: 3.7.2
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.9.0
    plotly-resampler: Not installed
             kaleido: 0.2.1
           schemdraw: 0.15
         statsmodels: 0.0.0
              sktime: 0.21.1
               tbats: 1.1.3
            pmdarima: 0.0.0
              psutil: 5.9.0
          markupsafe: 2.1.3
             pickle5: Not installed
         cloudpickle: 2.2.1
         deprecation: 2.1.0
              xxhash: 2.0.2
           wurlitzer: Not installed

PyCaret optional dependencies:
                shap: 0.43.0
           interpret: 0.4.4
                umap: 0.5.5
     ydata_profiling: 4.6.0
  explainerdashboard: 0.4.3
             autoviz: 0.1.732
           fairlearn: 0.7.0
          deepchecks: Not installed
             xgboost: 2.0.2
            catboost: 1.2.2
              kmodes: 0.12.2
             mlxtend: 0.23.0
       statsforecast: 1.5.0
        tune_sklearn: 0.5.0
                 ray: 2.8.1
            hyperopt: 0.2.7
              optuna: 3.4.0
               skopt: 0.9.0
              mlflow: 1.30.1
              gradio: 3.50.2
             fastapi: 0.104.1
             uvicorn: 0.24.0.post1
              m2cgen: 0.10.0
           evidently: 0.2.8
               fugue: 0.8.6
           streamlit: Not installed
             prophet: Not installed
</details>

**Comment by tvdboom** [comment] 2023-12-09 18:55
Thanks for reporting this. It's not really a bug, but it definitely isn't very clean on pycaret's side.

What's happens is that, first, the feature `machine` is correctly assigned to the categorical features, but then, when encoding the feature, it realizes it only has 2 unique values, and therefore it gets encoded using the `OrdinalEncoder`. To encode it ordinally (which is intended behavior), it adds the feature to the Ordinal features attribute in `._fxs`, which it probably shouldn't do.

There are no downside consequences for your pipeline here, except that the visual representation is wrong. I'll make a fix for that.

If you try, you'll see that this doesn't happen when the feature has more than 2 unique values.

**Closed** 2023-12-09 20:36 UTC
Labels: bug
