### ISSUE TITLE
[BUG]: times series prediction is returning empty dataframe

### ISSUE THREAD

**Issue by sabirjana** [pycaret/pycaret#2986] opened 2022-09-25 14:10 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Hi, I tried to run the airline example as provided in the documentation. After executing setup(), when I run compare_models() it returns an empty dataframe. Appreciate any help!
![image](https://user-images.githubusercontent.com/52304765/192147439-b5b34519-0e98-4580-8d97-f8ff08eca41a.png)

### Reproducible Example

```python
from pycaret.datasets import get_data
df = get_data('airline')
```

### Expected Behavior

![image](https://user-images.githubusercontent.com/52304765/192147690-12839aab-3eb1-4ebe-a76a-716079aeb7a2.png)

### Actual Results

```python-traceback
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [9], line 1
----> 1 prediction = predict_model(best, fh = 90)
      2 prediction.to_frame()
      3 prediction

File ~\AppData\Roaming\Python\Python38\site-packages\pycaret\time_series\forecasting\functional.py:1023, in predict_model(estimator, fh, X, return_pred_int, alpha, round, verbose)
   1020 if experiment is None:
   1021     experiment = _EXPERIMENT_CLASS()
-> 1023 return experiment.predict_model(
   1024     estimator=estimator,
   1025     fh=fh,
   1026     X=X,
   1027     return_pred_int=return_pred_int,
   1028     alpha=alpha,
   1029     round=round,
   1030     verbose=verbose,
   1031 )

File ~\AppData\Roaming\Python\Python38\site-packages\pycaret\time_series\forecasting\oop.py:3314, in TSForecastingExperiment.predict_model(self, estimator, fh, X, return_pred_int, alpha, round, verbose)
   3244 def predict_model(
   3245     self,
   3246     estimator,
   (...)
   3252     verbose: bool = True,
   3253 ) -> pd.DataFrame:
   3255     """
   3256     This function forecast using a trained model. When ``fh`` is None,
   3257     it forecasts using the same forecast horizon used during the
   (...)
   3311 
   3312     """
-> 3314     estimator.check_is_fitted()
   3316     pipeline_with_model, estimator_ = self._predict_model_reconcile_pipe_estimator(
   3317         estimator=estimator
   3318     )
   3320     fh = self._predict_model_reconcile_fh(estimator=estimator_, fh=fh)

AttributeError: 'list' object has no attribute 'check_is_fitted'
```

### Installed Versions

<details>
System:
    python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
executable: C:\ProgramData\Anaconda3\envs\pycaretenv\python.exe
   machine: Windows-10-10.0.22000-SP0

Python dependencies:
          pip: 22.1.2
   setuptools: 63.4.1
      pycaret: 3.0.0
      sklearn: 1.0.2
       sktime: 0.13.2
  statsmodels: 0.13.2
        numpy: 1.21.6
        scipy: 1.8.1
       pandas: 1.4.4
   matplotlib: 3.6.0
       plotly: 5.10.0
       joblib: 1.1.0
        numba: 0.55.2
       mlflow: Not installed
     lightgbm: 3.3.2
      xgboost: Not installed
     pmdarima: 1.8.5
        tbats: Installed but version unavailable
      prophet: 1.1.1
      tsfresh: 0.19.0
</details>

**Comment by ngupta23** [comment] 2022-09-26 02:03
There is not enough information here to debug. Can you provide a completely reproducible example of the code? Thanks!

**Comment by sabirjana** [comment] 2022-09-26 05:37
Please find attached a zip file with the code. Appreciate it if you can have a look. Thanks!
[pycaret_prediction_v.10.zip](https://github.com/pycaret/pycaret/files/9643232/pycaret_prediction_v.10.zip)

**Comment by ngupta23** [comment] 2022-10-08 20:12
I am not able to reproduce your issue. It seems to be working fine for me. See here: https://gist.github.com/ngupta23/f550e5f0530dce73ad3afb90a8fee8bb

I will close this issue. Feel free to reopen if you can provide the reproducible code for this issue.

**Closed by ngupta23** 2022-10-08 20:12 UTC
Labels: bug, time_series
