### ISSUE TITLE
[BUG]: Cannot import pycaret.classification (KeyError)

### ISSUE THREAD

**Issue by lucidviews** [pycaret/pycaret#2980] opened 2022-09-21 16:25 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

I just installed the latest PyCaret version (3.0-rc) but when I try to run `from pycaret,classification import *` I receive an error in my Python 3.9.12 virtual env.

I am however able to import the dataset using `from pycaret.datasets import get_data`

### Reproducible Example

```python
from pycaret.classification import *
```

### Expected Behavior

Successful import of all PyCaret functions.

### Actual Results

```python-traceback
Traceback (most recent call last):
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/8b/9w96sjd930j08ht19r_6xnx00000gn/T/ipykernel_11456/2894516886.py", line 8, in <module>
    from pycaret.anomaly import *
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/pycaret/anomaly/__init__.py", line 1, in <module>
    from pycaret.anomaly.functional import (
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/pycaret/anomaly/functional.py", line 7, in <module>
    from pycaret.anomaly.oop import AnomalyExperiment
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/pycaret/anomaly/oop.py", line 5, in <module>
    import pycaret.containers.metrics.anomaly
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/pycaret/containers/metrics/anomaly.py", line 17, in <module>
    import pycaret.containers.base_container
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/pycaret/containers/base_container.py", line 8, in <module>
    import pycaret.internal.utils
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/pycaret/internal/utils.py", line 8, in <module>
    import pandas.io.formats.style
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/pandas/io/formats/style.py", line 105, in <module>
    class Styler(StylerRenderer):
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/pandas/io/formats/style.py", line 447, in Styler
    def to_excel(
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/pandas/util/_decorators.py", line 394, in decorator
    )
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/pandas/util/_decorators.py", line 395, in <listcomp>
KeyError: 'storage_options_versionadded'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 1997, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1112, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1006, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/IPython/core/ultratb.py", line 859, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/IPython/core/ultratb.py", line 812, in format_exception_as_a_whole
    frames.append(self.format_record(r))
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/IPython/core/ultratb.py", line 730, in format_record
    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/stack_data/core.py", line 734, in lines
    pieces = self.included_pieces
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/stack_data/core.py", line 681, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/stack_data/core.py", line 660, in executing_piece
    return only(
  File "/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/executing/executing.py", line 164, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0
```

### Installed Versions

<details>
System:
    python: 3.9.12 (main, Apr  5 2022, 01:53:17)  [Clang 12.0.0 ]
executable: /Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/bin/python
   machine: macOS-10.16-x86_64-i386-64bit

PyCaret required dependencies:
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?aa2e5296-e3fb-41a7-a805-4627accbeab1)
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In [54], line 2
      1 from pycaret import show_versions
----> 2 show_versions()

File ~/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/pycaret/utils/_show_versions.py:177, in show_versions(optional, logger)
    174     print_func("{k:>10}: {stat}".format(k=k, stat=stat))  # noqa: T001
    176 print_func(f"{prefix}PyCaret required dependencies:")  # noqa: T001
--> 177 optional_deps_info = _get_deps_info(logger=logger)
    178 for k, stat in optional_deps_info.items():
    179     print_func("{k:>20}: {stat}".format(k=k, stat=stat))  # noqa: T001

File ~/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/pycaret/utils/_show_versions.py:143, in _get_deps_info(optional, logger)
    141             mod = importlib.import_module(modname)
    142     else:
--> 143         mod = importlib.import_module(modname)
    144 ver = _get_module_version(mod)
    145 deps_info[modname] = ver

File ~/opt/anaconda3/lib/python3.9/importlib/__init__.py:127, in import_module(name, package)
    125             break
    126         level += 1
--> 127 return _bootstrap._gcd_import(name[level:], package, level)
...
    384     self._handle = handle

OSError: dlopen(/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: '/usr/local/opt/libomp/lib/libomp.dylib'
  Referenced from: '/Users/lucassilbernagel/Documents/GitHub/churn_prediction/venv_churn/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so'
  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file)
</details>

**Comment by IacusElias** [comment] 2022-09-23 13:28
i Have a problem also importing classification from pycaret.
ImportError: cannot import name '_astype_copy_false' from 'sklearn.utils.fixes'

**Comment by cespos** [comment] 2022-09-28 08:45
Hi! 
I also cannot import pycaret.classification but I got a different error:
```
>>> from pycaret.classification import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/users/carespos/conda/envs/evoqsar_pycaret3/lib/python3.8/site-packages/pycaret/classification/__init__.py", line 1, in <module>
    from pycaret.classification.functional import (
  File "/data/users/carespos/conda/envs/evoqsar_pycaret3/lib/python3.8/site-packages/pycaret/classification/functional.py", line 7, in <module>
    from pycaret.classification.oop import ClassificationExperiment
  File "/data/users/carespos/conda/envs/evoqsar_pycaret3/lib/python3.8/site-packages/pycaret/classification/oop.py", line 13, in <module>
    from pycaret.containers.metrics import get_all_class_metric_containers
ImportError: cannot import name 'get_all_class_metric_containers' from 'pycaret.containers.metrics' (/data/users/carespos/conda/envs/evoqsar_pycaret3/lib/python3.8/site-packages/pycaret/containers/metrics/__init__.py)
```
Thanks!

**Comment by ngupta23** [comment] 2022-11-05 12:39
Can you paste the output of following command to this issue

```python
from pycaret import show_versions
show_versions()
```

**Comment by moezali1** [comment] 2022-11-17 13:26
Closing issue due to lack of reproducible example and OP not responding.

**Closed by moezali1** 2022-11-17 13:26 UTC
Labels: bug, classification
