### ISSUE TITLE
[BUG]: Pycaret not support scikit-learn > 1.0.2

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#2543] opened 2022-05-12 23:06 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

in requirements.txt it says that pycaret can install scikit-learn equal to or greater than 1.0.2.

I installed scikit-learn 1.1.0 and now I get error
 ImportError: cannot import name '_check_param_grid' from 'sklearn.model_selection._search'

### Reproducible Example

```python
from pycaret.classification import *
```

### Expected Behavior

 no errors

### Actual Results

```python-traceback
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [20], in <cell line: 1>()
----> 1 from pycaret.classification import *

File ~\miniconda3\lib\site-packages\pycaret\classification\__init__.py:1, in <module>
----> 1 from pycaret.classification.functional import (
      2     add_metric,
      3     automl,
      4     blend_models,
      5     calibrate_model,
      6     check_fairness,
      7     compare_models,
      8     convert_model,
      9     create_api,
     10     create_app,
     11     create_docker,
     12     create_model,
     13     dashboard,
     14     deploy_model,
     15     eda,
     16     ensemble_model,
     17     evaluate_model,
     18     finalize_model,
     19     get_config,
     20     get_leaderboard,
     21     get_logs,
     22     get_metrics,
     23     interpret_model,
     24     load_config,
     25     load_model,
     26     models,
     27     optimize_threshold,
     28     plot_model,
     29     predict_model,
     30     pull,
     31     remove_metric,
     32     save_config,
     33     save_model,
     34     set_config,
     35     set_current_experiment,
     36     setup,
     37     stack_models,
     38     tune_model,
     39 )
     40 from pycaret.classification.oop import ClassificationExperiment
     42 __all__ = [
     43     "ClassificationExperiment",
     44     "setup",
   (...)
     80     "create_app",
     81 ]

File ~\miniconda3\lib\site-packages\pycaret\classification\functional.py:9, in <module>
      6 import pandas as pd
      7 from joblib.memory import Memory
----> 9 from pycaret.classification.oop import ClassificationExperiment
     10 from pycaret.internal.utils import (
     11     DATAFRAME_LIKE,
     12     TARGET_LIKE,
     13     check_if_global_is_not_none,
     14 )
     16 # from pycaret.parallel import ParallelBackend # unused

File ~\miniconda3\lib\site-packages\pycaret\classification\oop.py:17, in <module>
     15 import pycaret.internal.patches.sklearn
     16 import pycaret.internal.patches.yellowbrick
---> 17 import pycaret.internal.persistence
     18 import pycaret.internal.preprocess
     19 from pycaret.internal.Display import Display

File ~\miniconda3\lib\site-packages\pycaret\internal\persistence.py:12, in <module>
     10 from pycaret.internal.utils import get_logger
     11 from pycaret.utils._dependencies import _check_soft_dependencies
---> 12 from pycaret.utils.time_series.forecasting.pipeline import _add_model_to_pipeline
     15 def deploy_model(
     16     model, model_name: str, authentication: dict, platform: str = "aws", prep_pipe_=None
     17 ):
     18     """
     19     (In Preview)
     20 
   (...)
    100 
    101     """

File ~\miniconda3\lib\site-packages\pycaret\utils\time_series\forecasting\pipeline.py:6, in <module>
      4 import pandas as pd
      5 from sktime.forecasting.base import BaseForecaster
----> 6 from sktime.forecasting.compose import ForecastingPipeline, TransformedTargetForecaster
      7 from sktime.transformations.compose import TransformerPipeline
      8 from sktime.transformations.series.impute import Imputer

File ~\miniconda3\lib\site-packages\sktime\forecasting\compose\__init__.py:28, in <module>
      8 __all__ = [
      9     "ColumnEnsembleForecaster",
     10     "EnsembleForecaster",
   (...)
     24     "make_reduction",
     25 ]
     27 from sktime.forecasting.compose._column_ensemble import ColumnEnsembleForecaster
---> 28 from sktime.forecasting.compose._ensemble import (
     29     AutoEnsembleForecaster,
     30     EnsembleForecaster,
     31 )
     32 from sktime.forecasting.compose._multiplexer import MultiplexForecaster
     33 from sktime.forecasting.compose._pipeline import (
     34     ForecastingPipeline,
     35     TransformedTargetForecaster,
     36 )

File ~\miniconda3\lib\site-packages\sktime\forecasting\compose\_ensemble.py:20, in <module>
     18 from sktime.forecasting.base import ForecastingHorizon
     19 from sktime.forecasting.base._meta import _HeterogenousEnsembleForecaster
---> 20 from sktime.forecasting.model_selection import temporal_train_test_split
     21 from sktime.utils.stats import (
     22     _weighted_geometric_mean,
     23     _weighted_max,
     24     _weighted_median,
     25     _weighted_min,
     26 )
     27 from sktime.utils.validation.forecasting import check_regressor

File ~\miniconda3\lib\site-packages\sktime\forecasting\model_selection\__init__.py:22, in <module>
     20 from sktime.forecasting.model_selection._split import SlidingWindowSplitter
     21 from sktime.forecasting.model_selection._split import temporal_train_test_split
---> 22 from sktime.forecasting.model_selection._tune import ForecastingGridSearchCV
     23 from sktime.forecasting.model_selection._tune import ForecastingRandomizedSearchCV

File ~\miniconda3\lib\site-packages\sktime\forecasting\model_selection\_tune.py:13, in <module>
     11 from sklearn.base import clone
     12 from sklearn.model_selection import ParameterGrid, ParameterSampler, check_cv
---> 13 from sklearn.model_selection._search import _check_param_grid
     14 from sklearn.utils.metaestimators import if_delegate_has_method
     16 from sktime.exceptions import NotFittedError

ImportError: cannot import name '_check_param_grid' from 'sklearn.model_selection._search' (C:\Users\username\miniconda3\lib\site-packages\sklearn\model_selection\_search.py)
```

### Installed Versions

<details>
pycaret: 3.0
scikit-learn: 1.1.0
</details>

**Comment by celestinoxp** [comment] 2022-05-12 23:13
scikit-learn 1.1.0 is a latest version released in May2022
https://scikit-learn.org/stable/whats_new/v1.1.html#changes-1-1

**Comment by ngupta23** [comment] 2022-05-13 00:44
Closing as this is a duplicate of #2542. Please follow that issue for updates. Short term fix is mentioned there.

**Closed by ngupta23** 2022-05-13 00:44 UTC
Labels: bug
