### ISSUE TITLE
plot_model() fails due to possible matplotlib incompatibility

### ISSUE THREAD

**Issue by bsense-rius** [pycaret/pycaret#2299] opened 2022-03-16 11:02 UTC
**Describe the bug**
In google colab, with full install of pycaret and enable_colab(), just running the plot_model example from pycaret's documentation website
https://pycaret.gitbook.io/docs/get-started/functions/analyze#plot_model
The plot_model() section throws an error

If i revert to a previous matplotlib the error is over:
 !pip install matplotlib==3.1.3

**To Reproduce**
```python
# load dataset
from pycaret.datasets import get_data
diabetes = get_data('diabetes')

# init setup
from pycaret.classification import *
clf1 = setup(data = diabetes, target = 'Class variable')

# creating a model
lr = create_model('lr')

# plot model
plot_model(lr, plot = 'auc')
```

**Expected behavior**
Show the auc chart.

**Additional context**

**Versions**

**Comment by moezali1** [comment] 2022-03-27 21:25
@bsense-rius I just tried this on Colab and I cannot reproduce the bug. You do not need to run the `enable_colab` command anymore. Where do you find the reference for `enable_colab`. I thought I removed it everywhere from the documentation.

Link to Colab: https://colab.research.google.com/drive/1g21vnMEwOtL5Hp1QDvZJomeYFYIJsSXf?usp=sharing

Anyways, hope this helps. Closing the issue now.

**Closed by moezali1** 2022-03-27 21:25 UTC
Labels: bug, installation
