### ISSUE TITLE
All result AUC = 0 with compare_model

### ISSUE THREAD

**Issue by houpdelta** [pycaret/pycaret#3932] opened 2024-03-02 18:36 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

The result of the compare_model()  presents AUC = 0

### Reproducible Example

```python
from pycaret.classification import *
data = pd.read_sql(query,mydb)
from pycaret.classification import *
s = setup(data, target='weather', log_experiment=True, experiment_name= my_experiment_name)
best_model = s.compare_models()
```

### Expected Behavior

Table best models incomplete- AUC
![image](https://github.com/pycaret/pycaret/assets/10964021/38275ebc-86ce-446d-81ba-f7936f66edfa)

### Actual Results

```python-traceback
`2024-03-02 14:11:43,296:WARNING:c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\pycaret\internal\metrics.py:196: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method=('decision_function', 'predict_proba'), average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\pycaret\internal\metrics.py", line 188, in _score
return super()._score(
File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\sklearn\metrics_scorer.py", line 350, in _score
return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\pycaret\internal\metrics.py", line 136, in call
return self.score_func(y_true, y_pred, **kwargs)
File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\sklearn\utils_param_validation.py", line 213, in wrapper
return func(*args, **kwargs)
File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\sklearn\metrics_ranking.py", line 634, in roc_auc_score
return _multiclass_roc_auc_score(
File "c:\Users\Laurent\miniconda3\envs\pycaret3\lib\site-packages\sklearn\metrics_ranking.py", line 707, in _multiclass_roc_auc_score
raise ValueError(
ValueError: Target scores need to be probabilities for multiclass roc_auc, i.e. they should sum up to 1.0 over classes
```

### Installed Versions

<details>
pycaret: 3.3.0
IPython: 8.22.1
ipywidgets: 8.1.2
tqdm: 4.66.2
numpy: 1.26.4
pandas: 2.1.4
jinja2: 3.1.3
scipy: 1.11.4
joblib: 1.3.2
sklearn: 1.4.1.post1
</details>

**Comment by houpdelta** [comment] 2024-03-04 18:47
I forgot but #3935 gas been tested. 
But it doesnt work.

**Comment by predictiori** [comment] 2024-03-10 08:54
I enabled metadata routing and the AUC are back.

import sklearn
sklearn.set_config(enable_metadata_routing=True)

**Comment by predictiori** [comment] 2024-03-14 06:05
The transform function called may have created the error. The scikit-learn pipeline module uses a different transform function.

**Comment by celestinoxp** [comment] 2024-03-16 08:01
Hi @predictiori Can you make a pull-request with a fix for this problem?

**Comment by predictiori** [comment] 2024-03-17 05:29
Hi @celestinoxp, I will try. I am exploring the issue locally on my computer, and unexpectedly, the output contains the AUC values. How could this happen?

<img width="565" alt="Screenshot 2024-03-17 at 1 27 08 pm" src="https://github.com/pycaret/pycaret/assets/154598106/60e56758-02be-4aaa-818e-1dc36a314935">

**Comment by predictiori** [comment] 2024-03-17 07:20
I have a quick look at the PyPI file (https://pypi.org/project/pycaret/#files). In classification.py (within the pycaret/containers/metrics folder), the line "needs_proba=True," has been replaced with "response_method=("decision_function", "predict_proba")," in the GitHub version.

GitHub version
```
class ROCAUCMetricContainer(ClassificationMetricContainer):
    def __init__(self, globals_dict: dict) -> None:
        args = {"average": "weighted", "multi_class": "ovr"}
        score_func = pycaret.internal.metrics.BinaryMulticlassScoreFunc(
            metrics.roc_auc_score,
            kwargs_if_binary={"average": "macro", "multi_class": "raise"},
        )
        super().__init__(
            id="auc",
            name="AUC",
            score_func=score_func,
            scorer=pycaret.internal.metrics.make_scorer_with_error_score(
                score_func,
                response_method=("decision_function", "predict_proba"),
                error_score=0.0,
                **args,
            ),
            target="pred_proba",
            args=args,
        )
```
PyPI version

```
class ROCAUCMetricContainer(ClassificationMetricContainer):
    def __init__(self, globals_dict: dict) -> None:
        args = {"average": "weighted", "multi_class": "ovr"}
        score_func = pycaret.internal.metrics.BinaryMulticlassScoreFunc(
            metrics.roc_auc_score,
            kwargs_if_binary={"average": "macro", "multi_class": "raise"},
        )
        super().__init__(
            id="auc",
            name="AUC",
            score_func=score_func,
            scorer=pycaret.internal.metrics.make_scorer_with_error_score(
                score_func, 
                needs_proba=True, 
                error_score=0.0, 
                **args
            ),
            target="pred_proba",
            args=args,
        )

```
Do you think this is the cause of the error?

**Comment by predictiori** [comment] 2024-03-20 23:09
@celestinoxp, I just wonder what you think about this issue. Thanks.

**Comment by predictiori** [comment] 2024-03-21 12:09
It seems I have gone down the wrong path. I will focus on the transform issue.

**Comment by cedricgoubard** [comment] 2024-04-16 13:26
Hi,
I had this problem too. In my case, **I got around it by setting `max_encoding_ohe=0` when calling `setup()`.**
Looks like the problem comes from the fact that some of the group values are dropped when the categorical feature is encoded.

**Comment by predictiori** [comment] 2024-04-17 06:22
@cedricgoubard You could be on the right track. I have found a similar problem with categorical variables. I instead reverted the commented-out code in the predict_proba definition and got around the issue. It's related to the transformer, but my debug/python skills are rather basic, and I don't know how to progress.

```
def predict_proba(self, X, **params):
        # X, _ = self._memory_full_transform(self, X, None, with_final=False)

        Xt = X

        if not _routing_enabled():
            for _, name, transform in self._iter(with_final=False):
                Xt = transform.transform(Xt)
            return self.steps[-1][1].predict_proba(Xt, **params)

        # metadata routing enabled
        routed_params = process_routing(self, "predict_proba", **params)

        # return self.steps[-1][-1].predict_proba(X, **params)
        return self.steps[-1][1].predict_proba(
            Xt, **routed_params[self.steps[-1][0]].predict_proba
        )
```

**Comment by celestinoxp** [comment] 2024-04-22 18:11
@Yard1 any suggestion to fix it?

**Closed** 2024-04-28 16:42 UTC
Labels: bug
