### ISSUE TITLE
[BUG] preprocess=False doesn't seem to turn off preprocessing in classification setup

### ISSUE THREAD

**Issue by nateGeorge** [pycaret/pycaret#1322] opened 2021-06-03 01:56 UTC
**Describe the bug**
In pycaret.classification.setup, setting `preprocess=False` doesn't seem to actually turn off preprocessing.

**To Reproduce**
This loads the 20 newsgroups data, creates TFIDF vectors, and tries to run pycaret's setup for classification. However, it hangs for at least 10 minutes on 'preprocessing' even though `preprocess=False` (I interrupted it after waiting 10 minutes). The shape of the training data is `(11314, 13270)` and test data is `(7532, 13270)`.

```python
from pycaret.classification import setup, create_model, tune_model, evaluate_model
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.datasets import fetch_20newsgroups
import pandas as pd


newsgroups_train = fetch_20newsgroups(remove=('headers', 'footers'))
newsgroups_test = fetch_20newsgroups(subset='test', remove=('headers', 'footers'))

vectorizer = TfidfVectorizer(min_df=10, max_df=0.9)
train_tfidf = vectorizer.fit_transform(newsgroups_train['data'])
test_tfidf = vectorizer.transform(newsgroups_test['data'])

train_tfidf_df = pd.DataFrame(train_tfidf.todense())
test_tfidf_df = pd.DataFrame(test_tfidf.todense())
train_tfidf_df['label'] = newsgroups_train['target']
test_tfidf_df['label'] = newsgroups_test['target']

train_tfidf_df['label'] = train_tfidf_df['label'].astype('category')
test_tfidf_df['label'] = test_tfidf_df['label'].astype('category')

colnames = train_tfidf_df.drop('label', axis=1).columns.tolist()
tfidf_setup = setup(train_tfidf_df, test_data=test_tfidf_df, target='label', fold=3, numeric_features=colnames, silent=True, preprocess=False)

lr = create_model('lr')
```

**Expected behavior**
I would expect setup to complete quickly (a few seconds) since there should be no preprocessing and it's just configuring which data is which. I also set silent=True and told it all the columns are numeric, so it doesn't seem like pycaret should have any preprocessing steps to do.

**Additional context**
I don't understand what the preprocessing is actually doing and don't see a way to enable additional verbosity to see what it's doing. The data has no missing values or categorical values, so there shouldn't be any preprocessing to do. How do we see what the preprocessing is actually doing or what it is hanging up on?

It seems like something doesn't work well when data size gets big. Here is another example of someone having a similar problem: https://stackoverflow.com/questions/67000519/pycaret-stuck-on-setup

**Versions**
2.3.1

**Comment by Yard1** [comment] 2021-06-03 06:49
`Preprocess=False` still runs the data types inference and conversion step in order to guarantee PyCaret functionality. That'd be the reason. We cannot remove that step as it is the bare minimum required for the rest of PyCaret to not throw exceptions related to data constantly.

**Comment by nateGeorge** [comment] 2021-06-03 12:25
But if I'm providing the datatypes, why does it need to do data type inference and conversion?

**Comment by Yard1** [comment] 2021-06-03 13:50
Because they need to be in a specific format for PyCaret to work. We will be refactoring the code responsible in the next major release and we'll see if we can drop that requirement.

**Comment by nateGeorge** [comment] 2021-06-04 01:30
I see. It would definitely be very helpful to be able to provide the data already prepared and be able to turn off the inference and conversion. Or maybe some profiling to figure out where the bottlenecking is. It seems to make it unusable with big datasets with many features.

**Comment by moezali1** [comment] 2022-11-30 02:59
@tvdboom I believe this should be fixed now?

**Comment by tvdboom** [comment] 2022-11-30 07:57
Yes, this is fixed. I tested it with the reproducible example. Preprocess takes around 3 seconds (it's still a very large dataset).

**Closed by tvdboom** 2022-11-30 07:57 UTC
Labels: bug, enhancement
