### ISSUE TITLE
[BUG]: Predict model index out of bound for multi class

### ISSUE THREAD

**Issue by limleewen** [pycaret/pycaret#2494] opened 2022-05-03 09:37 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

same code run for binary class dataset working fine

### Reproducible Example

```python
df = pd.read_csv('D:\P2\Data\Iris.csv')
data = df.sample(frac=0.9, random_state=132)  #best model: ridge
data_unseen = df.drop(data.index)
data.reset_index(drop=True, inplace=True)
data_unseen.reset_index(drop=True, inplace=True)

print('Data for Modeling: ' + str(data.shape))
print('Unseen Data For Predictions: ' + str(data_unseen.shape))

m1 = setup(data = data,
           target = 'Species',silent=True, feature_selection=True,
          session_id=1)

best=compare_models(n_select = 1,cross_validation=True)
#Create Best Model
BM = create_model(best, cross_validation=True, fold=10)

tuned_BM = tune_model(BM)

evaluate_model(tuned_BM)

predict_model(tuned_BM)
```

### Expected Behavior

http://www.pycaret.org/tutorials/html/MCLF101.html

### Actual Results

```python-traceback
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-57-621134d496db> in <module>
----> 1 predict_model(tuned_BM)

~\anaconda3\lib\site-packages\pycaret\classification.py in predict_model(estimator, data, probability_threshold, encoded_labels, raw_score, drift_report, round, verbose, drift_kwargs)
   2123     """
   2124 
-> 2125     return pycaret.internal.tabular.predict_model(
   2126         estimator=estimator,
   2127         data=data,

~\anaconda3\lib\site-packages\pycaret\internal\tabular.py in predict_model(estimator, data, probability_threshold, encoded_labels, drift_report, raw_score, round, verbose, ml_usecase, display, drift_kwargs)
   9163         pred = pred.astype(int)
   9164         if not raw_score:
-> 9165             score = [s[pred[i]] for i, s in enumerate(score)]
   9166         try:
   9167             score = pd.DataFrame(score)

~\anaconda3\lib\site-packages\pycaret\internal\tabular.py in <listcomp>(.0)
   9163         pred = pred.astype(int)
   9164         if not raw_score:
-> 9165             score = [s[pred[i]] for i, s in enumerate(score)]
   9166         try:
   9167             score = pd.DataFrame(score)

IndexError: index 4 is out of bounds for axis 0 with size 4
```

### Installed Versions

<details>
The scikit-learn version is 0.23.2.
The pycaret version is 2.3.9.
</details>

**Comment by moezali1** [comment] 2022-05-03 12:12
@limleewen I can't reproduce this issue on Colab.

![image](https://user-images.githubusercontent.com/54699234/166450480-7f095a09-5d2c-4a48-a354-385ebd4de496.png)

**Comment by limleewen** [comment] 2022-05-04 02:29
@moezali1 thanks for your reply. I have found the issue if the target label starts with 1, it will hit this error. For example if I use 1,2,3 to label 3 types of Iris, it hit the error, but if I change it to 0,1,2 it work.

**Comment by jiristo** [comment] 2022-05-22 01:55
Hello, I am reporting exactly  the same issue! Though, I can get prediction with setting parameter `raw_score=True` in `predict_model()`
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/47312723/169674997-383c0ec6-1979-4aca-ad04-e9be6f7eadcb.png">

**Comment by ngupta23** [comment] 2022-06-10 10:51
@limleewen , @jiristo Can you check this with the latest release (3.0.0 rc). It should be fixed there.

`pip install -U --pre pycaret`

**Comment by kakalovedata** [comment] 2022-08-04 03:18
I am reporting exactly the same issue! 
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/var/folders/wr/zr3swp2j5q33rsrn4q2n8mbr0000gn/T/ipykernel_64802/1668823279.py in <module>
----> 1 df_result=predict_model(lightgbm)

/opt/anaconda3/lib/python3.8/site-packages/pycaret/classification.py in predict_model(estimator, data, probability_threshold, encoded_labels, raw_score, drift_report, round, verbose, drift_kwargs)
   2124 
   2125     return pycaret.internal.tabular.predict_model(
-> 2126         estimator=estimator,
   2127         data=data,
   2128         probability_threshold=probability_threshold,

/opt/anaconda3/lib/python3.8/site-packages/pycaret/internal/tabular.py in predict_model(estimator, data, probability_threshold, encoded_labels, drift_report, raw_score, round, verbose, ml_usecase, display, drift_kwargs)
   9169                 score_columns = pd.Series(range(score.shape[1]))
   9170                 if not encoded_labels:
-> 9171                     replace_lables_in_column(score_columns)
   9172                 score.columns = [f"Score_{label}" for label in score_columns]
   9173             else:

/opt/anaconda3/lib/python3.8/site-packages/pycaret/internal/tabular.py in <listcomp>(.0)
   9169                 score_columns = pd.Series(range(score.shape[1]))
   9170                 if not encoded_labels:
-> 9171                     replace_lables_in_column(score_columns)
   9172                 score.columns = [f"Score_{label}" for label in score_columns]
   9173             else:

IndexError: index 3 is out of bounds for axis 0 with size 3

**Comment by tvdboom** [comment] 2022-08-05 06:47
Can you confirm that this error occurred using the newest rc release `pip install -U --pre pycaret`? And if so, share a reproducible example. Thanks

**Comment by DanielLeung222** [comment] 2022-08-10 07:57
Hi, I have face the same problem, however, when I use pip install -U --pre pycaret, it occur another error.
![image](https://user-images.githubusercontent.com/108645351/183846973-3e791245-ec66-4c03-86e9-e79cf856d3b5.png)

**Comment by tvdboom** [comment] 2022-08-10 17:29
Can you share which version of pycaret you are using? Run `pycaret.__version__`. Also, I can't debug without a reproducible example. Thanks

**Comment by ngupta23** [comment] 2022-08-15 10:24
Verified in August 15th meeting. 

This is fixed in the latest pre released version. Users should install the following to check it out

`pip install --pre pycaret`

If the issue persists, please open a new issue with a reproducible example,

**Closed by ngupta23** 2022-08-15 10:24 UTC
Labels: bug
