### ISSUE TITLE
MemoryError:Unable to allocate 11.1 GiB for an array with shape (759926, 3935) and data type float32

### ISSUE THREAD

**Issue by akashg116414** [pycaret/pycaret#1477] opened 2021-07-28 04:29 UTC
got this error in pycaret==2.3.0 
Error: Unable to allocate 11.1 GiB for an array with shape (759926, 3935) and data type float32

**Comment by IncubatorShokuhou** [comment] 2021-07-28 07:30
Can you show a demo script to help us reproduce it?

**Comment by akashg116414** [comment] 2021-08-02 10:07
[error.zip](https://github.com/pycaret/pycaret/files/6916106/error.zip)
i have uploaded zip file for example notebook and dataset

**Comment by moezali1** [comment] 2021-08-07 16:22
@akashg116414 You are also passing `Loan ID` and `Customer ID` in the `setup` that's causing your memory limit. Replace the `setup` function in your Notebook with the following:

```
setup(data=data,target="Bankruptcies",train_size=0.8, ignore_features = ['Loan ID', 'Customer ID'])
```

This will work. Please close the issue if this resolves your problem.

**Comment by akashg116414** [comment] 2021-08-10 04:38
the idea is not ignore this feature, this is more trying to ignore the issue rather than fixing it. the work around is not convincing, as we will have such string based features which cannot be ignored and this was also a work around, which i have tried even before you have suggested this.

**Comment by harsh204016** [comment] 2021-08-10 13:39
I got this type of error for features which are having 15k unique values , so after removing those features it works fine. 
So, I think there must be some constrain in the number of unique values of the features..

**Comment by wkuopt** [comment] 2021-08-17 03:45
@akashg116414 the issue here is that you have too many unique values for those two features, which requires lots of memory to encode them into numerical form. To address this issue, there are several options:
1. Check if it really makes sense to include those 2 features - Do you really want the model to learn based on IDs? Wouldn't that cause overfitting which is not a desired outcome?
2. Use a computing resource with more RAM.
3. Use another categorical encoding technique to save the space. I assume you are using one-hot encoding?
4. Create groups to reduce the number of unique values in these two features.

**Comment by moezali1** [comment] 2021-08-28 14:22
@akashg116414 Do you really want to use ID column in training your machine learning model? For this instance, that's exactly the problem is and that's what I pointed out to. 

If you really have a situation where your categorical feature have so many distinct values and you have memory limitation you can try this:

```
setup(data=data,target="Bankruptcies",train_size=0.8, high_cardinality_features = ['name_of_feature'])
```

![image](https://user-images.githubusercontent.com/54699234/131221059-b8299f4f-7f41-43ab-b46c-8166baa9f749.png)

Documentation: https://pycaret.readthedocs.io/en/latest/api/classification.html

Hope this helps.

**Closed by moezali1** 2021-08-28 14:22 UTC
Labels: invalid

**Comment by akashg116414** [comment] 2021-08-30 10:25
Thanks for the workaround
