### ISSUE TITLE
[BUG]: Most recent Master version shows all metrics as 0

### ISSUE THREAD

**Issue by reza1615** [pycaret/pycaret#3007] opened 2022-09-30 16:07 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

I installed pycaret as pip install -U git+https://github.com/pycaret/pycaret.git@master and it shows most of the metrics as 0
![image](https://user-images.githubusercontent.com/2202483/193310925-7174a1e7-34da-4381-aadb-8cbc7fbcc5fb.png)
,

### Reproducible Example

```python
normal code
```

### Expected Behavior

before the update it was

![image](https://user-images.githubusercontent.com/2202483/193311142-66ad0b8a-f7c8-4c27-8d03-371c230adb92.png)

### Actual Results

```python-traceback
normal code
```

### Installed Versions

![image](https://user-images.githubusercontent.com/2202483/193311663-d2a0c326-e8f4-4860-9303-58c58344d9b9.png)

**Comment by celestinoxp** [comment] 2022-09-30 22:00
You have updated from 2.x to 3.x version?

**Comment by reza1615** [comment] 2022-09-30 23:40
yes before that I worked with 2.3.10
I just updated pycaret without changing code or data

**Comment by celestinoxp** [comment] 2022-10-01 09:14
I think when upgrading from version 2.x to 3.x some files from version 2.x stay in folders and then create conflicts in version 3.

My suggestion: use `pip uninstall pycaret` to delete pycaret completely and then use `pip install --pre pycaret -U` or the latest version on GitHub `pip install -U git+https://github.com/pycaret/pycaret.git@master`

See if it works now. If so, you can close this issue.

**Comment by reza1615** [comment] 2022-10-01 14:05
I install pycaret on databases notebook every time the notebook temporary install it after detaching it will remove

**Comment by moezali1** [comment] 2022-10-01 16:45
@reza1615 Can you please upload a reproducible notebook with data so that we can reproduce the error?

**Comment by reza1615** [comment] 2022-10-01 20:04
Unfortunately I can not upload the dataset it is confential data.

**Comment by ngupta23** [comment] 2022-10-02 15:17
Can you create mock data to reproduce the problem?

**Comment by ngupta23** [comment] 2022-11-05 14:57
Closing due to missing info. Feel free to send the reproducible example and reopen this.

**Closed by ngupta23** 2022-11-05 14:57 UTC
Labels: bug, missing_info
