### ISSUE TITLE
[BUG]: finalize_model and/or predict_model with strange behaviour 

### ISSUE THREAD

**Issue by EdgarEAM** [pycaret/pycaret#3497] opened 2023-04-21 02:19 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

I experience an error running predict_model with a estimator of  finalize_model its apparently due features names unseen at fit time and also features names seen at fit time but missing for predict. 

predict_model with estimator=best (compare_models() works, also if polynomial_features is set to false it works predict model from a finalized model. I suspect its something about finalize_model or predict_model, however cant figure out

Upload data bellow
[test.csv](https://github.com/pycaret/pycaret/files/11291719/test.csv)

### Reproducible Example

```python
import pycaret
import pandas as pd
## Load Data
data = pd.read_csv("test.csv")
from pycaret.regression import *
s = setup(data, feature_selection=True,feature_selection_method="univariate", 
          n_features_to_select=5,target = 'obj', polynomial_features=True,session_id = 123)
best = compare_models()
final_model = finalize_model(estimator=best)
predict_model(estimator=final_model);
```

### Expected Behavior

Predict model from a finalized model

### Actual Results

```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_19744\2722133075.py in <cell line: 1>()
----> 1 predict_model(estimator=final_model);

~\anaconda3\envs\PyC3_0_0Full\lib\site-packages\pycaret\regression\functional.py in predict_model(estimator, data, round, verbose)
   1925         experiment = _EXPERIMENT_CLASS()
   1926 
-> 1927     return experiment.predict_model(
   1928         estimator=estimator,
   1929         data=data,

~\anaconda3\envs\PyC3_0_0Full\lib\site-packages\pycaret\regression\oop.py in predict_model(self, estimator, data, round, verbose)
   2219         """
   2220 
-> 2221         return super().predict_model(
   2222             estimator=estimator,
   2223             data=data,

~\anaconda3\envs\PyC3_0_0Full\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py in predict_model(self, estimator, data, probability_threshold, encoded_labels, raw_score, round, verbose, ml_usecase, preprocess)
   4971             estimator = get_estimator_from_meta_estimator(estimator)
   4972 
-> 4973         pred = np.nan_to_num(estimator.predict(X_test_))
   4974         pred = pipeline.inverse_transform(pred)
   4975         # Need to convert labels back to numbers

~\anaconda3\envs\PyC3_0_0Full\lib\site-packages\sklearn\linear_model\_base.py in predict(self, X)
    352             Returns predicted values.
    353         """
--> 354         return self._decision_function(X)
    355 
    356     def _set_intercept(self, X_offset, y_offset, X_scale):

~\anaconda3\envs\PyC3_0_0Full\lib\site-packages\sklearn\linear_model\_base.py in _decision_function(self, X)
    335         check_is_fitted(self)
    336 
--> 337         X = self._validate_data(X, accept_sparse=["csr", "csc", "coo"], reset=False)
    338         return safe_sparse_dot(X, self.coef_.T, dense_output=True) + self.intercept_
    339 

~\anaconda3\envs\PyC3_0_0Full\lib\site-packages\sklearn\base.py in _validate_data(self, X, y, reset, validate_separately, **check_params)
    546             validated.
    547         """
--> 548         self._check_feature_names(X, reset=reset)
    549 
    550         if y is None and self._get_tags()["requires_y"]:

~\anaconda3\envs\PyC3_0_0Full\lib\site-packages\sklearn\base.py in _check_feature_names(self, X, reset)
    479                 )
    480 
--> 481             raise ValueError(message)
    482 
    483     def _validate_data(

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- VAR00005 VAR00007
Feature names seen at fit time, yet now missing:
- VAR00002
```

### Installed Versions

<details>
'3.0.0'
</details>

**Comment by tvdboom** [comment] 2023-04-22 09:30
I think this bug is fixed in `master`. Could you try installing from there and giving it a try?

**Comment by EdgarEAM** [comment] 2023-04-22 16:05
Tested in master however same results.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[6], line 1
----> 1 predict_model(estimator=final_model)

File ~\anaconda3\envs\PyCMaster4_22\lib\site-packages\pycaret\regression\functional.py:1927, in predict_model(estimator, data, round, verbose)
   1924 if experiment is None:
   1925     experiment = _EXPERIMENT_CLASS()
-> 1927 return experiment.predict_model(
   1928     estimator=estimator,
   1929     data=data,
   1930     round=round,
   1931     verbose=verbose,
   1932 )

File ~\anaconda3\envs\PyCMaster4_22\lib\site-packages\pycaret\regression\oop.py:2221, in RegressionExperiment.predict_model(self, estimator, data, round, verbose)
   2166 def predict_model(
   2167     self,
   2168     estimator,
   (...)
   2171     verbose: bool = True,
   2172 ) -> pd.DataFrame:
   2174     """
   2175     This function predicts ``Label`` using a trained model. When ``data`` is
   2176     None, it predicts label on the holdout set.
   (...)
   2218 
   2219     """
-> 2221     return super().predict_model(
   2222         estimator=estimator,
   2223         data=data,
   2224         probability_threshold=None,
   2225         encoded_labels=False,
   2226         round=round,
   2227         verbose=verbose,
   2228     )

File ~\anaconda3\envs\PyCMaster4_22\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py:4973, in _SupervisedExperiment.predict_model(self, estimator, data, probability_threshold, encoded_labels, raw_score, round, verbose, ml_usecase, preprocess)
   4970         probability_threshold = estimator.probability_threshold
   4971     estimator = get_estimator_from_meta_estimator(estimator)
-> 4973 pred = np.nan_to_num(estimator.predict(X_test_))
   4974 pred = pipeline.inverse_transform(pred)
   4975 # Need to convert labels back to numbers
   4976 # TODO optimize

File ~\anaconda3\envs\PyCMaster4_22\lib\site-packages\sklearn\linear_model\_base.py:354, in LinearModel.predict(self, X)
    340 def predict(self, X):
    341     """
    342     Predict using the linear model.
    343 
   (...)
    352         Returns predicted values.
    353     """
--> 354     return self._decision_function(X)

File ~\anaconda3\envs\PyCMaster4_22\lib\site-packages\sklearn\linear_model\_base.py:337, in LinearModel._decision_function(self, X)
    334 def _decision_function(self, X):
    335     check_is_fitted(self)
--> 337     X = self._validate_data(X, accept_sparse=["csr", "csc", "coo"], reset=False)
    338     return safe_sparse_dot(X, self.coef_.T, dense_output=True) + self.intercept_

File ~\anaconda3\envs\PyCMaster4_22\lib\site-packages\sklearn\base.py:548, in BaseEstimator._validate_data(self, X, y, reset, validate_separately, **check_params)
    483 def _validate_data(
    484     self,
    485     X="no_validation",
   (...)
    489     **check_params,
    490 ):
    491     """Validate input data and set or check the `n_features_in_` attribute.
    492 
    493     Parameters
   (...)
    546         validated.
    547     """
--> 548     self._check_feature_names(X, reset=reset)
    550     if y is None and self._get_tags()["requires_y"]:
    551         raise ValueError(
    552             f"This {self.__class__.__name__} estimator "
    553             "requires y to be passed, but the target y is None."
    554         )

File ~\anaconda3\envs\PyCMaster4_22\lib\site-packages\sklearn\base.py:481, in BaseEstimator._check_feature_names(self, X, reset)
    476 if not missing_names and not unexpected_names:
    477     message += (
    478         "Feature names must be in the same order as they were in fit.\n"
    479     )
--> 481 raise ValueError(message)

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- VAR00005 VAR00007
Feature names seen at fit time, yet now missing:
- VAR00002

**Comment by tvdboom** [comment] 2023-04-22 19:08
You are right, I see what's happening. It's not a bug.

When you call predict_model without providing data, pycaret uses the data transformed by the internal pipeline (`s.pipeline`) and feed that to the final estimator of `final_model`. But this doesn't work since the internal pipeline is not fitted on the same data as the `final_model` pipeline (the former is fitted only on the training set and the latter on the complete dataset). What you need to do is call predict_model and provide the data you want to predict yourself, e.g. `predict_model(final_model, data=s.X_test)

**Comment by EdgarEAM** [comment] 2023-04-22 21:33
Understand. Nevertheless, `predict_model(estimator=final_model, data=s.X_test)` doesn't return error metrics, just show predictions as per se

The following code allowed return error metrics,```

X_test = get_config(variable="X_test").reset_index().drop(["index"], axis=1)
y_test = get_config(variable="y_test").reset_index().drop(["index"], axis=1)["obj"]
df_test = X_test.copy()
df_test["label"] = y_test
predict_model(estimator=final_model, data=df_test
             )
```
Isn't a desirable behavior that if data isn't provided in predict_model Pycaret chooses data=s.X_test from setup?

**Comment by tvdboom** [comment] 2023-04-23 08:24
> Isn't a desirable behavior that if data isn't provided in predict_model Pycaret chooses data=s.X_test from setup?

That's more or less what happens. When `data` is not provided, pycaret uses `s.X_test_transformed`. The reason to take the transformed dataset is to avoid having to recalculate the preprocessing steps. This works great when using predict_model with a model returned by create_model, but that's also the reason the code fails if you don't add the `data` parameter using a model from finalize_model. Here, the pipeline differs from the one in setup.

**Comment by tvdboom** [comment] 2023-04-23 08:28
Also. Error metrics are showed when you provide a target column with `data`. So you can do this as well (it's simpler): `predict_model(estimator=final_model, data=s.test)`

**Comment by EdgarEAM** [comment] 2023-04-23 15:19
Your help was so valuable, thank u

Additional, maybe will be useful make tutorials or update readthedocs noticing users to avoid this possible mistake?
With nothing else for now, u can close this thread

**Closed** 2023-04-23 17:04 UTC
Labels: bug, prediction
