### ISSUE TITLE
Unable to install Pycaret

### ISSUE THREAD

**Issue by yogesh5c4** [pycaret/pycaret#109] opened 2020-05-07 04:53 UTC
Description
While trying to install Pycaret package, I am getting the below error :
ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\Users\SasanapY\AppData\Local\Continuum\anaconda3\Anaconda64bit\Library\bin\tbbmalloc.dll'
Consider using the --user option or check the permissions.

Expected behavior:
I expected to install pycaret package
Actual behavior:
Got the error : ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\Users\SasanapY\AppData\Local\Continuum\anaconda3\Anaconda64bit\Library\bin\tbbmalloc.dll'
Consider using the --user option or check the permissions.

Versions
OS - Windows 10
Python Version - 3.7.4g the pycaret, I got the below

**Comment by yogesh5c4** [comment] 2020-05-07 06:42
I am getting below error after fixing the above error :
SystemExit: (Type Error): spacy english model is not yet downloaded. See the documentation of setup to see installation guide.

**Comment by DaGuT** [comment] 2020-05-07 11:23
Run in console in your enviroment
`python -m spacy download en_core_web_sm`

It'll load the english model and should work

**Comment by yogesh5c4** [comment] 2020-05-07 11:37
Hi After loading spacy for english, I ran below code : 

```
import en_core_web_sm
nlp = en_core_web_sm.load()
```

It worked..but when I run below code..its again generating error : 

**Code :** 
```
from pycaret.nlp import *
nlp1=setup(data,target='en',session_id=123)
```

**ERROR:**
root:Internal Python error in the inspect module.
Below is the traceback from this internal error.
Traceback (most recent call last):
  File "C:\Users\SasanapY\AppData\Roaming\Python\Python37\site-packages\pycaret\nlp.py", line 115, in setup
    sp = spacy.load('en_core_web_sm', disable=['parser', 'ner'])
  File "C:\Users\SasanapY\AppData\Roaming\Python\Python37\site-packages\spacy\__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "C:\Users\SasanapY\AppData\Roaming\Python\Python37\site-packages\spacy\util.py", line 169, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SasanapY\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-79-f2eeff8925ab>", line 2, in <module>
    nlp1=setup(data,target='en',session_id=123)
  File "C:\Users\SasanapY\AppData\Roaming\Python\Python37\site-packages\pycaret\nlp.py", line 117, in setup
    sys.exit('(Type Error): spacy english model is not yet downloaded. See the documentation of setup to see installation guide.')
SystemExit: (Type Error): spacy english model is not yet downloaded. See the documentation of setup to see installation guide.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SasanapY\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 1151, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "C:\Users\SasanapY\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 319, in wrapped
    return f(*args, **kwargs)
  File "C:\Users\SasanapY\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 353, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "C:\Users\SasanapY\Anaconda3\lib\inspect.py", line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'





An exception has occurred, use %tb to see the full traceback.

---------------------------------------------------------------------------

During handling of the above exception, another exception occurred:

SystemExit: (Type Error): spacy english model is not yet downloaded. See the documentation of setup to see installation guide.

**Comment by DaGuT** [comment] 2020-05-07 11:48
Hm... That's weird.

Please, try
`python -m spacy download en`

Will it solve the issue?

**Comment by yogesh5c4** [comment] 2020-05-07 11:51
> Hm... That's weird.
> 
> Please, try
> `python -m spacy download en`
> 
> Will it solve the issue?
> 
> __
> 
> Forget it, I read logs properly, that will not help.

Any other solution to think about?

**Comment by DaGuT** [comment] 2020-05-07 11:52
Yes,
`https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz`

This helped some people

**Comment by DaGuT** [comment] 2020-05-07 11:59
If you are running python notebook, then you can add
`!pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz` at the beginning. This might install it under correct enviroment.

**Comment by yogesh5c4** [comment] 2020-05-07 11:59
> pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz

I tried that option already and it didnt work out

**Comment by yogesh5c4** [comment] 2020-05-07 12:00
> If you are running python notebook, then you can add
> `!pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz` at the beginning. This might install it under correct enviroment.

ok let me try this

**Comment by DaGuT** [comment] 2020-05-07 12:04
yet another suggestion:

`pip install --user https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz`

I'm just not good at anaconda things (I was never using it, so no idea how that works with storing packages for different enviroments), so if you fixed the first problem with adding --user (and I'm almost certain you did that), package was not installed under conda and is being loaded from user instead. But with everything I suggested before, it was installing under conda, but since pycaret is installed under used it tries to find english model under user and ofc it does not find it since it's in conda env.

It's just a suggestion that I just made up myself. So try the command from this message

**Comment by yogesh5c4** [comment] 2020-05-07 12:08
> yet another suggestion:
> 
> `pip install --user https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz`
> 
> I'm just not good at anaconda things (I was never using it, so no idea how that works with storing packages for different enviroments), so if you fixed the first problem by adding --user (and I'm almost certain you did that), package was not installed under conda and is being loaded from user instead. But with everything I suggested before, it was installing under conda, but since pycaret is installed under used it tries to find english model under user and ofc it does not find it since it's in conda env.
> 
> It's just a suggestion that I just made up myself. So try the command from this message

No difference...I have tried all options now and still the same issue persists..

**Comment by DaGuT** [comment] 2020-05-07 12:15
> No difference...I have tried all options now and still the same issue persists..
Just to make sure, there was '--user' added. Did you try with that?

Anyway, I suggest to reboot your computer first, then create new enviroment and install everything again without --user (I think that's the cause of the problem).
Also, when you open your cmd, run it with administrator privileges (right click -> run as admin)

**Comment by yogesh5c4** [comment] 2020-05-07 12:20
> > No difference...I have tried all options now and still the same issue persists..
> 
> Just to make sure, there was '--user' added. Did you try with that?
> 
> Anyway, I suggest to reboot your computer first, then create new enviroment and install pycaret again without --user (I think that's the cause of the problem).
> Also, when you open your cmd, run it with administrator privileges (right click -> run as admin)

I tried with --user added and downloaded in anaconda prompt and as well in jupyter notebook...But it didnt worked still

**Comment by DaGuT** [comment] 2020-05-07 12:21
>Anyway, I suggest to reboot your computer first, then create new enviroment and install pycaret again without --user (I think that's the cause of the problem).
Also, when you open your cmd, run it with administrator privileges (right click -> run as admin)

Please, try it :)

**Comment by yogesh5c4** [comment] 2020-05-07 12:41
> > Anyway, I suggest to reboot your computer first, then create new enviroment and install pycaret again without --user (I think that's the cause of the problem).
> > Also, when you open your cmd, run it with administrator privileges (right click -> run as admin)
> 
> Please, try it :)
> 
> Also, if
> 
> ```
> import spacy
> nlp = spacy.load('en_core_web_sm')
> ```
> 
> works, then I'm correct, that pycaret is trying to load spacy model from a different place and that's the cause of your problem. (there is a difference with how you tried to check if the moedl works)

Now everything is working fine..One more question to add here..How to define topic number?

**Comment by DaGuT** [comment] 2020-05-07 12:54
Sorry idk. I really have not used the package yet. I was just asked to make it work by my chief (there was a bug) xD and after that I'm here. @pycaret ,
>How to define topic number while performing topic modelling operation? Any idea?
:DDD
__
Glad that everything worked.

**Comment by pycaret** [comment] 2020-05-08 19:23
@DaGuT and @yogesh5c4 

Hi. sorry for late response. The number of topics can be defined using num_topics parameter within create_model. 

Check https://pycaret.org/nlp/ for more details.

@DaGuT You can close this issue if the original question of installation is already addressed, which I believe is done. Thanks for your help.

**Comment by DaGuT** [comment] 2020-05-10 14:12
I cant close issues :)

but yeah, @yogesh5c4 close the issue, pls

**Comment by Spartacus8080** [comment] 2020-05-11 07:35
import en_core_web_sm
nlp = en_core_web_sm.load()

**Closed** 2020-05-11 07:37 UTC
Labels: good first issue

**Comment by harsh204016** [comment] 2021-08-19 19:06
I am trying 
`pip install pycaret`
```
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 

'C:\\Users\\harsh\\AppData\\Roaming\\Python\\Python38\\site-packages\\~klearn\\.libs\\vcomp140.dll'
Check the permissions.
```
Windows 10 
python 3.8.6 
@DaGuT @yogesh5c4 @pycaret

**Comment by MukulKirtiVerma** [comment] 2021-10-06 11:41
run this in os consol: 
python -m spacy download en
python -m spacy link en en_core_web_sm

then run this in python console or on your python IDE:
import spacy
spacy.load('en_core_web_sm')
