### ISSUE TITLE
3.0.0.rc2 - Hourly data missing imputation error on time_series module 

### ISSUE THREAD

**Issue by tugra-alp** [pycaret/pycaret#2642] opened 2022-06-07 11:34 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

I havemissing values in data. However, when i set the 'numeric_imputation_target' on setup part, it doesnt work.

### Reproducible Example

```python
s = setup(data=real_time_consumption, verbose=True, fh=3, session_id=42)
```

### Expected Behavior

.

### Actual Results

```python-traceback
ValueError: 
Time Series modeling automation relies on running statistical tests, plots, etc.
Many of these can not be run when data has missing values. 
Your target has 7 missing values and `numeric_imputation_target` is set to `None`. 
Please enable imputation to proceed.
```

### Installed Versions

<details>
Replace this line with the output of the version code above.
</details>

**Comment by ngupta23** [comment] 2022-06-07 11:39
So the error message is explaining what needs to be done here. The issue is not with the hourly data per se, but with the fact that you have missing values. You will need to enable imputation in setup to overcome this. Check out the 200 series notebooks here for details:

https://github.com/pycaret/pycaret/tree/master/examples/time_series/forecasting

**Comment by ngupta23** [comment] 2022-06-07 12:54
I will close this for now, but feel free to reopen if the issue persists or if you have follow up questions.

**Closed by ngupta23** 2022-06-07 12:54 UTC
Labels: time_series, preprocessing, impute
