### ISSUE TITLE
[BUG] Numpy Versioning incompatibility

### ISSUE THREAD

**Issue by NaelsonDouglas** [pycaret/pycaret#1574] opened 2021-09-15 02:14 UTC
**Describe the bug**
Numpy is [pinned on version 1.19.5](https://github.com/pycaret/pycaret/commit/c198f0f720800e05b04b7633fc676a59bc7845f5), but several other dependencies have their own version pinning for Numpy and specially on the case of **yellowbrick**, there's a conflict going on.

If we just call 'pip install -r requirements.txt', this error will not appear, but on the other hand, we will have a version overwrite and we might be breaking one of the dependencies.
This problem gets on the spot when we use a version control tool like [pip-tools](https://github.com/jazzband/pip-tools/)(which is a good practice), where in this case pip-tools will warn us about the conflict and we won't be able to install Pycaret.

**To Reproduce**
1: Create and activate a virtual env
2: Install pip-tools
3: Create a file called 'requirements.in'
4: Adde the line 'pycaret' into the requirements.in file
4: call 'pip-compile -v'

**Expected behavior**
We should use a pinning tool, like pip-tools, to generate our requirements.txt file instead of creating it manually.

**Additional context**
This is the error message we get when trying to install pycaret via pip-tools.
```bash
There are incompatible versions in the resolved dependencies:
  **numpy==1.19.5 (from -r requirements.in (line 1))**
  numpy>=1.10.4 (from Boruta==0.3->pycaret==2.3.0->-r requirements.in (line 2))
  numpy>=1.13.3 (from scikit-learn==0.23.2->pycaret==2.3.0->-r requirements.in (line 2))
  numpy>=1.14.5 (from scipy==1.5.4->pycaret==2.3.0->-r requirements.in (line 2))
  numpy>=1.9.2 (from cufflinks==0.17.3->pycaret==2.3.0->-r requirements.in (line 2))
  numpy>=1.10.4 (from kmodes==0.11.0->pycaret==2.3.0->-r requirements.in (line 2))
  numpy (from lightgbm==3.2.1->pycaret==2.3.0->-r requirements.in (line 2))
  numpy>=1.17.3 (from pandas==1.3.3->pycaret==2.3.0->-r requirements.in (line 2))
  numpy>=1.17 (from umap-learn==0.5.1->pycaret==2.3.0->-r requirements.in (line 2))
  numpy>=1.13 (from pyod==0.9.3->pycaret==2.3.0->-r requirements.in (line 2))
  **numpy<1.20,>=1.16.0 (from yellowbrick==1.3.post1->pycaret==2.3.0->-r requirements.in (line 2))**
  numpy>=1.6.1 (from wordcloud==1.8.1->pycaret==2.3.0->-r requirements.in (line 2))
  numpy>=1.16 (from matplotlib==3.4.3->pycaret==2.3.0->-r requirements.in (line 2))
  numpy (from mlflow==1.20.2->pycaret==2.3.0->-r requirements.in (line 2))
  numpy>=1.16.2 (from mlxtend==0.19.0->pycaret==2.3.0->-r requirements.in (line 2))
  **numpy==1.19.5 (from pycaret==2.3.0->-r requirements.in (line 2))**
  numpy>=1.16.0 (from pandas-profiling==3.0.0->pycaret==2.3.0->-r requirements.in (line 2))
  numpy>=1.20.0 (from pyLDAvis==3.3.1->pycaret==2.3.0->-r requirements.in (line 2))
  numpy>=1.13.3 (from imbalanced-learn==0.8.0->pycaret==2.3.0->-r requirements.in (line 2))
  numpy>=1.17.0 (from gensim==4.1.1->pycaret==2.3.0->-r requirements.in (line 2))
  numpy>=1.15 (from seaborn==0.11.2->pycaret==2.3.0->-r requirements.in (line 2))
  numpy>=1.15.0 (from spacy==2.3.7->pycaret==2.3.0->-r requirements.in (line 2)
```

**Versions**
Python 3.9.5
Pycaret 2.3.3

**OS Info**
NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.10"
VERSION_ID="19.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan

**Comment by souravjamwal77** [comment] 2021-09-17 01:42
@NaelsonDouglas You can check the issue# 1573 [Here](https://github.com/pycaret/pycaret/issues/1573#issuecomment-919162086) for NumPy related issue. 
Duplicate of #1573

**Comment by NaelsonDouglas** [comment] 2021-09-21 16:16
> @NaelsonDouglas You can check the issue# 1573 [Here](https://github.com/pycaret/pycaret/issues/1573#issuecomment-919162086) for NumPy related issue.
> Duplicate of #1573

Oh, thanks.

So it's safe to close this issue, right?

**Comment by moezali1** [comment] 2021-09-23 19:38
@Yard1 @ngupta23 @tvdboom @wkuopt @IncubatorShokuhou Do you guys have any thoughts on this?

**Closed** 2021-12-04 14:19 UTC
Labels: bug
