### ISSUE TITLE
Documentation : add source reference for included datasets

### ISSUE THREAD

**Issue by lusis-ai** [pycaret/pycaret#816] opened 2020-11-06 16:30 UTC
While some datasets are well known, it's not the case for all of them, so it could be very helpful to have the source reference of each dataset to enable quickly getting features descriptions.

**Comment by pycaret** [comment] 2020-11-06 17:12
@lusis-ai This issue has been brought in the past several times. The problem is we haven't got anyone who would be willing to put time and add sources to the datasets. Many have committed but none of them actually worked. Will you be willing to work on this and add sources to available datasets?

**Comment by rajpratyush** [comment] 2021-01-26 08:27
@pycaret I want to work on this. Please assign me this issue

**Comment by pycaret** [comment] 2021-01-26 19:42
@rajpratyush Sure. I am assigning it to you. Thanks for your help.

**Comment by rajpratyush** [comment] 2021-01-27 03:40
@pycaret Do I have to add the source link in each dataset?

**Comment by rajpratyush** [comment] 2021-01-28 05:00
please guide me @pycaret

**Comment by rajpratyush** [comment] 2021-02-02 17:01
@pycaret please respond to my query

**Comment by rajpratyush** [comment] 2021-02-11 14:49
@yard1 @pycaret Do I have to add the source link in each dataset? or just add a new column "source" in index.csv.

**Comment by pycaret** [comment] 2021-02-11 22:52
@rajpratyush Adding a source column in index.csv will be a good approach.

**Comment by ngupta23** [comment] 2021-05-13 13:47
@rajpratyush Are you still working on this?

**Comment by rajpratyush** [comment] 2021-05-13 13:49
I had some doubts on this pls clear them and i shall push a pr within 12 hours

**Closed** 2021-07-21 02:13 UTC
Labels: documentation, no-issue-activity
