### ISSUE TITLE
[BUG]: Long runtime for Pycaret setup function on large dataset

### ISSUE THREAD

**Issue by tahaflex** [pycaret/pycaret#3371] opened 2023-03-07 20:00 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

When running PyCaret's setup function on a dataset with 0.8 million rows and 29 features, which include 10 categorical, 14 numerical, 1 date feature and 4 ordinal features, the function takes more than 2.5 hours to complete. This is extremely slow and makes the usage of PyCaret impractical for large datasets.

### Reproducible Example

```python
Steps to reproduce:

Use a dataset with at least 0.8 million rows and 29 features, including 10 categorical, 14 numerical, 1 date feature and 4 ordinal features.
Run PyCaret's setup function on the dataset.
```

### Expected Behavior

PyCaret's setup function should have reasonable performance when dealing with large datasets with multiple features. in Previous version pycaret 2.3.10 it usually takes 5 mins max.

### Actual Results

```python-traceback
No errors this is the time it takes to run the setup function:
Time taken: 8243.859333276749 seconds
```

### Installed Versions

System:
    python: 3.7.16 (default, Jan 17 2023, 16:06:28) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\Taha\anaconda3\envs\pycaret3rc9\python.exe
   machine: Windows-10-10.0.22621-SP0

PyCaret required dependencies:
                 pip: 22.3.1
          setuptools: 60.10.0
             pycaret: 3.0.0rc9
             IPython: 7.34.0
          ipywidgets: 8.0.4
                tqdm: 4.64.1
               numpy: 1.21.6
              pandas: 1.3.5
              jinja2: 3.1.2
               scipy: 1.7.3
              joblib: 1.2.0
             sklearn: 1.0.2
                pyod: 1.0.7
            imblearn: 0.10.1
   category_encoders: 2.6.0
            lightgbm: 3.3.5
               numba: 0.56.4
            requests: 2.28.2
          matplotlib: 3.5.3
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.13.1
             kaleido: 0.2.1
         statsmodels: 0.13.5
              sktime: 0.16.1
               tbats: 1.1.2
            pmdarima: 2.0.2
              psutil: 5.9.4

PyCaret optional dependencies:
                shap: 0.41.0
           interpret: 0.3.0
                umap: 0.5.3
    pandas_profiling: 4.0.0
  explainerdashboard: 0.3.8.2
             autoviz: 0.1.58
           fairlearn: 0.7.0
             xgboost: 1.6.2
            catboost: 1.1.1
              kmodes: Not installed
             mlxtend: Not installed
       statsforecast: Not installed
        tune_sklearn: Not installed
                 ray: Not installed
            hyperopt: 0.2.7
              optuna: 3.1.0
               skopt: 0.9.0
              mlflow: 1.30.0
              gradio: 3.20.0
             fastapi: 0.92.0
             uvicorn: 0.20.0
              m2cgen: 0.10.0
           evidently: 0.2.6
               fugue: Not installed
           streamlit: Not installed
             prophet: Not installed

**Comment by moezali1** [comment] 2023-03-07 22:45
@tahaflex Is it possible to share the dataset / reproducible notebook so we can investigate what's going wrong here? 

@mavs FYI.

**Comment by tahaflex** [comment] 2023-03-08 06:18
The data is sensitive i cannot share it, but let me try on open dataset with similar properties & will share the code with you.

**Comment by moezali1** [comment] 2023-03-08 17:26
@tahaflex Can you show me your setup code?

**Comment by tahaflex** [comment] 2023-03-08 21:59
Sure here it is: Target Type is muticlass, 

import time
from pycaret.classification import *

start_time = time.time()
model_setup = setup(data = data, target = 'status', session_id=123, train_size=0.70, n_jobs = -1, low_variance_threshold=0, feature_selection = True, n_features_to_select=0.8, create_date_columns= ['day', 'month'], bin_numeric_features=['cost'], remove_multicollinearity = True, numeric_features=['numeric1, numeric2', ........... numeric14], categorical_features=['cat1, cat2, ......... cat10'], normalize=True, group_features=[['g1','g2'], ['g3', 'g4'], ['g5', 'g6'], ['g7', 'g8']], group_names=['mp_mc', 'sd_ca', 'tco_c', 'al_fd'], feature_selection_method='classic', feature_selection_estimator="lightgbm", max_encoding_ohe=10, numeric_imputation='knn')

end_time = time.time()
print(f"Time taken: {end_time - start_time} seconds")

Output:
Original data shape | (866256, 18)
Transformed data shape | (866256, 12)
Transformed train set shape | (606379, 12)
Transformed test set shape | (259877, 12)
Ordinal features | 4
Numeric features | 7
Date features | 1
Categorical features | 9
Rows with missing values | 10.8%
Preprocess | True
Imputation type | simple
Numeric imputation | knn
Categorical imputation | mode
Maximum one-hot encoding | 10
Encoding method | None
Low variance threshold | 0
Remove multicollinearity | True
Multicollinearity threshold | 0.900000
Feature selection | True
Feature selection method | classic
Feature selection estimator | lightgbm
Number of features selected | 0.700000
Fold Generator | StratifiedKFold
Fold Number | 10
CPU Jobs | -1
Use GPU | False
Log Experiment | False
Experiment Name | clf-default-name
USI | 0081

Time taken: 12827.133962392807 seconds (3.5 Hours)

Tried on Vertex AI jupyterlab with 8vCPUs, 52GB RAM, also on my local windows 11 laptop i7 11Gen 16GB RAM,
python 3.8 & 3.7 throws error "ValueError: Cannot cast object dtype to float64", though works fine on python 3.7. Also after running setup functions multiple times without restarting the kernel it take about 120GB of temp local C: space on my laptop i need to manually delete %temp% files, didn't faced any of the issue in Pycaret 2.3.10 version.

**Comment by tahaflex** [comment] 2023-03-09 09:56
I tried without it on different target variable without any imputation technique used, it still took 2.25Hours, also for no reason if i continuously rerun the setup function multiple times without restarting the kernel, it uses 100GB of Local storage from my C drive, i need to manually clean the from %temp% folder.

**Comment by tvdboom** [comment] 2023-03-09 10:17
strange. I really need some data to be able to reproduce the issue. I can't properly debug without.

Regarding the memory issue, the pipeline caches some transformation steps in the temp folder but it shouldn't be that large... How large is the original dataset? @Yard1 any ideas?

**Comment by moezali1** [comment] 2023-03-11 15:40
@tahaflex Can you try setting `memory=False` in the `setup`?

**Comment by Yard1** [comment] 2023-03-11 20:03
If you keep rerunning the setup, then it will create a separate cache each time. I'll see if I can add some cleanup to avoid this.

**Comment by tahaflex** [comment] 2023-03-12 11:04
@moezali1 @Yard1 When setting memory=False, & remove knn as imputation technique as i imputed missing values manually, setup function runtime drops to 40 minutes from 3.5 Hours, but still in previous version i.e 2.3.10 setup function usually takes minute or 2, not sure if category encoders taking time or something else, apart from this when pulling the transformed dataset with X_train = get_config('X_train_transformed'), sometimes it takes seconds sometime even 10, 12 minutes not sure why.

**Comment by ahmedhindi** [comment] 2023-03-13 07:31
I have the same problem and i tried many datasets I even used a dataset that's less than 1000 rows.

**Comment by Yard1** [comment] 2023-03-15 02:51
@ahmedhindi can you share any of those datasets?

**Comment by moezali1** [comment] 2023-03-15 17:42
@tahaflex @ahmedhindi In order to understand what is causing this, we really need your help. Can one of you please share the notebook with the data for us to investigate what is causing this?

**Comment by ahmedhindi** [comment] 2023-03-15 18:09
Solved the problem sorry. it was an mlflow server problem not related to pycaret

**Comment by ngupta23** [comment] 2023-03-18 14:43
@tahaflex , If you are not able to share the data, my recommendation would be to disable all preprocessing and then enable them one at a time and try the setup. Then figure out what step in preprocessing is causing the problem. 

We will go ahead and close this issue for now, but if you are able to figure that out, please open a new issue with the details and we can look at it at that time.

**Closed by ngupta23** 2023-03-18 14:43 UTC
Labels: bug, priority_high

**Comment by ngupta23** [comment] 2023-03-23 13:51
```
Databricks uses MLflow by default
```

What happens if you use `log_experiment = False` in setup? Does it change?

Also, can you try to recreate this problem outside Databricks (maybe local notebook setup)? It will help narrow down the issue?

**Comment by tvdboom** [comment] 2023-03-23 14:40
I know Databricks' autologging (see https://docs.databricks.com/mlflow/databricks-autologging.html) is a very annoying feature. Try running this before running pycaret.
```
import mlflow
mlflow.autolog(disable=True)
```

**Comment by ngupta23** [comment] 2023-03-23 22:57
```
Don't know if related but mine was stuck on setup with a dataset of size 30k x 100. Using a integer index instead of DatetimeIndex solved it for me.
```

Were you extracting any datetime features? Can you provide a reproducible example (code + dataset)?

**Comment by moezali1** [comment] 2023-03-24 02:45
@mocnikchain I tried to reproduce this with exact commands in your `setup` and the same shape dataframe (300,000 x 17).

The setup finishes in 25 seconds. I am using Colab. Here is the link to the notebook: https://colab.research.google.com/drive/1kMP8RKcOMru3JlULwCM9bjfz1MrLrpG5?usp=sharing

Can you point out if I am doing anything wrong?

**Comment by georgeannie** [comment] 2023-03-27 21:31
Hi,
I am experiencing the same thing. Pycaret 3 is extremely slow. I have been using pycaret 2.3.10 for sometime to model a data set containing 200 rows and 10 columns. I have not changed anything in the setup from version 2.3.10 to 3.0.0. The setup takes a while in version 3.0.0 but still gets through. However a simple linear regression (not a forecasting problem) is taking more than 14 mins which was taking just less than a min in version 2.3.10.

The setup is as follows
setup(target:= 'XXX',
    train_size=0.95,
    fold_strategy='kfold',
    remove_multicollinearity= False,
    data_split_shuffle:=False,
    data_split_stratify:=False,
    remove_outliers:=True,
    outliers_threshold= 0.05,
    transformation=True,
    transform_target=True,
    normalize=True,
    normalize_method='minmax',
    fold= 10,
    session_id= 123,
    ignore_features= ['1', '2', '3', '4'])

The model
create_model('lr' , verbose=False)

Please help

**Comment by mocnikchain** [comment] 2023-03-28 06:37
Thank you @Ridvanz and @moezali1,  using a integer index instead of DatetimeIndex makes setup finish in 16sec.

**Comment by microlei** [comment] 2023-03-31 19:36
Hello I am having similar problems of long runtime for Pycaret setup. I actually get an error when I run my full 200k+ column dataframe. It completes in ~30 seconds when it's 1000 columns and hangs for hours when I've increased it to 5k. I've reprinted my jupyter notebook code and a link to the external file on [pastebin](https://pastebin.com/ZqbsZX7V). I've tried this on my macbook and on an HPC with more GB of RAM.

```python
import pycaret
import pandas as pd
import numpy as np
```
```python
# Set the dimensions of the DataFrame
n_rows = 928
n_cols = 208334
# Create a list of the possible values
values = [0, 1, "."]
# Create a numpy array with the specified dimensions and fill it with random values from the list
data = np.random.choice(values, size=(n_rows, n_cols))
# Create a DataFrame from the numpy array
df = pd.DataFrame(data)
cgmlst_data = pd.read_csv('data/cgmlst.txt', header=0, squeeze=True, sep='\t')
# Add the cgmlst data as a new column in the DataFrame
df['serovar_cgmlst'] = cgmlst_data
```

```python
from pycaret.classification import *
s = setup(df, target = 'serovar_cgmlst', session_id=123)
```

Error msg when running the full 200k+ column dataframe (this only sometimes happens. Other times it runs for a long time before crashing the kernel or I just give up and restart):
```bash
TypeError                                 Traceback (most recent call last)
Cell In[13], line 2
      1 from pycaret.classification import *
----> 2 s = setup(df, target = 'serovar_cgmlst', session_id=123)

File [~/miniconda3/envs/pycaret/lib/python3.10/site-packages/pycaret/classification/functional.py:603](https://file+.vscode-resource.vscode-cdn.net/Users/lei/Documents/salmonella/ML/~/miniconda3/envs/pycaret/lib/python3.10/site-packages/pycaret/classification/functional.py:603), in setup(data, data_func, target, index, train_size, test_data, ordinal_features, numeric_features, categorical_features, date_features, text_features, ignore_features, keep_features, preprocess, create_date_columns, imputation_type, numeric_imputation, categorical_imputation, iterative_imputation_iters, numeric_iterative_imputer, categorical_iterative_imputer, text_features_method, max_encoding_ohe, encoding_method, rare_to_value, rare_value, polynomial_features, polynomial_degree, low_variance_threshold, group_features, group_names, drop_groups, remove_multicollinearity, multicollinearity_threshold, bin_numeric_features, remove_outliers, outliers_method, outliers_threshold, fix_imbalance, fix_imbalance_method, transformation, transformation_method, normalize, normalize_method, pca, pca_method, pca_components, feature_selection, feature_selection_method, feature_selection_estimator, n_features_to_select, custom_pipeline, custom_pipeline_position, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, html, session_id, system_log, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, verbose, memory, profile, profile_kwargs)
    601 exp = _EXPERIMENT_CLASS()
    602 set_current_experiment(exp)
--> 603 return exp.setup(
    604     data=data,
    605     data_func=data_func,
    606     target=target,
    607     index=index,
    608     train_size=train_size,
    609     test_data=test_data,
    610     ordinal_features=ordinal_features,
    611     numeric_features=numeric_features,
    612     categorical_features=categorical_features,
    613     date_features=date_features,
    614     text_features=text_features,
    615     ignore_features=ignore_features,
    616     keep_features=keep_features,
    617     preprocess=preprocess,
    618     create_date_columns=create_date_columns,
...
--> 637     self._fxs["Ordinal"][name] = list(sorted(column.dropna().unique()))
    638 elif max_encoding_ohe < 0 or n_unique <= max_encoding_ohe:
    639     one_hot_cols.append(name)

TypeError: '<' not supported between instances of 'str' and 'int'
```
System: Darwin
Release: 22.3.0
Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2[/RELEASE_ARM64_T8103]
Machine: arm64
Processor: arm
Architecture: 64bit
Python: 3.10.10

**Comment by tvdboom** [comment] 2023-03-31 20:56
Why are you mixing integers with string values in a column? That's what's causing the error. Try using nan instead of "."

**Comment by ngupta23** [comment] 2023-04-01 15:05
@tvdboom - Is it possible to add a check for this so we flag it as soon as this condition is detected?

**Comment by tvdboom** [comment] 2023-04-03 08:35
Possibly, yes. But before I implement that, there is something else going on. I tried to reproduce the error but wasn't able because the line that errors in the example is never reached since there are three unique values in the column and that line only runs when there are two. @microlei can you share a full reproducible example with dummy data in such a way that I can just copy paste and run?

**Comment by microlei** [comment] 2023-04-03 14:51
Sure, try this code. I tried with the `values = [0,1,999]` and there was no bug, it completed in ~2 minutes. Then, I switched my data fill to `values= ["A", "B", "C"]` because I want my data to be categorical rather than numerical and it's lagging again (20+ minutes). `values = [0,1,np.NaN]` also produced lag. 

```python
import pycaret
import pandas as pd
import numpy as np

# Set the dimensions of the DataFrame
n_rows = 928
n_cols = 208334

# Create a list of the possible values
values = ["A", "B", "C"]
letters = np.array(list('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'))

# Create a numpy array with the specified dimensions and fill it with random values from the list
data = np.random.choice(values, size=(n_rows, n_cols))
labels = np.random.choice(letters, n_rows)

# Create a DataFrame from the numpy array
df = pd.DataFrame(data)
df['labels'] = labels

from pycaret.classification import *
s = setup(df, target = 'labels', session_id=123)
```

**Comment by rarrudaml** [comment] 2023-04-10 10:44
Hi @moezali1 I'm in trouble with setup step. So long to run. I'm using a public https://www.unb.ca/cic/datasets/ids-2017.html dataset with this setup:

`###########################
######
###### Main Module
#####
###########################
###### Packages
import datetime
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from mlflow import *
#from pycaret.classification import *
#import pycaret
from pycaret.classification import setup, compare_models
###########################


def dados_tratar(df):
    
    df.columns = (
    df.columns.str.strip()
              .str.lower()
              .str.replace(' ', '_', regex=False)
              .str.replace('(', '', regex=True)
              .str.replace(')', '', regex=True)
    )
    
    df['flow_bytes/s'] = df['flow_bytes/s'].replace([np.nan,",,"],0)
    df['flow_packets/s'] = df['flow_packets/s'].replace([np.nan,",,"],0)
    df['flow_bytes/s'] = df['flow_bytes/s'].replace([np.inf,",,"],-1)
    df['flow_packets/s'] = df['flow_packets/s'].replace([np.inf,",,"],-1)

    df.loc[df['flow_bytes/s'] == "Infinity", 'flow_bytes/s'] = -1
    df.loc[df['flow_packets/s'] == "Infinity", 'flow_packets/s'] = -1

    df['flow_bytes/s'] = df['flow_bytes/s'].apply(pd.to_numeric) 
    df['flow_packets/s'] = df['flow_packets/s'].apply(pd.to_numeric) 
    
    for i, col in enumerate(df.columns[:-1]):
        df = df.rename(columns={col: f'x{i+1}'})
    
    
    df['label'] = df['label'].apply(lambda x: 0 if x == 'BENIGN' else 1)
    df_train, df_test  =\
                    train_test_split(df,\
                    test_size=0.7, random_state=4, stratify=df['label'])
                    
    return df_train , df_test
                    
        

if __name__ == "__main__":
    # Obtém a hora atual antes da execução do programa
    hora_inicio = datetime.datetime.now()
    print("Loading dataset...")
    #Load Data
    df1=pd.read_csv("./Monday-WorkingHours.pcap_ISCX.csv", low_memory=False)
    df2=pd.read_csv("./Tuesday-WorkingHours.pcap_ISCX.csv", low_memory=False)
    df3=pd.read_csv("./Wednesday-workingHours.pcap_ISCX.csv", low_memory=False)
    df4=pd.read_csv("./Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv", low_memory=False)
    df5=pd.read_csv("./Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv", low_memory=False)
    df6=pd.read_csv("./Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv", low_memory=False)
    df7=pd.read_csv("./Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv", low_memory=False)
    df8=pd.read_csv("./Friday-WorkingHours-Morning.pcap_ISCX.csv", low_memory=False)
    df = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8])
    print(df.shape)
    
    print("Particionando os dados...")
    df_train, df_test  = dados_tratar(df)
    print("Particionando os dados... DONE")
    print("Setando ambientes pycaret...")
    bin_geral = setup(df_train, target = 'label',\
       numeric_imputation=None, \
       numeric_features = ['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10', 'x11', \
       'x12', 'x13', 'x14', 'x15', 'x16', 'x17', 'x18', 'x19', 'x20', 'x21', \
       'x22', 'x23', 'x24', 'x25', 'x26', 'x27', 'x28', 'x29', 'x30', 'x31', \
       'x32', 'x33', 'x34', 'x35', 'x36', 'x37', 'x38', 'x39', 'x40', 'x41', \
       'x42', 'x43', 'x44', 'x45', 'x46', 'x47', 'x48', 'x49', 'x50', 'x51', \
       'x52', 'x53', 'x54', 'x55', 'x56', 'x57', 'x58', 'x59', 'x60', 'x61', \
       'x62', 'x63', 'x64', 'x65', 'x66', 'x67', 'x68', 'x69', 'x70', 'x71', \
       'x72', 'x73', 'x74', 'x75', 'x76', 'x77', 'x78', 'label'])
    print("Setando ambientes pycaret... DONE")
    print("Ajustando modelos...")
    best_model = compare_models()
    print("Ajustando modelos... DONE")
    # Obtém a hora atual após a execução do programa
    hora_fim = datetime.datetime.now()
    
    print("Horário de início:", hora_inicio)
    print("Horário de fim:", hora_fim)`

**Comment by tvdboom** [comment] 2023-04-11 11:43
@microlei I did some debugging. It's not pycaret that's slow but the underlying transformer. In your case, it's the [OneHotEncoder](https://contrib.scikit-learn.org/category_encoders/onehot.html) class from the `category_encoders` library. I guess it's just too expensive to compute the encoding for that many columns. That's also the reason you don't encounter the problem when the values are numerical. In the case of the `np.nan`, the same issue arises with sklearn's `SimpleImputer` class. Not sure how pycaret could help with this. You could try setting `max_encoding_ohe=0` in setup. This will use another, somewhat faster encoding method

**Comment by tahaflex** [comment] 2023-04-11 12:17
@tvdboom @microlei In previous comments i did mentioned about the possible issue with category encoders.

**Comment by rarrudaml** [comment] 2023-04-11 21:41
Can someone help me understanding why dataset size increase in setup step? original dataframe = (2830743, 79). But before setup step I split it in train  (40%) test (60%)

    df['label'] = df['label'].apply(lambda x: 0 if x == 'BENIGN' else 1)
    df_train, df_test  =\
                    train_test_split(df,\
                    test_size=0.6, random_state=4, stratify=df['label'])


My setup parameters:

    bin_geral = setup(df_train ,target = 'label',\
       numeric_imputation=None, memory = False , imputation_type = None, preprocess= False, session_id=31, \
       numeric_features = \
       ['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10', 'x11', \
       'x12', 'x13', 'x14', 'x15', 'x16', 'x17', 'x18', 'x19', 'x20', 'x21', \
       'x22', 'x23', 'x24', 'x25', 'x26', 'x27', 'x28', 'x29', 'x30', 'x31', \
       'x32', 'x33', 'x34', 'x35', 'x36', 'x37', 'x38', 'x39', 'x40', 'x41', \
       'x42', 'x43', 'x44', 'x45', 'x46', 'x47', 'x48', 'x49', 'x50', 'x51', \
       'x52', 'x53', 'x54', 'x55', 'x56', 'x57', 'x58', 'x59', 'x60', 'x61', \
       'x62', 'x63', 'x64', 'x65', 'x66', 'x67', 'x68', 'x69', 'x70', 'x71', \
       'x72', 'x73', 'x74', 'x75', 'x76', 'x77', 'x78'])

**Comment by tvdboom** [comment] 2023-04-12 08:14
This has probably something to do with your dataframe indices. Try adding `index=False` to setup.

**Comment by rarrudaml** [comment] 2023-04-12 16:55
@tvdboom Could it be related with fold replication?

    bin_geral = setup(data= df_train, test_data=df_test ,target = 'label', index = False, fold=4, \
       memory = True , imputation_type = None, preprocess= False, use_gpu = True, \
       numeric_features = \
       ['x1', 'x2', '.... 'x78'])

real (train + test). (A) = 2.830.743
Original data shape SETUP step (B) = 10.838.443
ratio = B/A = 4

Loading dataset...
(2830743, 79)

                   Description           Value
0                   Session id             508
1                       Target           label
2                  Target type          Binary
3          Original data shape  (10838443, 79)
4       Transformed data shape  (10838443, 79)
5  Transformed train set shape   (8746546, 79)
6   Transformed test set shape   (2091897, 79)
7             Numeric features              78

**Comment by tvdboom** [comment] 2023-04-15 16:52
@rarrudaml can you share a reproducible example? in such a way that I can just copy paste the code to try it

**Comment by Yard1** [comment] 2023-04-16 17:55
@rarrudaml, @tahaflex, @microlei could you paste the output of `pycaret.show_versions`?

**Comment by Yard1** [comment] 2023-04-17 18:44
Can you run
```
import pycaret
pycaret.show_versions()
```
and paste the output bere?

**Comment by rarrudaml** [comment] 2023-04-17 18:53
> Can you run
> 
> ```
> import pycaret
> pycaret.show_versions()
> ```
> 
> and paste the output bere?

[pycaret_versions.txt](https://github.com/pycaret/pycaret/files/11254830/pycaret_versions.txt)

**Comment by allansuzuki** [comment] 2023-05-23 09:07
Hi, I'm running the tutorial https://pycaret.gitbook.io/docs/get-started/quickstart#regression and doing same code as in the tutorial:

I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

 I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

**Reproducible code**

```
# load sample dataset - quite fast
from pycaret.datasets import get_data
data = get_data('insurance')

# import and setup - took 55s
from pycaret.regression import *
s = setup(data, target = 'charges', session_id = 123)

# import and setup - don't stop running....
best = s.compare_models()
```

**pycaret.show_versions()**
```
System:
    python: 3.9.16 (main, Jan 11 2023, 16:16:36) [MSC v.1916 64 bit (AMD64)]
executable: [c:----Projetos\-----\-----modelling\.conda\python.exe
   machine: Windows-10-10.0.22621-SP0

PyCaret required dependencies:
                 pip: 22.3.1
          setuptools: 65.6.3
             pycaret: 3.0.2
             IPython: 8.10.0
          ipywidgets: 7.6.5
                tqdm: 4.64.1
               numpy: 1.23.5
              pandas: 1.5.2
              jinja2: 3.1.2
               scipy: 1.10.0
              joblib: 1.2.0
             sklearn: 1.2.1
                pyod: 1.0.8
            imblearn: 0.10.1
   category_encoders: 2.6.0
            lightgbm: 3.3.5
               numba: 0.56.4
            requests: 2.28.1
          matplotlib: 3.6.2
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.14.1
             kaleido: 0.2.1
         statsmodels: 0.13.5
              sktime: 0.16.1
               tbats: 1.1.3
            pmdarima: 2.0.2
              psutil: 5.9.0

PyCaret optional dependencies:
                shap: 0.41.0
           interpret: Not installed
                umap: Not installed
    pandas_profiling: Not installed
  explainerdashboard: Not installed
             autoviz: Not installed
           fairlearn: Not installed
             xgboost: 1.7.4
            catboost: 1.1.1
              kmodes: Not installed
             mlxtend: Not installed
       statsforecast: 1.5.0
        tune_sklearn: Not installed
                 ray: Not installed
            hyperopt: Not installed
              optuna: Not installed
               skopt: Not installed
              mlflow: 2.3.1
              gradio: Not installed
             fastapi: Not installed
             uvicorn: Not installed
              m2cgen: Not installed
           evidently: Not installed
               fugue: 0.8.1
           streamlit: Not installed
             prophet: 1.1.2
```

A friend also tested downgrading to pycaret 3.0.0rc9 and it seems the API is not loading fast

**Comment by allansuzuki** [comment] 2023-05-24 08:44
@tahaflex @moezali1 Do you have a position in this problem? I have an actual work in progress and I depend on it

**Comment by allansuzuki** [comment] 2023-05-24 09:06
I make the tutorial for time series and did not took forever, but took long:
```
# load sample dataset
from pycaret.datasets import get_data
data = get_data('airline')

from pycaret.time_series import *
s = setup(data, fh = 3, fold = 5, session_id = 123)

# functional API
best = s.compare_models()
```
time: 3m 22.2s

while the other mentioned below it's running and it already took +16m (and running...)


> Hi, I'm running the tutorial https://pycaret.gitbook.io/docs/get-started/quickstart#regression and doing same code as in the tutorial:
> 
> I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.
> 
> I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).
> 
> **Reproducible code**
> 
> ```
> # load sample dataset - quite fast
> from pycaret.datasets import get_data
> data = get_data('insurance')
> 
> # import and setup - took 55s
> from pycaret.regression import *
> s = setup(data, target = 'charges', session_id = 123)
> 
> # import and setup - don't stop running....
> best = s.compare_models()
> ```
> 
> **pycaret.show_versions()**
> 
> ```
> System:
>     python: 3.9.16 (main, Jan 11 2023, 16:16:36) [MSC v.1916 64 bit (AMD64)]
> executable: [c:----Projetos\-----\-----modelling\.conda\python.exe
>    machine: Windows-10-10.0.22621-SP0
> 
> PyCaret required dependencies:
>                  pip: 22.3.1
>           setuptools: 65.6.3
>              pycaret: 3.0.2
>              IPython: 8.10.0
>           ipywidgets: 7.6.5
>                 tqdm: 4.64.1
>                numpy: 1.23.5
>               pandas: 1.5.2
>               jinja2: 3.1.2
>                scipy: 1.10.0
>               joblib: 1.2.0
>              sklearn: 1.2.1
>                 pyod: 1.0.8
>             imblearn: 0.10.1
>    category_encoders: 2.6.0
>             lightgbm: 3.3.5
>                numba: 0.56.4
>             requests: 2.28.1
>           matplotlib: 3.6.2
>           scikitplot: 0.3.7
>          yellowbrick: 1.5
>               plotly: 5.14.1
>              kaleido: 0.2.1
>          statsmodels: 0.13.5
>               sktime: 0.16.1
>                tbats: 1.1.3
>             pmdarima: 2.0.2
>               psutil: 5.9.0
> 
> PyCaret optional dependencies:
>                 shap: 0.41.0
>            interpret: Not installed
>                 umap: Not installed
>     pandas_profiling: Not installed
>   explainerdashboard: Not installed
>              autoviz: Not installed
>            fairlearn: Not installed
>              xgboost: 1.7.4
>             catboost: 1.1.1
>               kmodes: Not installed
>              mlxtend: Not installed
>        statsforecast: 1.5.0
>         tune_sklearn: Not installed
>                  ray: Not installed
>             hyperopt: Not installed
>               optuna: Not installed
>                skopt: Not installed
>               mlflow: 2.3.1
>               gradio: Not installed
>              fastapi: Not installed
>              uvicorn: Not installed
>               m2cgen: Not installed
>            evidently: Not installed
>                fugue: 0.8.1
>            streamlit: Not installed
>              prophet: 1.1.2
> ```
> 
> A friend also tested downgrading to pycaret 3.0.0rc9 and it seems the API is not loading fast

**Comment by claywey** [comment] 2023-09-01 21:58
Why is the setup() method calling pipeline.fit? This would be the first explanation for the performance drop. Secondly, if you set the n_jobs parameter greater that 1 in the setup, there's a lot of extract overhead as joblib is persisting large input arguments each time a pipeline step is called it seems. 

https://github.com/pycaret/pycaret/blob/ea88b2d3ee22c080ca5059f2f6f1547952b9451c/pycaret/classification/oop.py#L889C54-L889C54

**Comment by tvdboom** [comment] 2023-09-02 07:52
> Why is the setup() method calling pipeline.fit?

`pipeline.fit` is called in order to get the data properties ending in `_transformed`, e.g. `dataset_transformed`. The fitted pipeline is later used in numerous methods, for example for plotting.

> if you set the n_jobs parameter greater that 1 in the setup, there's a lot of extract overhead as joblib is persisting large input arguments each time a pipeline step is called it seems.

I don't understand what the `n_jobs` parameter has to do with the caching of the pipeline steps you refer to (I think). If you are worried the caching is making it slow, set `memory=None` in setup and see what happens.

**Comment by claywey** [comment] 2023-09-14 01:27
> > Why is the setup() method calling pipeline.fit?
> 
> `pipeline.fit` is called in order to get the data properties ending in `_transformed`, e.g. `dataset_transformed`. The fitted pipeline is later used in numerous methods, for example for plotting.
> 
> > if you set the n_jobs parameter greater that 1 in the setup, there's a lot of extract overhead as joblib is persisting large input arguments each time a pipeline step is called it seems.
> 
> I don't understand what the `n_jobs` parameter has to do with the caching of the pipeline steps you refer to (I think). If you are worried the caching is making it slow, set `memory=None` in setup and see what happens.

But that's exactly my point. The core issue is that there is a big change in behavior in `setup()` from 2.x and 3.0. Let's say I am _not_ performing any downstream plotting and just running `compare_models()` or 'tune_model` or something. The cached transformers are not (and should) not be used and I would have big concerns about data leakage if that were the case.

Look, the behavior change was forced onto the user without giving them an option to turn it off. I don't want you to run a full pipeline fit on my training data during setup. That just not good. Downstream, if I want to plot or perform other tasks, _then_, caching the transformers might make sense. For example, calling something like `plot_model()` or 'evaluate_model()` should cache the transformers upon first use then subsequent calls can use the `dataset_transformed`

When it comes to joblib, the logs are outputting the follow:
`UserWarning: Persisting input arguments took Xs to run. If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped
function (e.g. large strings). THIS IS A JOBLIB ISSUE. If you can, kindly provide the joblib's team with an example so that they can fix the problem.`
The large input arguments are likely the `X_train` and `y_train` getting passed in. My point in calling that out was more of and FYI. Additionally since the default is `memory = True`, there is a lot of I/O overhead incurred while writing out those cached transforms.

**Comment by Yard1** [comment] 2023-09-14 05:15
Actually, in 2.x, the exact same behavior occured, _with the difference_ that the pipeline fitted in `setup()` was also used in model fitting - which indeed lead to data leakage. That has been fixed in 3.0, and the caching system has been introduced as a way to reduce the impact of recreating the pipeline for every model and every fold. The idea is that when you run `compare_models`, the first time each fold is visited, the pipeline will be cached and then reused for subsequent models (sans the model itself, of course). The joblib caching system we are using guarantees that the right cached objects are loaded given the arguments. However, you are correct that this introduces additional hashing and I/O overhead that in some cases may diminish benefits from caching. We will consider changing the default behavior to `memory=False`.

**Comment by hakan-77** [comment] 2024-01-29 00:26
I would like to resurface this issue. 

Cross validation during compare_models() fail for us for any lightgbm version >= v4, and for any data size including ice_cream, iris etc. The only method that works is to exclude lightgbm from compare_models().

After re-installing lightgbm==3.3.5 I observe no other package version has changed, and can confirm everything works as usual.

We have been pinning lightgbm to < 4 for many months now and hope we can find a solution.

[versions.txt](https://github.com/pycaret/pycaret/files/14078448/versions.txt)

**Comment by BradKML** [comment] 2024-11-07 03:57
Keeping an eye on this but for large amounts of categorical data

**Comment by moezali1** [comment] 2026-04-27 15:38
Closing as part of the 4.0 backlog cleanup — see #4177.

PyCaret 4.0 is a ground-up rewrite (OOP-only API, sklearn-native engine, Python 3.11+, sklearn ≥ 1.7) and almost all pre-4.0 issues either reference removed APIs (`setup()`, `plot_model`, `evaluate_model`, `interpret_model`, `automl`, the legacy time-series module, the Streamlit dashboard, …) or no longer reproduce on the new code path.

**If this still affects you in 4.0, please re-file as a new issue** with:

- the experiment constructor call (`Experiment(...)`),
- the operation that fails,
- the full traceback,
- your Python / sklearn / pycaret versions.

Resources for 4.0:

- Docs: https://pycaret.org/docs
- Migrate from 3.x: https://pycaret.org/docs/guides/migrating-from-3-x
- API reference: https://pycaret.org/reference
- FAQ: https://pycaret.org/docs/resources/faqs

Thanks for filing — and apologies for the long latency. The repo had drifted; we're starting clean.
