### ISSUE TITLE
[INSTALL]: Cannot uninstall 'llvmlite'.

### ISSUE THREAD

**Issue by psychoandtech** [pycaret/pycaret#3910] opened 2024-02-19 15:59 UTC
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

no

### Installation Method

pip install

### pycaret Version

latest

### Python Version

python 3.9

### Description

  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.38.0
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

**Comment by celestinoxp** [comment] 2024-02-20 14:19
@psychoandtech 
llvmlite is not a direct dependency on pycaret, I think it is related to the numba package
check with the new version of pycaret 3.3.0... you can use `pip install --upgrade pycaret`

if the problem is resolved you can close this issue, otherwise you should provide more details...

**Closed** 2024-03-12 07:13 UTC
Labels: installation
