### ISSUE TITLE
PyCaret 2.0 overwrites pandas-profiling 2.8 back to 2.3

### ISSUE THREAD

**Issue by dplew** [pycaret/pycaret#351] opened 2020-08-04 18:16 UTC
Related to Issues #276 and #280: 

The aforementioned issues were cleared when pandas-profiling is updated to 2.8.
This may have been addressed in the nightly build.
However, the current install of PyCaret 2.0 removes pandas-profiling 2.8 and replaces with 2.3.
To prevent Issue #280, user needs to manually re-upgrade to pandas-profiling 2.8.
Advise to change PyCaret 2.0 build to keep pandas-profiling 2.8.

**Comment by pycaret** [comment] 2020-08-05 03:41
@dplew Hi. I have created a new conda environment and installed pycaret==2.0. I cannot reproduce the same behavior. I got pandas-profiling==2.8 by default.

This is the instruction I followed: https://www.pycaret.org/install

Can you create a new conda environment and confirm if pycaret==2.0 overwrites pandas-profiling?

**Comment by dplew** [comment] 2020-08-05 04:41
Ah.  Yes I see I missed something (see below for detail).  But perhaps I could amend my suggestion to change the PyCaret 2.0 install to require pandas-profiling 2.8.0 rather than allowing any version >2.3.0 (since 2.3.0 breaks functionality?)

I started in an environment that already had the most recent stable version of PyCaret installed along with pandas-profiling-2.8.0 that I had installed manually.  I then did “pip install pycaret” but did not specify the version number.  Clearly this did not install pycaret 2.0, though I’m not sure which version this was.  Here is a log excerpt from the install which removed 2.8 in favor of 2.3:
Installing collected packages: pandas-profiling
  Attempting uninstall: pandas-profiling
    Found existing installation: pandas-profiling 2.8.0
    Uninstalling pandas-profiling-2.8.0:
      Successfully uninstalled pandas-profiling-2.8.0
Successfully installed pandas-profiling-2.3.0

When I install pycaret 2.0 in a new anaconda environment, I see it picks up my wheel file for pandas-profiling-2.8.0.  This is correct, but I wonder why it should even allow 2.3?

    |████████████████████████████████| 263 kB 3.2 MB/s
Collecting pandas-profiling>=2.3.0
  Using cached pandas_profiling-2.8.0-py2.py3-none-any.whl (259 kB)
Collecting imbalanced-learn
  Using cached imbalanced_learn-0.7.0-py3

**Comment by pycaret** [comment] 2020-08-05 16:15
@dplew Got it. The issue was in PyCaret 1.0. It had a literal dependency to pandas-profiling==2.30. That's why.

The issue is resolved in PyCaret 2.0.

**Closed by pycaret** 2020-08-05 16:15 UTC
Labels: invalid
