### ISSUE TITLE
[BUG]: Getting cannot import name '_boxcox_conf_interval' from 'scipy.stats.morestats' during set up for timeseries

### ISSUE THREAD

**Issue by snamjoshi1** [pycaret/pycaret#2741] opened 2022-07-11 19:20 UTC
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

For pycaret time series API,I am getting the above mentioned error during set up
versions of libraries installed
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
asttokens            2.0.5
attrs                21.4.0
backcall             0.2.0
beautifulsoup4       4.11.1
bleach               4.1.0
category-encoders    2.5.0
certifi              2022.6.15
cffi                 1.15.0
colorama             0.4.5
cycler               0.11.0
Cython               0.29.30
debugpy              1.5.1
decorator            5.1.1
defusedxml           0.7.1
Deprecated           1.2.13
distlib              0.3.4
entrypoints          0.4
et-xmlfile           1.1.0
executing            0.8.3
fastjsonschema       2.15.1
filelock             3.7.1
fonttools            4.34.4
fsspec               2022.5.0
imbalanced-learn     0.9.1
importlib-resources  5.2.0
ipykernel            6.9.1
ipython              8.4.0
ipython-genutils     0.2.0
jedi                 0.18.1
Jinja2               3.0.3
joblib               1.1.0
jsonschema           4.4.0
jupyter-client       7.2.2
jupyter-core         4.10.0
jupyterlab-pygments  0.1.2
kaleido              0.2.1
kiwisolver           1.4.3
lightgbm             3.3.2
llvmlite             0.38.1
MarkupSafe           2.1.1
matplotlib           3.5.2
matplotlib-inline    0.1.3
mistune              0.8.4
nbclient             0.5.13
nbconvert            6.4.4
nbformat             5.3.0
nest-asyncio         1.5.5
notebook             6.4.11
numba                0.55.2
numpy                1.23.1
openpyxl             3.0.10
packaging            21.3
pandas               1.4.3
pandocfilters        1.5.0
parso                0.8.3
patsy                0.5.2
pickleshare          0.7.5
Pillow               9.2.0
pip                  22.1.2
platformdirs         2.5.2
plotly               5.9.0
pluggy               1.0.0
pmdarima             1.8.5
prometheus-client    0.13.1
prompt-toolkit       3.0.30
pure-eval            0.2.2
py                   1.11.0
pycaret-ts-alpha     3.0.0.dev1649017462
pycparser            2.21
Pygments             2.12.0
pyod                 1.0.3
pyparsing            3.0.9
pyrsistent           0.18.0
python-dateutil      2.8.2
pytz                 2022.1
pywin32              302
pywinpty             2.0.2
pyzmq                22.3.0
scikit-learn         1.1.1
scikit-plot          0.3.7
scipy                1.8.1
Send2Trash           1.8.0
setuptools           61.2.0
six                  1.16.0
sktime               0.10.1
soupsieve            2.3.1
stack-data           0.3.0
statsmodels          0.13.2
tbats                1.1.0
tenacity             8.0.1
terminado            0.13.1
testpath             0.6.0
threadpoolctl        3.1.0
toml                 0.10.2
tornado              6.1
tox                  3.25.1
tox-conda            0.9.2
traitlets            5.3.0
typing_extensions    4.1.1
urllib3              1.26.10
virtualenv           20.15.1
wcwidth              0.2.5
webencodings         0.5.1
wheel                0.37.1
wincertstore         0.2
wrapt                1.14.1
yellowbrick          1.4
zipp                 3.8.0

### Reproducible Example

```python
# with functional API
from pycaret.time_series import *
setup(tempdata, fh = 7, fold = 3, session_id = 123)
```

### Expected Behavior

The set up should succeed

### Actual Results

```python-traceback
ImportError                               Traceback (most recent call last)
Input In [5], in <cell line: 2>()
      1 # with functional API
----> 2 from pycaret.time_series import *
      3 setup(tempdata, fh = 7, fold = 3, session_id = 123)

File ~\Anaconda3\envs\pycarettimeseries\lib\site-packages\pycaret\time_series\__init__.py:1, in <module>
----> 1 from pycaret.time_series.forecasting.oop import TSForecastingExperiment
      2 from pycaret.time_series.forecasting.functional import (
      3     setup,
      4     create_model,
   (...)
     25     check_stats,
     26 )
     28 __all__ = [
     29     "TSForecastingExperiment",
     30     "setup",
   (...)
     52     "check_stats",
     53 ]

File ~\Anaconda3\envs\pycarettimeseries\lib\site-packages\pycaret\time_series\forecasting\oop.py:34, in <module>
     31 from pycaret.utils.time_series.forecasting.models import DummyForecaster
     32 from sktime.forecasting.compose import TransformedTargetForecaster
---> 34 from pycaret.internal.preprocess.time_series.forecasting.preprocessor import (
     35     TSForecastingPreprocessor,
     36 )
     38 import pycaret.containers.metrics.time_series
     39 import pycaret.containers.models.time_series

File ~\Anaconda3\envs\pycarettimeseries\lib\site-packages\pycaret\internal\preprocess\time_series\forecasting\preprocessor.py:13, in <module>
     11 from sktime.transformations.series.adapt import TabularToSeriesAdaptor
     12 from sktime.transformations.series.impute import Imputer
---> 13 from sktime.transformations.series.boxcox import BoxCoxTransformer, LogTransformer
     14 from sktime.transformations.series.exponent import ExponentTransformer, SqrtTransformer
     15 from sktime.transformations.series.cos import CosineTransformer

File ~\Anaconda3\envs\pycarettimeseries\lib\site-packages\sktime\transformations\series\boxcox.py:13, in <module>
     11 from scipy.special import boxcox, inv_boxcox
     12 from scipy.stats import boxcox_llf, distributions, variation
---> 13 from scipy.stats.morestats import (
     14     _boxcox_conf_interval,
     15     _calc_uniform_order_statistic_medians,
     16 )
     18 from sktime.transformations.base import BaseTransformer
     19 from sktime.utils.validation import is_int

ImportError: cannot import name '_boxcox_conf_interval' from 'scipy.stats.morestats' (D:\User\snamjoshi\Anaconda3\envs\pycarettimeseries\lib\site-packages\scipy\stats\morestats.py)
```

### Installed Versions

<details>
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
asttokens            2.0.5
attrs                21.4.0
backcall             0.2.0
beautifulsoup4       4.11.1
bleach               4.1.0
category-encoders    2.5.0
certifi              2022.6.15
cffi                 1.15.0
colorama             0.4.5
cycler               0.11.0
Cython               0.29.30
debugpy              1.5.1
decorator            5.1.1
defusedxml           0.7.1
Deprecated           1.2.13
distlib              0.3.4
entrypoints          0.4
et-xmlfile           1.1.0
executing            0.8.3
fastjsonschema       2.15.1
filelock             3.7.1
fonttools            4.34.4
fsspec               2022.5.0
imbalanced-learn     0.9.1
importlib-resources  5.2.0
ipykernel            6.9.1
ipython              8.4.0
ipython-genutils     0.2.0
jedi                 0.18.1
Jinja2               3.0.3
joblib               1.1.0
jsonschema           4.4.0
jupyter-client       7.2.2
jupyter-core         4.10.0
jupyterlab-pygments  0.1.2
kaleido              0.2.1
kiwisolver           1.4.3
lightgbm             3.3.2
llvmlite             0.38.1
MarkupSafe           2.1.1
matplotlib           3.5.2
matplotlib-inline    0.1.3
mistune              0.8.4
nbclient             0.5.13
nbconvert            6.4.4
nbformat             5.3.0
nest-asyncio         1.5.5
notebook             6.4.11
numba                0.55.2
numpy                1.23.1
openpyxl             3.0.10
packaging            21.3
pandas               1.4.3
pandocfilters        1.5.0
parso                0.8.3
patsy                0.5.2
pickleshare          0.7.5
Pillow               9.2.0
pip                  22.1.2
platformdirs         2.5.2
plotly               5.9.0
pluggy               1.0.0
pmdarima             1.8.5
prometheus-client    0.13.1
prompt-toolkit       3.0.30
pure-eval            0.2.2
py                   1.11.0
pycaret-ts-alpha     3.0.0.dev1649017462
pycparser            2.21
Pygments             2.12.0
pyod                 1.0.3
pyparsing            3.0.9
pyrsistent           0.18.0
python-dateutil      2.8.2
pytz                 2022.1
pywin32              302
pywinpty             2.0.2
pyzmq                22.3.0
scikit-learn         1.1.1
scikit-plot          0.3.7
scipy                1.8.1
Send2Trash           1.8.0
setuptools           61.2.0
six                  1.16.0
sktime               0.10.1
soupsieve            2.3.1
stack-data           0.3.0
statsmodels          0.13.2
tbats                1.1.0
tenacity             8.0.1
terminado            0.13.1
testpath             0.6.0
threadpoolctl        3.1.0
toml                 0.10.2
tornado              6.1
tox                  3.25.1
tox-conda            0.9.2
traitlets            5.3.0
typing_extensions    4.1.1
urllib3              1.26.10
virtualenv           20.15.1
wcwidth              0.2.5
webencodings         0.5.1
wheel                0.37.1
wincertstore         0.2
wrapt                1.14.1
yellowbrick          1.4
zipp                 3.8.0
</details>

**Comment by ngupta23** [comment] 2022-07-12 04:47
We have released a fully integrated version of time series (with other modules) now (hence pycaret-ts-alpha is deprecated). Can you try with it to see if the issue persists with the latest version.

`pip install -U --pre pycaret`

**Comment by ngupta23** [comment] 2022-07-23 12:07
@snamjoshi1 We will close this issue for now since we are not able to reproduce it. If the recommendation does not work for you, please feel free to reopen this issue. Thanks!

**Closed by ngupta23** 2022-07-23 12:07 UTC
Labels: bug, time_series
