### ISSUE TITLE
@kmedved I think we can make it work. Here is my working example of how to do it until the functionality is available:

### ISSUE THREAD

**Issue by Prashavu** [pycaret/pycaret#2906] opened 2022-08-24 05:02 UTC
How do I use this fit to predict using pycaret?
I do not think  its working. I fit on lr and used lr to predict, is that the correct way to do it?
@kmedved I think we can make it work. Here is my working example of how to do it until the functionality is available:

```
from pycaret.datasets import get_data
data = get_data('juice')

from pycaret.classification import *
clf1 = setup(data, target = 'Purchase')

lr = create_model('lr')

# now pass sample weights to lr and fit again
import numpy as np
weights = np.arange(get_config('X_train').shape[0])
lr.fit(X = get_config('X_train'), y = get_config('y_train'), sample_weight = weights)
```

_Originally posted by @pycaret in https://github.com/pycaret/pycaret/issues/573#issuecomment-683890030_

**Comment by ngupta23** [comment] 2022-08-25 10:13
@Prashavu What is your issue or question?

**Comment by Prashavu** [comment] 2022-08-25 11:15
@ngupta23 how to give sample_weights for a tuned classifier from setup? is it possible? IF not how else can we do it. If we manually fit , Then we cannot use pycaret `ceeate_model`, 1tune_model` right?

**Comment by mydataag** [comment] 2022-09-01 12:42
Possible duplicate of: https://github.com/pycaret/pycaret/issues/1350

**Comment by tevfikcagridural** [comment] 2022-09-28 18:59
Based on @mydataag’s answer it is possible give sample weights not on `setup` but on `create_model` or `compare_models` within pycaret. Works for both classification and regression

```
import numpy as np
from pycaret.classification import setup, compare_models, get_config 
from pycaret.datasets import get_data 

# Load dataset 
df = get_data('iris')

# Initialize pycaret training environment
setup(df, target='species')

# Weights as pandas Series for 
# all samples based on the df given in setup 
weights = np.random.rand(df.shape[0]) 

# Get index of train data  
idx = get_config('X_train').index

# Compare models with subset set in setup 
compare_models(fit_kwargs={'sample_weight': weights[idx]})
```

**Closed** 2022-12-06 02:31 UTC
Labels: classification, no-issue-activity
